// Copyright 2026 Oleh Mushka
// SPDX-License-Identifier: Apache-2.0

package envoverlay_test

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"

	hconfig "github.com/olegamysk/go-oikumenea/internal/hermenea/config"
	config "github.com/olegamysk/go-oikumenea/internal/platform/config"
	"github.com/olegamysk/go-oikumenea/pkg/config/envoverlay"
)

// updateGolden regenerates docs/reference/env-vars.md instead of asserting it (run:
// `go test ./pkg/config/envoverlay -run EnvVarReference -update`).
var updateGolden = flag.Bool("update", false, "regenerate the env-var reference doc")

const envVarsDocPath = "../../../docs/reference/env-vars.md"

// TestEnvVarReferenceDoc keeps docs/reference/env-vars.md in lockstep with the config schema: the
// table is DERIVED from the struct yaml tags, so a new config field cannot silently miss the doc.
func TestEnvVarReferenceDoc(t *testing.T) {
	want := renderEnvVarsDoc()
	if *updateGolden {
		if err := os.WriteFile(envVarsDocPath, want, 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		return
	}
	got, err := os.ReadFile(envVarsDocPath)
	if err != nil {
		t.Fatalf("read %s: %v (run with -update to generate)", envVarsDocPath, err)
	}
	if !bytes.Equal(bytes.TrimRight(got, "\n"), bytes.TrimRight(want, "\n")) {
		t.Errorf("%s is stale — run: go test ./pkg/config/envoverlay -run EnvVarReference -update", envVarsDocPath)
	}
}

func renderEnvVarsDoc() []byte {
	var b strings.Builder
	b.WriteString("# Environment-variable reference\n\n")
	b.WriteString("> Generated by `pkg/config/envoverlay` — do not edit by hand. Regenerate with\n")
	b.WriteString("> `go test ./pkg/config/envoverlay -run EnvVarReference -update`.\n\n")
	b.WriteString("Every config field is overridable by an environment variable whose name is derived from its\n")
	b.WriteString("YAML path (dashes become `_`, upper-cased, prefix-joined). Env vars **override** the YAML file,\n")
	b.WriteString("and the YAML file is **optional** (env-only boot works). Precedence: real env > `.env` > YAML.\n")
	b.WriteString("See [D-EnvConfig](../architecture/decisions.md).\n\n")
	b.WriteString("`_N_` marks a slice index (e.g. `_0_`); `_<KEY>_` marks a map key. In addition, the database\n")
	b.WriteString("connection can be assembled from discrete parts: `<PREFIX>_DB_HOST`, `_DB_PORT`, `_DB_USER`,\n")
	b.WriteString("`_DB_PASSWORD`, `_DB_NAME`, `_DB_SSLMODE` (used only when `<PREFIX>_POSTGRES_DSN` is unset).\n\n")

	writeTable(&b, "oikumenea — install config", reflect.TypeOf(config.Install{}), "OIKUMENEA", nil)
	// The runtime config embeds witchcraft's base Runtime (service-discovery/diagnostics/health-check
	// httpclient tuning); document only the operator-relevant subset here — everything else is still
	// overridable via the same rule.
	writeTable(&b, "oikumenea — runtime config", reflect.TypeOf(config.Runtime{}), "OIKUMENEA", runtimeKeep)
	writeTable(&b, "hermenea — install config", reflect.TypeOf(hconfig.Install{}), "HERMENEA", nil)

	return []byte(b.String())
}

// runtimeKeep limits the runtime table to the app-relevant tunables + the log level.
func runtimeKeep(path envoverlay.Path) bool {
	if len(path) == 0 {
		return false
	}
	switch path[0] {
	case "default-page-size", "person-purge-grace-hours", "logging":
		return true
	}
	return false
}

func writeTable(b *strings.Builder, title string, t reflect.Type, prefix string, keep func(envoverlay.Path) bool) {
	bindings := envoverlay.Bindings(t, prefix)
	names := make([]string, 0, len(bindings))
	for n := range bindings {
		if keep != nil && !keep(bindings[n]) {
			continue
		}
		names = append(names, n)
	}
	sort.Strings(names)

	fmt.Fprintf(b, "## %s\n\n", title)
	b.WriteString("| Environment variable | YAML path |\n")
	b.WriteString("| --- | --- |\n")
	for _, n := range names {
		fmt.Fprintf(b, "| `%s` | `%s` |\n", n, strings.Join(bindings[n], "."))
	}
	b.WriteString("\n")
}
