// Copyright 2026 Oleh Mushka
// SPDX-License-Identifier: Apache-2.0

// Command gen-ontology-mirror generates the web console's RID decode tables from pkg/rid — the
// single source of truth for the ontology type registry (R-28, review-2026-09).
//
// The console decodes a packed-UUIDv8 RID's service/kind/type bits into a service name + a registry
// token so it can route, label, and render any object without a server lookup. That mapping used to
// be a hand-maintained mirror in web/src/lib/ontology/rid.ts and had drifted (missing services
// 15/16/17/19, "geo" vs "location", stale pre-M41 education types). This tool regenerates it from
// pkg/rid so it cannot drift; a CI drift gate (scripts/gen-ontology-mirror.sh --verify) enforces it.
//
// Usage:
//
//	go run ./tools/gen-ontology-mirror                 # write web/src/lib/ontology/generated-rid.ts
//	go run ./tools/gen-ontology-mirror -out path.ts    # write elsewhere (used by --verify)
//
// The token scheme lives in pkg/rid (rid.TokenOf) — it has a second consumer, the pkg/facet catalog,
// which validates a declaration's object-type token against it (M56 ticket 3).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"sort"

	"github.com/olegamysk/go-oikumenea/pkg/rid"
)

func main() {
	out := flag.String("out", "web/src/lib/ontology/generated-rid.ts", "output path for the generated TS file")
	flag.Parse()

	src := render()
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-ontology-mirror: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-ontology-mirror: wrote %s\n", *out)
}

func render() []byte {
	services := rid.Services()
	types := rid.Types() // sorted by (service, kind, code)
	tokenOf := rid.TokenOf()

	var b bytes.Buffer
	b.WriteString("// GENERATED by tools/gen-ontology-mirror from pkg/rid — DO NOT EDIT.\n")
	b.WriteString("// Run `scripts/gen-ontology-mirror.sh` to regenerate. The RID type registry (pkg/rid,\n")
	b.WriteString("// itself boot-asserted equal to the platform_rid_* SQL seed) is the single source of truth\n")
	b.WriteString("// (R-28, review-2026-09). See tools/gen-ontology-mirror/main.go for the token scheme.\n\n")

	// SERVICE_NAMES
	b.WriteString("export const SERVICE_NAMES: Record<number, string> = {\n")
	svcCodes := make([]int, 0, len(services))
	for c := range services {
		svcCodes = append(svcCodes, c)
	}
	sort.Ints(svcCodes)
	for _, c := range svcCodes {
		fmt.Fprintf(&b, "  %d: %q,\n", c, services[c])
	}
	b.WriteString("};\n\n")

	// RID_TYPES
	b.WriteString("export interface RidTypeInfo {\n")
	b.WriteString("  /** registry token — the key registry.ts is keyed by */\n")
	b.WriteString("  token: string;\n")
	b.WriteString("  /** bare type name from pkg/rid (fallback label for any RID without a registry view) */\n")
	b.WriteString("  name: string;\n")
	b.WriteString("  kind: \"object\" | \"link\" | \"action\";\n")
	b.WriteString("}\n\n")
	b.WriteString("// Keyed by `${service}/${kind}/${typeCode}` (kind 1=object, 2=link, 3=action).\n")
	b.WriteString("export const RID_TYPES: Record<string, RidTypeInfo> = {\n")
	for _, t := range types {
		fmt.Fprintf(&b, "  %q: { token: %q, name: %q, kind: %q },\n",
			fmt.Sprintf("%d/%d/%d", t.Service, t.Kind, t.Code),
			tokenOf[t], t.Name, rid.Kind(t.Kind).String())
	}
	b.WriteString("};\n")

	return b.Bytes()
}
