// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditEntry = `-- name: GetAuditEntry :one
SELECT id, created_at, actor_type, actor_person_id, subsystem, action, target_type, target_id, unit_id, request_id, before, after, outcome FROM oikumenea.audit_log WHERE id = $1
`

// Reads one entry by its Action RID.
func (q *Queries) GetAuditEntry(ctx context.Context, id string) (OikumeneaAuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditEntry, id)
	var i OikumeneaAuditLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActorType,
		&i.ActorPersonID,
		&i.Subsystem,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.UnitID,
		&i.RequestID,
		&i.Before,
		&i.After,
		&i.Outcome,
	)
	return i, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec

INSERT INTO oikumenea.audit_log (
  id, actor_type, actor_person_id, subsystem,
  action, target_type, target_id, unit_id,
  request_id, before, after, outcome
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10, $11, $12
)
`

type InsertAuditEntryParams struct {
	ID            string
	ActorType     string
	ActorPersonID pgtype.Text
	Subsystem     pgtype.Text
	Action        string
	TargetType    string
	TargetID      pgtype.Text
	UnitID        pgtype.Text
	RequestID     string
	Before        []byte
	After         []byte
	Outcome       string
}

// Audit module queries (docs/modules/audit.md). The audit log is append-only: insert + read only,
// never UPDATE/DELETE (reject_mutation() guards it at the DB).
// Records one Action in the same transaction as the write it describes (D-Audit). The id is the
// supplied Action RID (action__<type>); the row commits iff the caller's transaction commits.
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.ID,
		arg.ActorType,
		arg.ActorPersonID,
		arg.Subsystem,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.UnitID,
		arg.RequestID,
		arg.Before,
		arg.After,
		arg.Outcome,
	)
	return err
}

const queryAuditLog = `-- name: QueryAuditLog :many
SELECT id, created_at, actor_type, actor_person_id, subsystem, action, target_type, target_id, unit_id, request_id, before, after, outcome FROM oikumenea.audit_log
WHERE ($1::text IS NULL OR actor_person_id = $1)
  AND ($2::text     IS NULL OR actor_type      = $2)
  AND ($3::text    IS NULL OR target_type     = $3)
  AND ($4::text      IS NULL OR target_id       = $4)
  AND ($5::text        IS NULL OR unit_id         = $5)
  AND ($6::text         IS NULL OR action          = $6)
  AND ($7::text        IS NULL OR outcome         = $7)
  AND ($8::timestamptz   IS NULL OR created_at      >= $8)
  AND ($9::timestamptz   IS NULL OR created_at      <= $9)
  AND (
    $10::text IS NULL
    OR (created_at, id) < ($11::timestamptz, $10::text)
  )
ORDER BY created_at DESC, id DESC
LIMIT $12
`

type QueryAuditLogParams struct {
	ActorPersonID   pgtype.Text
	ActorType       pgtype.Text
	TargetType      pgtype.Text
	TargetID        pgtype.Text
	UnitID          pgtype.Text
	Action          pgtype.Text
	Outcome         pgtype.Text
	Since           pgtype.Timestamptz
	Until           pgtype.Timestamptz
	CursorID        pgtype.Text
	CursorCreatedAt pgtype.Timestamptz
	PageLimit       int32
}

// Filterable, keyset-paginated read over the log (D-Audit: filterable by every audited entity
// type). Ordered newest-first by the (created_at, id) cursor. A NULL filter matches everything.
// page_limit is fetched as N+1 by the caller to detect a further page.
func (q *Queries) QueryAuditLog(ctx context.Context, arg QueryAuditLogParams) ([]OikumeneaAuditLog, error) {
	rows, err := q.db.Query(ctx, queryAuditLog,
		arg.ActorPersonID,
		arg.ActorType,
		arg.TargetType,
		arg.TargetID,
		arg.UnitID,
		arg.Action,
		arg.Outcome,
		arg.Since,
		arg.Until,
		arg.CursorID,
		arg.CursorCreatedAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaAuditLog
	for rows.Next() {
		var i OikumeneaAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorType,
			&i.ActorPersonID,
			&i.Subsystem,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.UnitID,
			&i.RequestID,
			&i.Before,
			&i.After,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
