// Copyright 2026 Oleh Mushka
// SPDX-License-Identifier: Apache-2.0

package facet

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The facet-arg drift guard (M56 / D-ObjectFacets): parity between the hand-written catalog and the
// Conjure contract, checked in BOTH directions against listArgs — the IR-derived mirror generated by
// tools/genfacetargs.
//
// Direction 1 (TestEveryFacetHasItsQueryArg): a declared facet whose derived arg the contract does
// not ship. That facet would be undeliverable — declared, documented, and unreachable.
//
// Direction 2 (TestEveryQueryArgIsFacetOrClassified): a query arg bound to neither a facet nor a
// classified non-facet role. This is the direction that actually decays: someone adds a filter arg
// to a list endpoint, the vocabulary never learns about it, and M57's stats endpoint silently cannot
// group by it. The classification is CHECKED, not merely recorded (a paging class may only cover the
// two paging args; search/traversal must name a real sqlc query they drive) — otherwise the mechanism
// would degenerate into an allowlist that hides exactly the drift it exists to catch.

// TestEveryFacetHasItsQueryArg is direction 1.
func TestEveryFacetHasItsQueryArg(t *testing.T) {
	for _, o := range Default.All() {
		shipped, ok := listArgs[o.Type]
		if !ok {
			t.Errorf("%s: no entry in listArgs — run scripts/gen-action-params.sh", o.Type)
			continue
		}
		byName := map[string]ArgSpec{}
		for _, a := range shipped {
			byName[a.Name] = a
		}
		for _, f := range o.Facets {
			for _, arg := range f.Args() {
				got, ok := byName[arg]
				if !ok {
					t.Errorf("%s.%s declares arg %q but %s ships no such query arg — add it to the contract and run scripts/gen-action-params.sh",
						o.Type, f.Key, arg, o.ListEndpoint)
					continue
				}
				if want := f.ArgType(); got.Type != want {
					t.Errorf("%s.%s arg %q is %s in the contract, but a %s facet must be carried as %s",
						o.Type, f.Key, arg, got.Type, f.Kind, want)
				}
				if got.Optional == f.Required {
					switch {
					case f.Required:
						t.Errorf("%s.%s is declared Required but arg %q is optional<%s> in the contract",
							o.Type, f.Key, arg, got.Type)
					default:
						t.Errorf("%s.%s is not Required but arg %q is non-optional in the contract",
							o.Type, f.Key, arg)
					}
				}
			}
		}
	}
}

// TestEveryQueryArgIsFacetOrClassified is direction 2.
func TestEveryQueryArgIsFacetOrClassified(t *testing.T) {
	for _, o := range Default.All() {
		byFacet := map[string]string{} // arg -> facet key
		for _, f := range o.Facets {
			for _, arg := range f.Args() {
				byFacet[arg] = f.Key
			}
		}
		classified := map[string]NonFacetArg{}
		for _, n := range o.NonFacetArgs {
			classified[n.Arg] = n
		}
		for _, a := range listArgs[o.Type] {
			if _, ok := byFacet[a.Name]; ok {
				continue
			}
			n, ok := classified[a.Name]
			if !ok {
				t.Errorf("%s arg %q is neither a declared facet nor a classifiable non-facet arg — "+
					"declare a Facet in pkg/facet/catalog.go or classify it in NonFacetArgs",
					o.ListEndpoint, a.Name)
				continue
			}
			checkClass(t, o, n, a)
		}
		// An entry classifying an arg the contract does not ship is stale.
		shipped := map[string]bool{}
		for _, a := range listArgs[o.Type] {
			shipped[a.Name] = true
		}
		for _, n := range o.NonFacetArgs {
			if !shipped[n.Arg] {
				t.Errorf("%s: non-facet arg %q is classified but %s ships no such query arg (stale entry)",
					o.Type, n.Arg, o.ListEndpoint)
			}
		}
	}
}

// checkClass holds the class predicates. Each class must EARN its exemption; "it is written down"
// is not enough.
func checkClass(t *testing.T, o ObjectType, n NonFacetArg, a ArgSpec) {
	t.Helper()
	switch n.Class {
	case ClassPaging:
		// Only the two paging args, and only with their contract types — so "paging" cannot be used
		// to wave through an unrelated arg.
		want := map[string]string{"pageSize": "integer", "pageToken": "string"}[a.Name]
		if want == "" {
			t.Errorf("%s arg %q is classified paging, but only pageSize/pageToken may be", o.Type, a.Name)
			return
		}
		if a.Type != want {
			t.Errorf("%s arg %q is classified paging but is %s in the contract, want %s", o.Type, a.Name, a.Type, want)
		}
	case ClassSearch:
		if a.Type != "string" {
			t.Errorf("%s arg %q is classified search but is %s in the contract, want string", o.Type, a.Name, a.Type)
		}
		requireDrivesResolves(t, o, n)
	case ClassTraversal:
		requireDrivesResolves(t, o, n)
	default:
		t.Errorf("%s arg %q carries unknown class %q", o.Type, a.Name, n.Class)
	}
}

// requireDrivesResolves proves a search/traversal exemption names a real named query in the owning
// module's sqlc source. Without this the two classes would be free-text and could excuse anything.
func requireDrivesResolves(t *testing.T, o ObjectType, n NonFacetArg) {
	t.Helper()
	if n.Drives == "" {
		t.Errorf("%s arg %q is classified %s with no Drives", o.Type, n.Arg, n.Class)
		return
	}
	dir := filepath.Join("..", "..", "internal", o.Module, "adapters", "queries")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("%s: read %s: %v", o.Type, dir, err)
	}
	needle := "-- name: " + n.Drives + " "
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".sql") {
			continue
		}
		body, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			t.Fatalf("read %s: %v", e.Name(), err)
		}
		if strings.Contains(string(body), needle) {
			return
		}
	}
	t.Errorf("%s arg %q (class %s) claims to drive %q, but no `%s` query exists under %s — "+
		"the exemption names nothing real", o.Type, n.Arg, n.Class, n.Drives, needle, dir)
}

// TestGeneratedArgsAreNonVacuous is the pkg/listing TestGuardsScanTheModules lesson: a broken
// generator that emitted an empty (or partial) map would make every assertion above pass silently.
func TestGeneratedArgsAreNonVacuous(t *testing.T) {
	if len(listArgs) == 0 {
		t.Fatal("listArgs is empty — args_gen.go was never generated; run scripts/gen-action-params.sh")
	}
	if len(listArgs) != len(Default.All()) {
		t.Errorf("listArgs covers %d object types, the registry has %d — the generated mirror is stale",
			len(listArgs), len(Default.All()))
	}
	facets := 0
	for _, o := range Default.All() {
		args := listArgs[o.Type]
		if len(args) < 3 {
			t.Errorf("%s: only %d query args generated — a list endpoint has at least pageSize/pageToken plus a facet", o.Type, len(args))
		}
		for _, a := range args {
			if a.Name == "" || a.Type == "" {
				t.Errorf("%s: malformed generated arg %+v", o.Type, a)
			}
		}
		facets += len(o.Facets)
	}
	// person (7) + unit (7) today; the floor guards against a catalog that silently emptied out.
	if facets < 14 {
		t.Errorf("the catalog declares only %d facets across %d types — expected at least 14 for M56's person+unit",
			facets, len(Default.All()))
	}
}
