// Code generated by conjure-go. DO NOT EDIT.

package education

import (
	"context"
	"net/http"
	"strconv"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

/*
Institutions, their structure tree (+ closure), buildings, groups, positions/appointments, and the
person bindings (enrollments, dorm stays). Reads gate on `education.read`; structure writes on
`education.manage`; position/appointment writes on `education.position.manage`; person-binding
writes on `education.enrollment.manage`; catalog-kind writes on `education.catalog.manage`. Writes
are audited in-process (D-Audit).
*/
type EducationService interface {
	ListInstitutionKinds(ctx context.Context, authHeader bearertoken.Token) (InstitutionKindList, error)
	// Create or update (by code) an institution-kind catalog entry.
	UpsertInstitutionKind(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertCatalogKindRequest) (InstitutionKind, error)
	// The `university` domain's unit-kind catalog (owned by the tenant service — M41).
	ListUnitKinds(ctx context.Context, authHeader bearertoken.Token) (UnitKindList, error)
	ListDegreeLevels(ctx context.Context, authHeader bearertoken.Token) (DegreeLevelList, error)
	CreateInstitution(ctx context.Context, authHeader bearertoken.Token, requestArg CreateInstitutionRequest) (Institution, error)
	ListInstitutions(ctx context.Context, authHeader bearertoken.Token, queryArg *string, pageSizeArg *int, pageTokenArg *string) (InstitutionPage, error)
	GetInstitution(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string) (Institution, error)
	UpdateInstitution(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string, requestArg UpdateInstitutionRequest) (Institution, error)
	DeleteInstitution(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string) error
	CreateUnit(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string, requestArg CreateUnitRequest) (EducationUnit, error)
	// All active units of an institution with their closure depth from the nearest root.
	ListUnits(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string) (EducationUnitList, error)
	GetUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (EducationUnit, error)
	UpdateUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg UpdateUnitRequest) (EducationUnit, error)
	// Move a unit under a new parent, recomputing the closure. Returns Education:UnitCycleDetected on a cycle.
	ReparentUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg ReparentUnitRequest) (EducationUnit, error)
	CreateBuilding(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string, requestArg CreateBuildingRequest) (Building, error)
	ListBuildings(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string) (BuildingList, error)
	GetBuilding(ctx context.Context, authHeader bearertoken.Token, buildingIdArg string) (Building, error)
	UpdateBuilding(ctx context.Context, authHeader bearertoken.Token, buildingIdArg string, requestArg UpdateBuildingRequest) (Building, error)
	DeleteBuilding(ctx context.Context, authHeader bearertoken.Token, buildingIdArg string) error
	CreateGroup(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg CreateGroupRequest) (Group, error)
	ListGroups(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (GroupList, error)
	GetGroup(ctx context.Context, authHeader bearertoken.Token, groupIdArg string) (Group, error)
	UpdateGroup(ctx context.Context, authHeader bearertoken.Token, groupIdArg string, requestArg UpdateGroupRequest) (Group, error)
	DeleteGroup(ctx context.Context, authHeader bearertoken.Token, groupIdArg string) error
	CreatePosition(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string, requestArg CreatePositionRequest) (EducationPosition, error)
	ListPositions(ctx context.Context, authHeader bearertoken.Token, institutionIdArg string, stateArg *string, pageSizeArg *int, pageTokenArg *string) (PositionPage, error)
	GetPosition(ctx context.Context, authHeader bearertoken.Token, positionIdArg string) (EducationPosition, error)
	UpdatePosition(ctx context.Context, authHeader bearertoken.Token, positionIdArg string, requestArg UpdatePositionRequest) (EducationPosition, error)
	AbolishPosition(ctx context.Context, authHeader bearertoken.Token, positionIdArg string) (EducationPosition, error)
	// Fill a vacant position. Returns Education:PositionAlreadyFilled if already filled.
	FillPosition(ctx context.Context, authHeader bearertoken.Token, positionIdArg string, requestArg FillPositionRequest) (Appointment, error)
	EndAppointment(ctx context.Context, authHeader bearertoken.Token, appointmentIdArg string, requestArg EndAppointmentRequest) (Appointment, error)
	// Read-only list of the education positions a person holds, enriched with title + institution.
	ListPersonAppointments(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (PersonAppointmentList, error)
	ListEnrollments(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (EnrollmentList, error)
	CreateEnrollment(ctx context.Context, authHeader bearertoken.Token, personIdArg string, requestArg UpsertEnrollmentRequest) (Enrollment, error)
	UpdateEnrollment(ctx context.Context, authHeader bearertoken.Token, personIdArg string, enrollmentIdArg string, requestArg UpsertEnrollmentRequest) (Enrollment, error)
	DeleteEnrollment(ctx context.Context, authHeader bearertoken.Token, personIdArg string, enrollmentIdArg string) error
	ListDormitoryStays(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (DormitoryStayList, error)
	CreateDormitoryStay(ctx context.Context, authHeader bearertoken.Token, personIdArg string, requestArg UpsertDormitoryStayRequest) (DormitoryStay, error)
	UpdateDormitoryStay(ctx context.Context, authHeader bearertoken.Token, personIdArg string, stayIdArg string, requestArg UpsertDormitoryStayRequest) (DormitoryStay, error)
	DeleteDormitoryStay(ctx context.Context, authHeader bearertoken.Token, personIdArg string, stayIdArg string) error
}

// RegisterRoutesEducationService registers handlers for the EducationService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesEducationService(router wrouter.Router, impl EducationService, routerParams ...wrouter.RouteParam) error {
	handler := educationServiceHandler{impl: impl}
	resource := wresource.New("educationservice", router)
	if err := resource.Get("ListInstitutionKinds", "/education/v1/institution-kinds", httpserver.NewJSONHandler(handler.HandleListInstitutionKinds, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listInstitutionKinds route")
	}
	if err := resource.Put("UpsertInstitutionKind", "/education/v1/institution-kinds", httpserver.NewJSONHandler(handler.HandleUpsertInstitutionKind, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertInstitutionKind route")
	}
	if err := resource.Get("ListUnitKinds", "/education/v1/unit-kinds", httpserver.NewJSONHandler(handler.HandleListUnitKinds, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listUnitKinds route")
	}
	if err := resource.Get("ListDegreeLevels", "/education/v1/degree-levels", httpserver.NewJSONHandler(handler.HandleListDegreeLevels, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listDegreeLevels route")
	}
	if err := resource.Post("CreateInstitution", "/education/v1/institutions", httpserver.NewJSONHandler(handler.HandleCreateInstitution, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createInstitution route")
	}
	if err := resource.Get("ListInstitutions", "/education/v1/institutions", httpserver.NewJSONHandler(handler.HandleListInstitutions, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listInstitutions route")
	}
	if err := resource.Get("GetInstitution", "/education/v1/institutions/{institutionId}", httpserver.NewJSONHandler(handler.HandleGetInstitution, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getInstitution route")
	}
	if err := resource.Put("UpdateInstitution", "/education/v1/institutions/{institutionId}", httpserver.NewJSONHandler(handler.HandleUpdateInstitution, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateInstitution route")
	}
	if err := resource.Delete("DeleteInstitution", "/education/v1/institutions/{institutionId}", httpserver.NewJSONHandler(handler.HandleDeleteInstitution, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteInstitution route")
	}
	if err := resource.Post("CreateUnit", "/education/v1/institutions/{institutionId}/units", httpserver.NewJSONHandler(handler.HandleCreateUnit, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createUnit route")
	}
	if err := resource.Get("ListUnits", "/education/v1/institutions/{institutionId}/units", httpserver.NewJSONHandler(handler.HandleListUnits, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listUnits route")
	}
	if err := resource.Get("GetUnit", "/education/v1/units/{unitId}", httpserver.NewJSONHandler(handler.HandleGetUnit, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getUnit route")
	}
	if err := resource.Put("UpdateUnit", "/education/v1/units/{unitId}", httpserver.NewJSONHandler(handler.HandleUpdateUnit, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateUnit route")
	}
	if err := resource.Post("ReparentUnit", "/education/v1/units/{unitId}/reparent", httpserver.NewJSONHandler(handler.HandleReparentUnit, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add reparentUnit route")
	}
	if err := resource.Post("CreateBuilding", "/education/v1/institutions/{institutionId}/buildings", httpserver.NewJSONHandler(handler.HandleCreateBuilding, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createBuilding route")
	}
	if err := resource.Get("ListBuildings", "/education/v1/institutions/{institutionId}/buildings", httpserver.NewJSONHandler(handler.HandleListBuildings, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listBuildings route")
	}
	if err := resource.Get("GetBuilding", "/education/v1/buildings/{buildingId}", httpserver.NewJSONHandler(handler.HandleGetBuilding, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getBuilding route")
	}
	if err := resource.Put("UpdateBuilding", "/education/v1/buildings/{buildingId}", httpserver.NewJSONHandler(handler.HandleUpdateBuilding, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateBuilding route")
	}
	if err := resource.Delete("DeleteBuilding", "/education/v1/buildings/{buildingId}", httpserver.NewJSONHandler(handler.HandleDeleteBuilding, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteBuilding route")
	}
	if err := resource.Post("CreateGroup", "/education/v1/units/{unitId}/groups", httpserver.NewJSONHandler(handler.HandleCreateGroup, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createGroup route")
	}
	if err := resource.Get("ListGroups", "/education/v1/units/{unitId}/groups", httpserver.NewJSONHandler(handler.HandleListGroups, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listGroups route")
	}
	if err := resource.Get("GetGroup", "/education/v1/groups/{groupId}", httpserver.NewJSONHandler(handler.HandleGetGroup, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getGroup route")
	}
	if err := resource.Put("UpdateGroup", "/education/v1/groups/{groupId}", httpserver.NewJSONHandler(handler.HandleUpdateGroup, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateGroup route")
	}
	if err := resource.Delete("DeleteGroup", "/education/v1/groups/{groupId}", httpserver.NewJSONHandler(handler.HandleDeleteGroup, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteGroup route")
	}
	if err := resource.Post("CreatePosition", "/education/v1/institutions/{institutionId}/positions", httpserver.NewJSONHandler(handler.HandleCreatePosition, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createPosition route")
	}
	if err := resource.Get("ListPositions", "/education/v1/institutions/{institutionId}/positions", httpserver.NewJSONHandler(handler.HandleListPositions, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPositions route")
	}
	if err := resource.Get("GetPosition", "/education/v1/positions/{positionId}", httpserver.NewJSONHandler(handler.HandleGetPosition, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getPosition route")
	}
	if err := resource.Put("UpdatePosition", "/education/v1/positions/{positionId}", httpserver.NewJSONHandler(handler.HandleUpdatePosition, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updatePosition route")
	}
	if err := resource.Post("AbolishPosition", "/education/v1/positions/{positionId}/abolish", httpserver.NewJSONHandler(handler.HandleAbolishPosition, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add abolishPosition route")
	}
	if err := resource.Post("FillPosition", "/education/v1/positions/{positionId}/fill", httpserver.NewJSONHandler(handler.HandleFillPosition, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add fillPosition route")
	}
	if err := resource.Post("EndAppointment", "/education/v1/appointments/{appointmentId}/end", httpserver.NewJSONHandler(handler.HandleEndAppointment, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add endAppointment route")
	}
	if err := resource.Get("ListPersonAppointments", "/education/v1/persons/{personId}/appointments", httpserver.NewJSONHandler(handler.HandleListPersonAppointments, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPersonAppointments route")
	}
	if err := resource.Get("ListEnrollments", "/education/v1/persons/{personId}/enrollments", httpserver.NewJSONHandler(handler.HandleListEnrollments, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listEnrollments route")
	}
	if err := resource.Post("CreateEnrollment", "/education/v1/persons/{personId}/enrollments", httpserver.NewJSONHandler(handler.HandleCreateEnrollment, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createEnrollment route")
	}
	if err := resource.Put("UpdateEnrollment", "/education/v1/persons/{personId}/enrollments/{enrollmentId}", httpserver.NewJSONHandler(handler.HandleUpdateEnrollment, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateEnrollment route")
	}
	if err := resource.Delete("DeleteEnrollment", "/education/v1/persons/{personId}/enrollments/{enrollmentId}", httpserver.NewJSONHandler(handler.HandleDeleteEnrollment, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteEnrollment route")
	}
	if err := resource.Get("ListDormitoryStays", "/education/v1/persons/{personId}/dormitory-stays", httpserver.NewJSONHandler(handler.HandleListDormitoryStays, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listDormitoryStays route")
	}
	if err := resource.Post("CreateDormitoryStay", "/education/v1/persons/{personId}/dormitory-stays", httpserver.NewJSONHandler(handler.HandleCreateDormitoryStay, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createDormitoryStay route")
	}
	if err := resource.Put("UpdateDormitoryStay", "/education/v1/persons/{personId}/dormitory-stays/{stayId}", httpserver.NewJSONHandler(handler.HandleUpdateDormitoryStay, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateDormitoryStay route")
	}
	if err := resource.Delete("DeleteDormitoryStay", "/education/v1/persons/{personId}/dormitory-stays/{stayId}", httpserver.NewJSONHandler(handler.HandleDeleteDormitoryStay, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteDormitoryStay route")
	}
	return nil
}

type educationServiceHandler struct {
	impl EducationService
}

func (e *educationServiceHandler) HandleListInstitutionKinds(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := e.impl.ListInstitutionKinds(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpsertInstitutionKind(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertCatalogKindRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpsertInstitutionKind(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListUnitKinds(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := e.impl.ListUnitKinds(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListDegreeLevels(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := e.impl.ListDegreeLevels(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleCreateInstitution(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateInstitutionRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.CreateInstitution(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListInstitutions(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var pageSizeArg *int
	if pageSizeArgStr := req.URL.Query().Get("pageSize"); pageSizeArgStr != "" {
		pageSizeArgInternal, err := strconv.Atoi(pageSizeArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"pageSize\" as integer")
		}
		pageSizeArg = &pageSizeArgInternal
	}
	var pageTokenArg *string
	if pageTokenArgStr := req.URL.Query().Get("pageToken"); pageTokenArgStr != "" {
		pageTokenArgInternal := pageTokenArgStr
		pageTokenArg = &pageTokenArgInternal
	}
	respArg, err := e.impl.ListInstitutions(req.Context(), bearertoken.Token(authHeader), queryArg, pageSizeArg, pageTokenArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleGetInstitution(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	respArg, err := e.impl.GetInstitution(req.Context(), bearertoken.Token(authHeader), institutionIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpdateInstitution(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	var requestArg UpdateInstitutionRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpdateInstitution(req.Context(), bearertoken.Token(authHeader), institutionIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleDeleteInstitution(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	if err := e.impl.DeleteInstitution(req.Context(), bearertoken.Token(authHeader), institutionIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (e *educationServiceHandler) HandleCreateUnit(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	var requestArg CreateUnitRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.CreateUnit(req.Context(), bearertoken.Token(authHeader), institutionIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListUnits(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	respArg, err := e.impl.ListUnits(req.Context(), bearertoken.Token(authHeader), institutionIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleGetUnit(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := e.impl.GetUnit(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpdateUnit(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg UpdateUnitRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpdateUnit(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleReparentUnit(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg ReparentUnitRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.ReparentUnit(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleCreateBuilding(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	var requestArg CreateBuildingRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.CreateBuilding(req.Context(), bearertoken.Token(authHeader), institutionIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListBuildings(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	respArg, err := e.impl.ListBuildings(req.Context(), bearertoken.Token(authHeader), institutionIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleGetBuilding(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	buildingIdArg, ok := pathParams["buildingId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"buildingId\" not present")
	}
	respArg, err := e.impl.GetBuilding(req.Context(), bearertoken.Token(authHeader), buildingIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpdateBuilding(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	buildingIdArg, ok := pathParams["buildingId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"buildingId\" not present")
	}
	var requestArg UpdateBuildingRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpdateBuilding(req.Context(), bearertoken.Token(authHeader), buildingIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleDeleteBuilding(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	buildingIdArg, ok := pathParams["buildingId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"buildingId\" not present")
	}
	if err := e.impl.DeleteBuilding(req.Context(), bearertoken.Token(authHeader), buildingIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (e *educationServiceHandler) HandleCreateGroup(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg CreateGroupRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.CreateGroup(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListGroups(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := e.impl.ListGroups(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleGetGroup(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	groupIdArg, ok := pathParams["groupId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"groupId\" not present")
	}
	respArg, err := e.impl.GetGroup(req.Context(), bearertoken.Token(authHeader), groupIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpdateGroup(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	groupIdArg, ok := pathParams["groupId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"groupId\" not present")
	}
	var requestArg UpdateGroupRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpdateGroup(req.Context(), bearertoken.Token(authHeader), groupIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleDeleteGroup(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	groupIdArg, ok := pathParams["groupId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"groupId\" not present")
	}
	if err := e.impl.DeleteGroup(req.Context(), bearertoken.Token(authHeader), groupIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (e *educationServiceHandler) HandleCreatePosition(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	var requestArg CreatePositionRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.CreatePosition(req.Context(), bearertoken.Token(authHeader), institutionIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListPositions(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	institutionIdArg, ok := pathParams["institutionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"institutionId\" not present")
	}
	var stateArg *string
	if stateArgStr := req.URL.Query().Get("state"); stateArgStr != "" {
		stateArgInternal := stateArgStr
		stateArg = &stateArgInternal
	}
	var pageSizeArg *int
	if pageSizeArgStr := req.URL.Query().Get("pageSize"); pageSizeArgStr != "" {
		pageSizeArgInternal, err := strconv.Atoi(pageSizeArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"pageSize\" as integer")
		}
		pageSizeArg = &pageSizeArgInternal
	}
	var pageTokenArg *string
	if pageTokenArgStr := req.URL.Query().Get("pageToken"); pageTokenArgStr != "" {
		pageTokenArgInternal := pageTokenArgStr
		pageTokenArg = &pageTokenArgInternal
	}
	respArg, err := e.impl.ListPositions(req.Context(), bearertoken.Token(authHeader), institutionIdArg, stateArg, pageSizeArg, pageTokenArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleGetPosition(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	positionIdArg, ok := pathParams["positionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"positionId\" not present")
	}
	respArg, err := e.impl.GetPosition(req.Context(), bearertoken.Token(authHeader), positionIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpdatePosition(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	positionIdArg, ok := pathParams["positionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"positionId\" not present")
	}
	var requestArg UpdatePositionRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpdatePosition(req.Context(), bearertoken.Token(authHeader), positionIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleAbolishPosition(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	positionIdArg, ok := pathParams["positionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"positionId\" not present")
	}
	respArg, err := e.impl.AbolishPosition(req.Context(), bearertoken.Token(authHeader), positionIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleFillPosition(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	positionIdArg, ok := pathParams["positionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"positionId\" not present")
	}
	var requestArg FillPositionRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.FillPosition(req.Context(), bearertoken.Token(authHeader), positionIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleEndAppointment(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	appointmentIdArg, ok := pathParams["appointmentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"appointmentId\" not present")
	}
	var requestArg EndAppointmentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.EndAppointment(req.Context(), bearertoken.Token(authHeader), appointmentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListPersonAppointments(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	respArg, err := e.impl.ListPersonAppointments(req.Context(), bearertoken.Token(authHeader), personIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleListEnrollments(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	respArg, err := e.impl.ListEnrollments(req.Context(), bearertoken.Token(authHeader), personIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleCreateEnrollment(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	var requestArg UpsertEnrollmentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.CreateEnrollment(req.Context(), bearertoken.Token(authHeader), personIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpdateEnrollment(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	enrollmentIdArg, ok := pathParams["enrollmentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"enrollmentId\" not present")
	}
	var requestArg UpsertEnrollmentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpdateEnrollment(req.Context(), bearertoken.Token(authHeader), personIdArg, enrollmentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleDeleteEnrollment(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	enrollmentIdArg, ok := pathParams["enrollmentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"enrollmentId\" not present")
	}
	if err := e.impl.DeleteEnrollment(req.Context(), bearertoken.Token(authHeader), personIdArg, enrollmentIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (e *educationServiceHandler) HandleListDormitoryStays(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	respArg, err := e.impl.ListDormitoryStays(req.Context(), bearertoken.Token(authHeader), personIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleCreateDormitoryStay(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	var requestArg UpsertDormitoryStayRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.CreateDormitoryStay(req.Context(), bearertoken.Token(authHeader), personIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleUpdateDormitoryStay(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	stayIdArg, ok := pathParams["stayId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"stayId\" not present")
	}
	var requestArg UpsertDormitoryStayRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := e.impl.UpdateDormitoryStay(req.Context(), bearertoken.Token(authHeader), personIdArg, stayIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (e *educationServiceHandler) HandleDeleteDormitoryStay(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	stayIdArg, ok := pathParams["stayId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"stayId\" not present")
	}
	if err := e.impl.DeleteDormitoryStay(req.Context(), bearertoken.Token(authHeader), personIdArg, stayIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}
