// Code generated by conjure-go. DO NOT EDIT.

package education

import (
	"github.com/palantir/pkg/datetime"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

// A person filling an education position (link__holds_education_position), one-holder, effective-dated.
type Appointment struct {
	Id            string             `json:"id"`
	PersonId      string             `json:"personId"`
	PositionId    string             `json:"positionId"`
	Status        string             `json:"status"`
	EffectiveFrom datetime.DateTime  `json:"effectiveFrom"`
	EffectiveTo   *datetime.DateTime `json:"effectiveTo,omitempty"`
	CreatedAt     datetime.DateTime  `json:"createdAt"`
	UpdatedAt     datetime.DateTime  `json:"updatedAt"`
}

func (o Appointment) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Appointment) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A physical building of an institution (optionally a unit), located via the shared M19 location.
type Building struct {
	Id            string  `json:"id"`
	InstitutionId string  `json:"institutionId"`
	UnitId        *string `json:"unitId,omitempty"`
	// The shared location RID (M19); null until geocoded.
	LocationId *string           `json:"locationId,omitempty"`
	Code       string            `json:"code"`
	Name       map[string]string `json:"name"`
	// One of academic | dormitory | administrative | library | sports | other.
	Kind      string            `json:"kind"`
	CreatedAt datetime.DateTime `json:"createdAt"`
	UpdatedAt datetime.DateTime `json:"updatedAt"`
}

func (o Building) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpBuilding Building
	return safejson.Marshal(_tmpBuilding(o))
}

func (o *Building) UnmarshalJSON(data []byte) error {
	type _tmpBuilding Building
	var rawBuilding _tmpBuilding
	if err := safejson.Unmarshal(data, &rawBuilding); err != nil {
		return err
	}
	if rawBuilding.Name == nil {
		rawBuilding.Name = make(map[string]string)
	}
	*o = Building(rawBuilding)
	return nil
}

func (o Building) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Building) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type BuildingList struct {
	Buildings []Building `json:"buildings"`
}

func (o BuildingList) MarshalJSON() ([]byte, error) {
	if o.Buildings == nil {
		o.Buildings = make([]Building, 0)
	}
	type _tmpBuildingList BuildingList
	return safejson.Marshal(_tmpBuildingList(o))
}

func (o *BuildingList) UnmarshalJSON(data []byte) error {
	type _tmpBuildingList BuildingList
	var rawBuildingList _tmpBuildingList
	if err := safejson.Unmarshal(data, &rawBuildingList); err != nil {
		return err
	}
	if rawBuildingList.Buildings == nil {
		rawBuildingList.Buildings = make([]Building, 0)
	}
	*o = BuildingList(rawBuildingList)
	return nil
}

func (o BuildingList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BuildingList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CreateBuildingRequest struct {
	Code       string  `json:"code"`
	Name       string  `json:"name"`
	Kind       string  `json:"kind"`
	UnitId     *string `json:"unitId,omitempty"`
	LocationId *string `json:"locationId,omitempty"`
}

func (o CreateBuildingRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateBuildingRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CreateGroupRequest struct {
	Code          string `json:"code"`
	Name          string `json:"name"`
	AdmissionYear *int   `json:"admissionYear,omitempty"`
}

func (o CreateGroupRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateGroupRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CreateInstitutionRequest struct {
	Code      string  `json:"code"`
	Name      string  `json:"name"`
	KindId    string  `json:"kindId"`
	CountryId *string `json:"countryId,omitempty"`
	FoundedOn *string `json:"foundedOn,omitempty"`
	ClosedOn  *string `json:"closedOn,omitempty"`
}

func (o CreateInstitutionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateInstitutionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Create a billet (vacant) owned by the institution or one of its units.
type CreatePositionRequest struct {
	Code      string  `json:"code"`
	Title     string  `json:"title"`
	UnitId    *string `json:"unitId,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

func (o CreatePositionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreatePositionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CreateUnitRequest struct {
	Code   string `json:"code"`
	Name   string `json:"name"`
	KindId string `json:"kindId"`
	// The parent unit (same institution); omit for a top-level unit.
	ParentId  *string `json:"parentId,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

func (o CreateUnitRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateUnitRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// An ISCED 2011 degree level (0..8), a migration-seeded reference scale.
type DegreeLevel struct {
	Id         string            `json:"id"`
	Code       string            `json:"code"`
	Name       map[string]string `json:"name"`
	IscedLevel int               `json:"iscedLevel"`
	Status     string            `json:"status"`
	SortOrder  *int              `json:"sortOrder,omitempty"`
}

func (o DegreeLevel) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpDegreeLevel DegreeLevel
	return safejson.Marshal(_tmpDegreeLevel(o))
}

func (o *DegreeLevel) UnmarshalJSON(data []byte) error {
	type _tmpDegreeLevel DegreeLevel
	var rawDegreeLevel _tmpDegreeLevel
	if err := safejson.Unmarshal(data, &rawDegreeLevel); err != nil {
		return err
	}
	if rawDegreeLevel.Name == nil {
		rawDegreeLevel.Name = make(map[string]string)
	}
	*o = DegreeLevel(rawDegreeLevel)
	return nil
}

func (o DegreeLevel) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *DegreeLevel) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type DegreeLevelList struct {
	DegreeLevels []DegreeLevel `json:"degreeLevels"`
}

func (o DegreeLevelList) MarshalJSON() ([]byte, error) {
	if o.DegreeLevels == nil {
		o.DegreeLevels = make([]DegreeLevel, 0)
	}
	type _tmpDegreeLevelList DegreeLevelList
	return safejson.Marshal(_tmpDegreeLevelList(o))
}

func (o *DegreeLevelList) UnmarshalJSON(data []byte) error {
	type _tmpDegreeLevelList DegreeLevelList
	var rawDegreeLevelList _tmpDegreeLevelList
	if err := safejson.Unmarshal(data, &rawDegreeLevelList); err != nil {
		return err
	}
	if rawDegreeLevelList.DegreeLevels == nil {
		rawDegreeLevelList.DegreeLevels = make([]DegreeLevel, 0)
	}
	*o = DegreeLevelList(rawDegreeLevelList)
	return nil
}

func (o DegreeLevelList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *DegreeLevelList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A person RESIDED_IN_DORMITORY — a dedicated stay (person ↔ dorm building, room, period).
type DormitoryStay struct {
	Id         string  `json:"id"`
	PersonId   string  `json:"personId"`
	BuildingId string  `json:"buildingId"`
	Room       *string `json:"room,omitempty"`
	// One of active | ended.
	Status        string            `json:"status"`
	EffectiveFrom *string           `json:"effectiveFrom,omitempty"`
	EffectiveTo   *string           `json:"effectiveTo,omitempty"`
	CreatedAt     datetime.DateTime `json:"createdAt"`
	UpdatedAt     datetime.DateTime `json:"updatedAt"`
}

func (o DormitoryStay) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *DormitoryStay) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type DormitoryStayList struct {
	DormitoryStays []DormitoryStay `json:"dormitoryStays"`
}

func (o DormitoryStayList) MarshalJSON() ([]byte, error) {
	if o.DormitoryStays == nil {
		o.DormitoryStays = make([]DormitoryStay, 0)
	}
	type _tmpDormitoryStayList DormitoryStayList
	return safejson.Marshal(_tmpDormitoryStayList(o))
}

func (o *DormitoryStayList) UnmarshalJSON(data []byte) error {
	type _tmpDormitoryStayList DormitoryStayList
	var rawDormitoryStayList _tmpDormitoryStayList
	if err := safejson.Unmarshal(data, &rawDormitoryStayList); err != nil {
		return err
	}
	if rawDormitoryStayList.DormitoryStays == nil {
		rawDormitoryStayList.DormitoryStays = make([]DormitoryStay, 0)
	}
	*o = DormitoryStayList(rawDormitoryStayList)
	return nil
}

func (o DormitoryStayList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *DormitoryStayList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
An institution/unit-owned billet (mirrors membership Position) — exists while vacant; carries
no authority. The current holder is populated on get/list (null when vacant).
*/
type EducationPosition struct {
	Id            string            `json:"id"`
	InstitutionId string            `json:"institutionId"`
	UnitId        *string           `json:"unitId,omitempty"`
	Code          string            `json:"code"`
	Title         map[string]string `json:"title"`
	Status        string            `json:"status"`
	SortOrder     *int              `json:"sortOrder,omitempty"`
	Holder        *Appointment      `json:"holder,omitempty"`
	CreatedAt     datetime.DateTime `json:"createdAt"`
	UpdatedAt     datetime.DateTime `json:"updatedAt"`
}

func (o EducationPosition) MarshalJSON() ([]byte, error) {
	if o.Title == nil {
		o.Title = make(map[string]string)
	}
	type _tmpEducationPosition EducationPosition
	return safejson.Marshal(_tmpEducationPosition(o))
}

func (o *EducationPosition) UnmarshalJSON(data []byte) error {
	type _tmpEducationPosition EducationPosition
	var rawEducationPosition _tmpEducationPosition
	if err := safejson.Unmarshal(data, &rawEducationPosition); err != nil {
		return err
	}
	if rawEducationPosition.Title == nil {
		rawEducationPosition.Title = make(map[string]string)
	}
	*o = EducationPosition(rawEducationPosition)
	return nil
}

func (o EducationPosition) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *EducationPosition) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A node in an institution's recursive structure tree (campus → faculty → department → chair).
type EducationUnit struct {
	Id            string `json:"id"`
	InstitutionId string `json:"institutionId"`
	// The parent unit RID; null for a top-level unit.
	ParentId  *string           `json:"parentId,omitempty"`
	KindId    string            `json:"kindId"`
	Code      string            `json:"code"`
	Name      map[string]string `json:"name"`
	Status    string            `json:"status"`
	SortOrder *int              `json:"sortOrder,omitempty"`
	// Distance from the queried root (populated by list-by-institution via the closure).
	Depth     *int              `json:"depth,omitempty"`
	CreatedAt datetime.DateTime `json:"createdAt"`
	UpdatedAt datetime.DateTime `json:"updatedAt"`
}

func (o EducationUnit) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpEducationUnit EducationUnit
	return safejson.Marshal(_tmpEducationUnit(o))
}

func (o *EducationUnit) UnmarshalJSON(data []byte) error {
	type _tmpEducationUnit EducationUnit
	var rawEducationUnit _tmpEducationUnit
	if err := safejson.Unmarshal(data, &rawEducationUnit); err != nil {
		return err
	}
	if rawEducationUnit.Name == nil {
		rawEducationUnit.Name = make(map[string]string)
	}
	*o = EducationUnit(rawEducationUnit)
	return nil
}

func (o EducationUnit) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *EducationUnit) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type EducationUnitList struct {
	Units []EducationUnit `json:"units"`
}

func (o EducationUnitList) MarshalJSON() ([]byte, error) {
	if o.Units == nil {
		o.Units = make([]EducationUnit, 0)
	}
	type _tmpEducationUnitList EducationUnitList
	return safejson.Marshal(_tmpEducationUnitList(o))
}

func (o *EducationUnitList) UnmarshalJSON(data []byte) error {
	type _tmpEducationUnitList EducationUnitList
	var rawEducationUnitList _tmpEducationUnitList
	if err := safejson.Unmarshal(data, &rawEducationUnitList); err != nil {
		return err
	}
	if rawEducationUnitList.Units == nil {
		rawEducationUnitList.Units = make([]EducationUnit, 0)
	}
	*o = EducationUnitList(rawEducationUnitList)
	return nil
}

func (o EducationUnitList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *EducationUnitList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type EndAppointmentRequest struct {
	EffectiveTo *datetime.DateTime `json:"effectiveTo,omitempty"`
}

func (o EndAppointmentRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *EndAppointmentRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A person STUDIED_AT an institution (optionally a unit/group), with an ISCED level + qualification.
type Enrollment struct {
	Id            string  `json:"id"`
	PersonId      string  `json:"personId"`
	InstitutionId string  `json:"institutionId"`
	UnitId        *string `json:"unitId,omitempty"`
	GroupId       *string `json:"groupId,omitempty"`
	// The program studied (education_programs); null if unspecified.
	ProgramId     *string `json:"programId,omitempty"`
	DegreeLevelId *string `json:"degreeLevelId,omitempty"`
	FieldOfStudy  *string `json:"fieldOfStudy,omitempty"`
	StudentNumber *string `json:"studentNumber,omitempty"`
	// One of enrolled | graduated | withdrawn | expelled | on_leave.
	Status        string            `json:"status"`
	Qualification *string           `json:"qualification,omitempty"`
	EffectiveFrom *string           `json:"effectiveFrom,omitempty"`
	EffectiveTo   *string           `json:"effectiveTo,omitempty"`
	CreatedAt     datetime.DateTime `json:"createdAt"`
	UpdatedAt     datetime.DateTime `json:"updatedAt"`
}

func (o Enrollment) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Enrollment) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type EnrollmentList struct {
	Enrollments []Enrollment `json:"enrollments"`
}

func (o EnrollmentList) MarshalJSON() ([]byte, error) {
	if o.Enrollments == nil {
		o.Enrollments = make([]Enrollment, 0)
	}
	type _tmpEnrollmentList EnrollmentList
	return safejson.Marshal(_tmpEnrollmentList(o))
}

func (o *EnrollmentList) UnmarshalJSON(data []byte) error {
	type _tmpEnrollmentList EnrollmentList
	var rawEnrollmentList _tmpEnrollmentList
	if err := safejson.Unmarshal(data, &rawEnrollmentList); err != nil {
		return err
	}
	if rawEnrollmentList.Enrollments == nil {
		rawEnrollmentList.Enrollments = make([]Enrollment, 0)
	}
	*o = EnrollmentList(rawEnrollmentList)
	return nil
}

func (o EnrollmentList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *EnrollmentList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type FillPositionRequest struct {
	PersonId      string             `json:"personId"`
	EffectiveFrom *datetime.DateTime `json:"effectiveFrom,omitempty"`
}

func (o FillPositionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *FillPositionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A cohort (study group) under a unit, with an admission year.
type Group struct {
	Id            string            `json:"id"`
	UnitId        string            `json:"unitId"`
	Code          string            `json:"code"`
	Name          map[string]string `json:"name"`
	AdmissionYear *int              `json:"admissionYear,omitempty"`
	Status        string            `json:"status"`
	CreatedAt     datetime.DateTime `json:"createdAt"`
	UpdatedAt     datetime.DateTime `json:"updatedAt"`
}

func (o Group) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpGroup Group
	return safejson.Marshal(_tmpGroup(o))
}

func (o *Group) UnmarshalJSON(data []byte) error {
	type _tmpGroup Group
	var rawGroup _tmpGroup
	if err := safejson.Unmarshal(data, &rawGroup); err != nil {
		return err
	}
	if rawGroup.Name == nil {
		rawGroup.Name = make(map[string]string)
	}
	*o = Group(rawGroup)
	return nil
}

func (o Group) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Group) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type GroupList struct {
	Groups []Group `json:"groups"`
}

func (o GroupList) MarshalJSON() ([]byte, error) {
	if o.Groups == nil {
		o.Groups = make([]Group, 0)
	}
	type _tmpGroupList GroupList
	return safejson.Marshal(_tmpGroupList(o))
}

func (o *GroupList) UnmarshalJSON(data []byte) error {
	type _tmpGroupList GroupList
	var rawGroupList _tmpGroupList
	if err := safejson.Unmarshal(data, &rawGroupList); err != nil {
		return err
	}
	if rawGroupList.Groups == nil {
		rawGroupList.Groups = make([]Group, 0)
	}
	*o = GroupList(rawGroupList)
	return nil
}

func (o GroupList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *GroupList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// An external reference institution (where people studied/taught). Soft-deleted, not destroyed.
type Institution struct {
	Id     string            `json:"id"`
	Code   string            `json:"code"`
	Name   map[string]string `json:"name"`
	KindId string            `json:"kindId"`
	// The institution's country RID (geo_countries); null for international/online.
	CountryId *string `json:"countryId,omitempty"`
	FoundedOn *string `json:"foundedOn,omitempty"`
	ClosedOn  *string `json:"closedOn,omitempty"`
	// One of active | closed | merged.
	State     string            `json:"state"`
	CreatedAt datetime.DateTime `json:"createdAt"`
	UpdatedAt datetime.DateTime `json:"updatedAt"`
}

func (o Institution) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpInstitution Institution
	return safejson.Marshal(_tmpInstitution(o))
}

func (o *Institution) UnmarshalJSON(data []byte) error {
	type _tmpInstitution Institution
	var rawInstitution _tmpInstitution
	if err := safejson.Unmarshal(data, &rawInstitution); err != nil {
		return err
	}
	if rawInstitution.Name == nil {
		rawInstitution.Name = make(map[string]string)
	}
	*o = Institution(rawInstitution)
	return nil
}

func (o Institution) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Institution) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// An instance-admin catalog entry classifying an institution (university/school/…).
type InstitutionKind struct {
	Id   string `json:"id"`
	Code string `json:"code"`
	// Default-locale fallback + i18n translations.
	Name      map[string]string `json:"name"`
	Status    string            `json:"status"`
	SortOrder *int              `json:"sortOrder,omitempty"`
}

func (o InstitutionKind) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpInstitutionKind InstitutionKind
	return safejson.Marshal(_tmpInstitutionKind(o))
}

func (o *InstitutionKind) UnmarshalJSON(data []byte) error {
	type _tmpInstitutionKind InstitutionKind
	var rawInstitutionKind _tmpInstitutionKind
	if err := safejson.Unmarshal(data, &rawInstitutionKind); err != nil {
		return err
	}
	if rawInstitutionKind.Name == nil {
		rawInstitutionKind.Name = make(map[string]string)
	}
	*o = InstitutionKind(rawInstitutionKind)
	return nil
}

func (o InstitutionKind) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *InstitutionKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type InstitutionKindList struct {
	InstitutionKinds []InstitutionKind `json:"institutionKinds"`
}

func (o InstitutionKindList) MarshalJSON() ([]byte, error) {
	if o.InstitutionKinds == nil {
		o.InstitutionKinds = make([]InstitutionKind, 0)
	}
	type _tmpInstitutionKindList InstitutionKindList
	return safejson.Marshal(_tmpInstitutionKindList(o))
}

func (o *InstitutionKindList) UnmarshalJSON(data []byte) error {
	type _tmpInstitutionKindList InstitutionKindList
	var rawInstitutionKindList _tmpInstitutionKindList
	if err := safejson.Unmarshal(data, &rawInstitutionKindList); err != nil {
		return err
	}
	if rawInstitutionKindList.InstitutionKinds == nil {
		rawInstitutionKindList.InstitutionKinds = make([]InstitutionKind, 0)
	}
	*o = InstitutionKindList(rawInstitutionKindList)
	return nil
}

func (o InstitutionKindList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *InstitutionKindList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type InstitutionPage struct {
	Institutions  []Institution `json:"institutions"`
	NextPageToken *string       `json:"nextPageToken,omitempty"`
}

func (o InstitutionPage) MarshalJSON() ([]byte, error) {
	if o.Institutions == nil {
		o.Institutions = make([]Institution, 0)
	}
	type _tmpInstitutionPage InstitutionPage
	return safejson.Marshal(_tmpInstitutionPage(o))
}

func (o *InstitutionPage) UnmarshalJSON(data []byte) error {
	type _tmpInstitutionPage InstitutionPage
	var rawInstitutionPage _tmpInstitutionPage
	if err := safejson.Unmarshal(data, &rawInstitutionPage); err != nil {
		return err
	}
	if rawInstitutionPage.Institutions == nil {
		rawInstitutionPage.Institutions = make([]Institution, 0)
	}
	*o = InstitutionPage(rawInstitutionPage)
	return nil
}

func (o InstitutionPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *InstitutionPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// An appointment a person holds, enriched with the position's title and owning institution (read-only person view).
type PersonAppointment struct {
	Id              string             `json:"id"`
	PersonId        string             `json:"personId"`
	PositionId      string             `json:"positionId"`
	PositionTitle   string             `json:"positionTitle"`
	InstitutionId   string             `json:"institutionId"`
	InstitutionName string             `json:"institutionName"`
	Status          string             `json:"status"`
	EffectiveFrom   datetime.DateTime  `json:"effectiveFrom"`
	EffectiveTo     *datetime.DateTime `json:"effectiveTo,omitempty"`
	CreatedAt       datetime.DateTime  `json:"createdAt"`
	UpdatedAt       datetime.DateTime  `json:"updatedAt"`
}

func (o PersonAppointment) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *PersonAppointment) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type PersonAppointmentList struct {
	Appointments []PersonAppointment `json:"appointments"`
}

func (o PersonAppointmentList) MarshalJSON() ([]byte, error) {
	if o.Appointments == nil {
		o.Appointments = make([]PersonAppointment, 0)
	}
	type _tmpPersonAppointmentList PersonAppointmentList
	return safejson.Marshal(_tmpPersonAppointmentList(o))
}

func (o *PersonAppointmentList) UnmarshalJSON(data []byte) error {
	type _tmpPersonAppointmentList PersonAppointmentList
	var rawPersonAppointmentList _tmpPersonAppointmentList
	if err := safejson.Unmarshal(data, &rawPersonAppointmentList); err != nil {
		return err
	}
	if rawPersonAppointmentList.Appointments == nil {
		rawPersonAppointmentList.Appointments = make([]PersonAppointment, 0)
	}
	*o = PersonAppointmentList(rawPersonAppointmentList)
	return nil
}

func (o PersonAppointmentList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *PersonAppointmentList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type PositionPage struct {
	Positions     []EducationPosition `json:"positions"`
	NextPageToken *string             `json:"nextPageToken,omitempty"`
}

func (o PositionPage) MarshalJSON() ([]byte, error) {
	if o.Positions == nil {
		o.Positions = make([]EducationPosition, 0)
	}
	type _tmpPositionPage PositionPage
	return safejson.Marshal(_tmpPositionPage(o))
}

func (o *PositionPage) UnmarshalJSON(data []byte) error {
	type _tmpPositionPage PositionPage
	var rawPositionPage _tmpPositionPage
	if err := safejson.Unmarshal(data, &rawPositionPage); err != nil {
		return err
	}
	if rawPositionPage.Positions == nil {
		rawPositionPage.Positions = make([]EducationPosition, 0)
	}
	*o = PositionPage(rawPositionPage)
	return nil
}

func (o PositionPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *PositionPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Move a unit under a new parent (same institution), recomputing the closure. Cycle-guarded.
type ReparentUnitRequest struct {
	// The new parent unit; null makes the unit top-level.
	ParentId *string `json:"parentId,omitempty"`
}

func (o ReparentUnitRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ReparentUnitRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// An instance-admin catalog entry classifying a structure-tree node (faculty/department/…).
type UnitKind struct {
	Id        string            `json:"id"`
	Code      string            `json:"code"`
	Name      map[string]string `json:"name"`
	Status    string            `json:"status"`
	SortOrder *int              `json:"sortOrder,omitempty"`
}

func (o UnitKind) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpUnitKind UnitKind
	return safejson.Marshal(_tmpUnitKind(o))
}

func (o *UnitKind) UnmarshalJSON(data []byte) error {
	type _tmpUnitKind UnitKind
	var rawUnitKind _tmpUnitKind
	if err := safejson.Unmarshal(data, &rawUnitKind); err != nil {
		return err
	}
	if rawUnitKind.Name == nil {
		rawUnitKind.Name = make(map[string]string)
	}
	*o = UnitKind(rawUnitKind)
	return nil
}

func (o UnitKind) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UnitKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UnitKindList struct {
	UnitKinds []UnitKind `json:"unitKinds"`
}

func (o UnitKindList) MarshalJSON() ([]byte, error) {
	if o.UnitKinds == nil {
		o.UnitKinds = make([]UnitKind, 0)
	}
	type _tmpUnitKindList UnitKindList
	return safejson.Marshal(_tmpUnitKindList(o))
}

func (o *UnitKindList) UnmarshalJSON(data []byte) error {
	type _tmpUnitKindList UnitKindList
	var rawUnitKindList _tmpUnitKindList
	if err := safejson.Unmarshal(data, &rawUnitKindList); err != nil {
		return err
	}
	if rawUnitKindList.UnitKinds == nil {
		rawUnitKindList.UnitKinds = make([]UnitKind, 0)
	}
	*o = UnitKindList(rawUnitKindList)
	return nil
}

func (o UnitKindList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UnitKindList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpdateBuildingRequest struct {
	Name       *string `json:"name,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	UnitId     *string `json:"unitId,omitempty"`
	LocationId *string `json:"locationId,omitempty"`
}

func (o UpdateBuildingRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateBuildingRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpdateGroupRequest struct {
	Name          *string `json:"name,omitempty"`
	AdmissionYear *int    `json:"admissionYear,omitempty"`
	Status        *string `json:"status,omitempty"`
}

func (o UpdateGroupRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateGroupRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Update name/kind/country/dates/state. code is immutable; omitted fields are unchanged.
type UpdateInstitutionRequest struct {
	Name      *string `json:"name,omitempty"`
	KindId    *string `json:"kindId,omitempty"`
	CountryId *string `json:"countryId,omitempty"`
	FoundedOn *string `json:"foundedOn,omitempty"`
	ClosedOn  *string `json:"closedOn,omitempty"`
	State     *string `json:"state,omitempty"`
}

func (o UpdateInstitutionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateInstitutionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpdatePositionRequest struct {
	Title     *string `json:"title,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

func (o UpdatePositionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdatePositionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Update name/kind/sort order/status. code and institution are immutable.
type UpdateUnitRequest struct {
	Name      *string `json:"name,omitempty"`
	KindId    *string `json:"kindId,omitempty"`
	Status    *string `json:"status,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

func (o UpdateUnitRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateUnitRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Create/update an institution-kind or unit-kind. name is the default-locale fallback.
type UpsertCatalogKindRequest struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder *int   `json:"sortOrder,omitempty"`
}

func (o UpsertCatalogKindRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpsertCatalogKindRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpsertDormitoryStayRequest struct {
	BuildingId    string  `json:"buildingId"`
	Room          *string `json:"room,omitempty"`
	Status        *string `json:"status,omitempty"`
	EffectiveFrom *string `json:"effectiveFrom,omitempty"`
	EffectiveTo   *string `json:"effectiveTo,omitempty"`
}

func (o UpsertDormitoryStayRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpsertDormitoryStayRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Create or update a person's enrollment. On create, omit nothing required; on update, target by id.
type UpsertEnrollmentRequest struct {
	InstitutionId string  `json:"institutionId"`
	UnitId        *string `json:"unitId,omitempty"`
	GroupId       *string `json:"groupId,omitempty"`
	ProgramId     *string `json:"programId,omitempty"`
	DegreeLevelId *string `json:"degreeLevelId,omitempty"`
	FieldOfStudy  *string `json:"fieldOfStudy,omitempty"`
	StudentNumber *string `json:"studentNumber,omitempty"`
	Status        *string `json:"status,omitempty"`
	Qualification *string `json:"qualification,omitempty"`
	EffectiveFrom *string `json:"effectiveFrom,omitempty"`
	EffectiveTo   *string `json:"effectiveTo,omitempty"`
}

func (o UpsertEnrollmentRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpsertEnrollmentRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
