// Code generated by conjure-go. DO NOT EDIT.

package identityfederation

import (
	"github.com/palantir/pkg/datetime"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

/*
An optional login attachment to exactly one person (Object Account). A person may have zero
accounts (roster-only) or one active account. `identities` are the linked login points and is
populated by getAccount/createAccount; it is empty in contexts that do not load it.
*/
type Account struct {
	// The account's URN RID (carried as a plain string).
	Id string `json:"id"`
	// The URN RID of the person this account attaches to.
	PersonId string `json:"personId"`
	// The IdP-asserted email, if any; unique among active accounts when present.
	Email *string `json:"email,omitempty"`
	// One of active | disabled (disable is a reversible login block).
	Status string `json:"status"`
	// The external identities (login points) federated to this account.
	Identities []ExternalIdentity `json:"identities"`
	CreatedAt  datetime.DateTime  `json:"createdAt"`
	UpdatedAt  datetime.DateTime  `json:"updatedAt"`
}

func (o Account) MarshalJSON() ([]byte, error) {
	if o.Identities == nil {
		o.Identities = make([]ExternalIdentity, 0)
	}
	type _tmpAccount Account
	return safejson.Marshal(_tmpAccount(o))
}

func (o *Account) UnmarshalJSON(data []byte) error {
	type _tmpAccount Account
	var rawAccount _tmpAccount
	if err := safejson.Unmarshal(data, &rawAccount); err != nil {
		return err
	}
	if rawAccount.Identities == nil {
		rawAccount.Identities = make([]ExternalIdentity, 0)
	}
	*o = Account(rawAccount)
	return nil
}

func (o Account) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Account) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
Create an account for a person, optionally linking its first external identity in the same
operation. The first identity on a new account is always permitted (the linking cap applies
only to ADDITIONAL identities).
*/
type CreateAccountRequest struct {
	PersonId string `json:"personId"`
	// The IdP-asserted email, if known.
	Email *string `json:"email,omitempty"`
	// The first login point to link; omit to create a login-less account shell.
	Identity *LinkIdentityRequest `json:"identity,omitempty"`
}

func (o CreateAccountRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateAccountRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
A verified (issuer, subject) login point federating to one account (Object External
identity). Globally unique; immutable once created and removed by unlink. No token columns —
access/refresh tokens are never persisted.
*/
type ExternalIdentity struct {
	// The external identity's URN RID (carried as a plain string).
	Id string `json:"id"`
	// The URN RID of the account this identity federates to.
	AccountId string `json:"accountId"`
	// The IdP `iss` (an allowed issuer).
	Issuer string `json:"issuer"`
	// The IdP `sub` — a pseudonymous identifier for the person.
	Subject   string            `json:"subject"`
	CreatedAt datetime.DateTime `json:"createdAt"`
}

func (o ExternalIdentity) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ExternalIdentity) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
One IdP issuer accepted by this instance (from install config), offered to binding UIs so an
operator picks an issuer rather than typing it. PUBLIC fields only — verification secrets
(HS256 keys) are never exposed. An external identity's `issuer` must match one of these for a
token from it to ever validate.
*/
type IssuerOption struct {
	// The `iss` value (also the OIDC discovery base URL).
	Issuer string `json:"issuer"`
	// The expected `aud`, if the instance pins one.
	Audience *string `json:"audience,omitempty"`
	// One of oidc | hs256 (hs256 is local/dev only).
	Type string `json:"type"`
}

func (o IssuerOption) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *IssuerOption) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Link a verified (issuer, subject) login point to an account.
type LinkIdentityRequest struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (o LinkIdentityRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *LinkIdentityRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
One deduped login/IP occurrence for an account (M37 / D-LoginSecurityLog): first-party
security telemetry from the token-validation seam, `pii:contact`, retention-bounded. Repeat
occurrences from the same (context, ip) within the dedup window collapse into one row —
`occurrenceCount` + `lastSeenAt` carry the recency. The `resolved*` / `isVpn` / `isTor`
fields are the IP-intelligence overlay and stay absent until a resolver ships.
*/
type LoginEvent struct {
	Id        string `json:"id"`
	AccountId string `json:"accountId"`
	// One of login | activity | registration (registration = the JIT link-on-match).
	Context         string            `json:"context"`
	Ip              string            `json:"ip"`
	FirstSeenAt     datetime.DateTime `json:"firstSeenAt"`
	LastSeenAt      datetime.DateTime `json:"lastSeenAt"`
	OccurrenceCount int               `json:"occurrenceCount"`
	// ISO 3166-1 alpha-2 when resolved.
	ResolvedCountry *string `json:"resolvedCountry,omitempty"`
	ResolvedIsp     *string `json:"resolvedIsp,omitempty"`
	IsVpn           *bool   `json:"isVpn,omitempty"`
	IsTor           *bool   `json:"isTor,omitempty"`
	UserAgent       *string `json:"userAgent,omitempty"`
}

func (o LoginEvent) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *LoginEvent) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type LoginEventPage struct {
	Events        []LoginEvent `json:"events"`
	NextPageToken *string      `json:"nextPageToken,omitempty"`
}

func (o LoginEventPage) MarshalJSON() ([]byte, error) {
	if o.Events == nil {
		o.Events = make([]LoginEvent, 0)
	}
	type _tmpLoginEventPage LoginEventPage
	return safejson.Marshal(_tmpLoginEventPage(o))
}

func (o *LoginEventPage) UnmarshalJSON(data []byte) error {
	type _tmpLoginEventPage LoginEventPage
	var rawLoginEventPage _tmpLoginEventPage
	if err := safejson.Unmarshal(data, &rawLoginEventPage); err != nil {
		return err
	}
	if rawLoginEventPage.Events == nil {
		rawLoginEventPage.Events = make([]LoginEvent, 0)
	}
	*o = LoginEventPage(rawLoginEventPage)
	return nil
}

func (o LoginEventPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *LoginEventPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type RegisterServicePrincipalRequest struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// The IdP `iss` the machine's tokens carry.
	Issuer string `json:"issuer"`
	/*
	   The IdP `sub` the machine's tokens carry. For Keycloak this is the service-account user
	   id; a rejected unknown token logs its issuer/subject so it can be copied from there.
	*/
	Subject  string  `json:"subject"`
	ClientId *string `json:"clientId,omitempty"`
}

func (o RegisterServicePrincipalRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RegisterServicePrincipalRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
A MACHINE subject (M51 / D-ServiceIdentities) — a facade with standing of its own, or a
connector. It authenticates through the same external IdP and the same middleware as a
person, using the OAuth2 client-credentials grant, and is keyed by the same
(issuer, subject) pair as an ExternalIdentity: a given pair is a person identity XOR a
principal, never both.

A principal holds NO role assignment and NO unit reach; its authority is the flat
per-principal grants owned by AuthorizationService. Registering one creates no credential —
the IdP owns the client secret (L-AuthzOnly holds).
*/
type ServicePrincipal struct {
	// The principal's URN RID (carried as a plain string).
	Id string `json:"id"`
	// Stable, locale-agnostic machine name (D-Code) — what audit rows and operators reference.
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// The IdP `iss` of the client-credentials token.
	Issuer string `json:"issuer"`
	// The IdP `sub` of the client-credentials token. Immutable after registration.
	Subject string `json:"subject"`
	/*
	   Display label from the token's `azp`/`client_id` claim, so an operator can tell which IdP
	   client this is. NEVER an authorization input — the identity key is (issuer, subject).
	*/
	ClientId *string `json:"clientId,omitempty"`
	// One of active | disabled. A disabled principal fails resolution, so its tokens stop working at once.
	Status    string            `json:"status"`
	CreatedAt datetime.DateTime `json:"createdAt"`
	UpdatedAt datetime.DateTime `json:"updatedAt"`
}

func (o ServicePrincipal) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ServicePrincipal) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type ServicePrincipalPage struct {
	Principals    []ServicePrincipal `json:"principals"`
	NextPageToken *string            `json:"nextPageToken,omitempty"`
}

func (o ServicePrincipalPage) MarshalJSON() ([]byte, error) {
	if o.Principals == nil {
		o.Principals = make([]ServicePrincipal, 0)
	}
	type _tmpServicePrincipalPage ServicePrincipalPage
	return safejson.Marshal(_tmpServicePrincipalPage(o))
}

func (o *ServicePrincipalPage) UnmarshalJSON(data []byte) error {
	type _tmpServicePrincipalPage ServicePrincipalPage
	var rawServicePrincipalPage _tmpServicePrincipalPage
	if err := safejson.Unmarshal(data, &rawServicePrincipalPage); err != nil {
		return err
	}
	if rawServicePrincipalPage.Principals == nil {
		rawServicePrincipalPage.Principals = make([]ServicePrincipal, 0)
	}
	*o = ServicePrincipalPage(rawServicePrincipalPage)
	return nil
}

func (o ServicePrincipalPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ServicePrincipalPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
Mutable display fields only. (issuer, subject) is the identity key the middleware resolves
on and is immutable — re-pointing it would silently transfer a machine's authority to a
different IdP client. Register a new principal and disable the old one instead.
*/
type UpdateServicePrincipalRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ClientId    *string `json:"clientId,omitempty"`
}

func (o UpdateServicePrincipalRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateServicePrincipalRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
The caller's own resolved PDP context — the person (and optional account) the inbound token
mapped to. Produced from the request context the validation middleware attached.
*/
type Whoami struct {
	// The URN RID of the resolved person (the PDP subject).
	PersonId string `json:"personId"`
	// The URN RID of the resolved account; absent only on out-of-band/system contexts.
	AccountId *string `json:"accountId,omitempty"`
	// The account's IdP-asserted email, if any.
	Email *string `json:"email,omitempty"`
}

func (o Whoami) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Whoami) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
