// Code generated by conjure-go. DO NOT EDIT.

package dataimport

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/olegamysk/go-oikumenea/clients/go/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	werror "github.com/palantir/witchcraft-go-error"
)

type envelopeMismatch struct {
	PathObjectType string `json:"pathObjectType"`
	BodyObjectType string `json:"bodyObjectType"`
}

func (o envelopeMismatch) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *envelopeMismatch) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewEnvelopeMismatch returns new instance of EnvelopeMismatch error.
func NewEnvelopeMismatch(pathObjectTypeArg string, bodyObjectTypeArg string) *EnvelopeMismatch {
	return &EnvelopeMismatch{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), envelopeMismatch: envelopeMismatch{PathObjectType: pathObjectTypeArg, BodyObjectType: bodyObjectTypeArg}}
}

// WrapWithEnvelopeMismatch returns new instance of EnvelopeMismatch error wrapping an existing error.
func WrapWithEnvelopeMismatch(err error, pathObjectTypeArg string, bodyObjectTypeArg string) *EnvelopeMismatch {
	return &EnvelopeMismatch{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, envelopeMismatch: envelopeMismatch{PathObjectType: pathObjectTypeArg, BodyObjectType: bodyObjectTypeArg}}
}

// EnvelopeMismatch is an error type.
// The envelope's objectType does not match the path object-type.
type EnvelopeMismatch struct {
	errorInstanceID uuid.UUID
	envelopeMismatch
	cause error
	stack werror.StackTrace
}

// IsEnvelopeMismatch returns true if err is an instance of EnvelopeMismatch.
func IsEnvelopeMismatch(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*EnvelopeMismatch)
	return ok
}

func (e *EnvelopeMismatch) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT DataImport:EnvelopeMismatch (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *EnvelopeMismatch) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *EnvelopeMismatch) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *EnvelopeMismatch) Message() string {
	return "INVALID_ARGUMENT DataImport:EnvelopeMismatch"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *EnvelopeMismatch) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *EnvelopeMismatch) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *EnvelopeMismatch) Name() string {
	return "DataImport:EnvelopeMismatch"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *EnvelopeMismatch) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *EnvelopeMismatch) Parameters() map[string]interface{} {
	return map[string]interface{}{"pathObjectType": e.PathObjectType, "bodyObjectType": e.BodyObjectType}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *EnvelopeMismatch) safeParams() map[string]interface{} {
	return map[string]interface{}{"pathObjectType": e.PathObjectType, "bodyObjectType": e.BodyObjectType, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *EnvelopeMismatch) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *EnvelopeMismatch) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *EnvelopeMismatch) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e EnvelopeMismatch) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.envelopeMismatch)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "DataImport:EnvelopeMismatch", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *EnvelopeMismatch) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters envelopeMismatch
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.envelopeMismatch = parameters
	return nil
}

type unknownObjectType struct {
	ObjectType string `json:"objectType"`
}

func (o unknownObjectType) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *unknownObjectType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewUnknownObjectType returns new instance of UnknownObjectType error.
func NewUnknownObjectType(objectTypeArg string) *UnknownObjectType {
	return &UnknownObjectType{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), unknownObjectType: unknownObjectType{ObjectType: objectTypeArg}}
}

// WrapWithUnknownObjectType returns new instance of UnknownObjectType error wrapping an existing error.
func WrapWithUnknownObjectType(err error, objectTypeArg string) *UnknownObjectType {
	return &UnknownObjectType{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, unknownObjectType: unknownObjectType{ObjectType: objectTypeArg}}
}

// UnknownObjectType is an error type.
// No upsert handler is registered for the requested object-type.
type UnknownObjectType struct {
	errorInstanceID uuid.UUID
	unknownObjectType
	cause error
	stack werror.StackTrace
}

// IsUnknownObjectType returns true if err is an instance of UnknownObjectType.
func IsUnknownObjectType(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*UnknownObjectType)
	return ok
}

func (e *UnknownObjectType) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT DataImport:UnknownObjectType (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *UnknownObjectType) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *UnknownObjectType) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *UnknownObjectType) Message() string {
	return "INVALID_ARGUMENT DataImport:UnknownObjectType"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *UnknownObjectType) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *UnknownObjectType) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *UnknownObjectType) Name() string {
	return "DataImport:UnknownObjectType"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *UnknownObjectType) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *UnknownObjectType) Parameters() map[string]interface{} {
	return map[string]interface{}{"objectType": e.ObjectType}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *UnknownObjectType) safeParams() map[string]interface{} {
	return map[string]interface{}{"objectType": e.ObjectType, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *UnknownObjectType) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *UnknownObjectType) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *UnknownObjectType) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e UnknownObjectType) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.unknownObjectType)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "DataImport:UnknownObjectType", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *UnknownObjectType) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters unknownObjectType
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.unknownObjectType = parameters
	return nil
}

func init() {
	conjureerrors.RegisterErrorType("DataImport:EnvelopeMismatch", reflect.TypeOf(EnvelopeMismatch{}))
	conjureerrors.RegisterErrorType("DataImport:UnknownObjectType", reflect.TypeOf(UnknownObjectType{}))
}
