// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: education.sql

package educationsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abolishPosition = `-- name: AbolishPosition :one
UPDATE oikumenea.education_positions SET status = 'abolished'
WHERE id = $1 AND status = 'active' AND deleted_at IS NULL
RETURNING id, institution_id, unit_id, code, title, status, sort_order, created_at, updated_at, deleted_at
`

func (q *Queries) AbolishPosition(ctx context.Context, id string) (OikumeneaEducationPosition, error) {
	row := q.db.QueryRow(ctx, abolishPosition, id)
	var i OikumeneaEducationPosition
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.UnitID,
		&i.Code,
		&i.Title,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const endAppointment = `-- name: EndAppointment :one
UPDATE oikumenea.education_appointments
SET status = 'ended', effective_to = COALESCE($1::timestamptz, now())
WHERE id = $2 AND status = 'active' AND deleted_at IS NULL
RETURNING id, person_id, position_id, status, effective_from, effective_to, created_at, updated_at, deleted_at
`

type EndAppointmentParams struct {
	EffectiveTo pgtype.Timestamptz
	ID          string
}

func (q *Queries) EndAppointment(ctx context.Context, arg EndAppointmentParams) (OikumeneaEducationAppointment, error) {
	row := q.db.QueryRow(ctx, endAppointment, arg.EffectiveTo, arg.ID)
	var i OikumeneaEducationAppointment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.PositionID,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveAppointmentByPosition = `-- name: GetActiveAppointmentByPosition :one
SELECT id, person_id, position_id, status, effective_from, effective_to, created_at, updated_at, deleted_at FROM oikumenea.education_appointments
WHERE position_id = $1 AND status = 'active' AND deleted_at IS NULL
`

func (q *Queries) GetActiveAppointmentByPosition(ctx context.Context, positionID string) (OikumeneaEducationAppointment, error) {
	row := q.db.QueryRow(ctx, getActiveAppointmentByPosition, positionID)
	var i OikumeneaEducationAppointment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.PositionID,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, person_id, position_id, status, effective_from, effective_to, created_at, updated_at, deleted_at FROM oikumenea.education_appointments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppointment(ctx context.Context, id string) (OikumeneaEducationAppointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i OikumeneaEducationAppointment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.PositionID,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBuilding = `-- name: GetBuilding :one
SELECT id, institution_id, unit_id, location_id, code, name, kind, created_at, updated_at, deleted_at FROM oikumenea.education_buildings WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBuilding(ctx context.Context, id string) (OikumeneaEducationBuilding, error) {
	row := q.db.QueryRow(ctx, getBuilding, id)
	var i OikumeneaEducationBuilding
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.UnitID,
		&i.LocationID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDormitoryStay = `-- name: GetDormitoryStay :one
SELECT id, person_id, building_id, room, status, effective_from, effective_to, created_at, updated_at, deleted_at FROM oikumenea.person_dormitory_stays
WHERE id = $1 AND person_id = $2 AND deleted_at IS NULL
`

type GetDormitoryStayParams struct {
	ID       string
	PersonID string
}

func (q *Queries) GetDormitoryStay(ctx context.Context, arg GetDormitoryStayParams) (OikumeneaPersonDormitoryStay, error) {
	row := q.db.QueryRow(ctx, getDormitoryStay, arg.ID, arg.PersonID)
	var i OikumeneaPersonDormitoryStay
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BuildingID,
		&i.Room,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, person_id, institution_id, unit_id, group_id, degree_level_id, field_of_study, status, qualification, effective_from, effective_to, created_at, updated_at, deleted_at, program_id, student_number FROM oikumenea.person_education_enrollments
WHERE id = $1 AND person_id = $2 AND deleted_at IS NULL
`

type GetEnrollmentParams struct {
	ID       string
	PersonID string
}

func (q *Queries) GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (OikumeneaPersonEducationEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, arg.ID, arg.PersonID)
	var i OikumeneaPersonEducationEnrollment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.InstitutionID,
		&i.UnitID,
		&i.GroupID,
		&i.DegreeLevelID,
		&i.FieldOfStudy,
		&i.Status,
		&i.Qualification,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProgramID,
		&i.StudentNumber,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, unit_id, code, name, admission_year, status, created_at, updated_at, deleted_at FROM oikumenea.education_groups WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGroup(ctx context.Context, id string) (OikumeneaEducationGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i OikumeneaEducationGroup
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Code,
		&i.Name,
		&i.AdmissionYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstitution = `-- name: GetInstitution :one
SELECT o.id, o.code, o.name,
  p.kind_id, p.country_id, p.founded_on, p.closed_on, p.state, p.created_at, p.updated_at
FROM oikumenea.education_org_profiles p
JOIN oikumenea.tenant_organizations o ON o.id = p.institution_id AND o.deleted_at IS NULL
WHERE p.institution_id = $1 AND p.deleted_at IS NULL
`

type GetInstitutionRow struct {
	ID        string
	Code      string
	Name      string
	KindID    string
	CountryID pgtype.Text
	FoundedOn pgtype.Date
	ClosedOn  pgtype.Date
	State     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetInstitution(ctx context.Context, id string) (GetInstitutionRow, error) {
	row := q.db.QueryRow(ctx, getInstitution, id)
	var i GetInstitutionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.KindID,
		&i.CountryID,
		&i.FoundedOn,
		&i.ClosedOn,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT id, institution_id, unit_id, code, title, status, sort_order, created_at, updated_at, deleted_at FROM oikumenea.education_positions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPosition(ctx context.Context, id string) (OikumeneaEducationPosition, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var i OikumeneaEducationPosition
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.UnitID,
		&i.Code,
		&i.Title,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAppointment = `-- name: InsertAppointment :one

INSERT INTO oikumenea.education_appointments (person_id, position_id, effective_from)
VALUES ($1, $2, COALESCE($3::timestamptz, now()))
RETURNING id, person_id, position_id, status, effective_from, effective_to, created_at, updated_at, deleted_at
`

type InsertAppointmentParams struct {
	PersonID      string
	PositionID    string
	EffectiveFrom pgtype.Timestamptz
}

// ============================ appointments ============================
func (q *Queries) InsertAppointment(ctx context.Context, arg InsertAppointmentParams) (OikumeneaEducationAppointment, error) {
	row := q.db.QueryRow(ctx, insertAppointment, arg.PersonID, arg.PositionID, arg.EffectiveFrom)
	var i OikumeneaEducationAppointment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.PositionID,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertBuilding = `-- name: InsertBuilding :one

INSERT INTO oikumenea.education_buildings (institution_id, unit_id, location_id, code, name, kind)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, institution_id, unit_id, location_id, code, name, kind, created_at, updated_at, deleted_at
`

type InsertBuildingParams struct {
	InstitutionID string
	UnitID        pgtype.Text
	LocationID    pgtype.Text
	Code          string
	Name          string
	Kind          string
}

// ============================ buildings ============================
func (q *Queries) InsertBuilding(ctx context.Context, arg InsertBuildingParams) (OikumeneaEducationBuilding, error) {
	row := q.db.QueryRow(ctx, insertBuilding,
		arg.InstitutionID,
		arg.UnitID,
		arg.LocationID,
		arg.Code,
		arg.Name,
		arg.Kind,
	)
	var i OikumeneaEducationBuilding
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.UnitID,
		&i.LocationID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertDormitoryStay = `-- name: InsertDormitoryStay :one
INSERT INTO oikumenea.person_dormitory_stays (person_id, building_id, room, status, effective_from, effective_to)
VALUES ($1, $2, $3, COALESCE($4, 'active'),
        $5, $6)
RETURNING id, person_id, building_id, room, status, effective_from, effective_to, created_at, updated_at, deleted_at
`

type InsertDormitoryStayParams struct {
	PersonID      string
	BuildingID    string
	Room          pgtype.Text
	Status        interface{}
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
}

func (q *Queries) InsertDormitoryStay(ctx context.Context, arg InsertDormitoryStayParams) (OikumeneaPersonDormitoryStay, error) {
	row := q.db.QueryRow(ctx, insertDormitoryStay,
		arg.PersonID,
		arg.BuildingID,
		arg.Room,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i OikumeneaPersonDormitoryStay
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BuildingID,
		&i.Room,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertEnrollment = `-- name: InsertEnrollment :one

INSERT INTO oikumenea.person_education_enrollments
  (person_id, institution_id, unit_id, group_id, program_id, degree_level_id, field_of_study, student_number, status, qualification, effective_from, effective_to)
VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, COALESCE($9, 'enrolled'), $10,
  $11, $12
)
RETURNING id, person_id, institution_id, unit_id, group_id, degree_level_id, field_of_study, status, qualification, effective_from, effective_to, created_at, updated_at, deleted_at, program_id, student_number
`

type InsertEnrollmentParams struct {
	PersonID      string
	InstitutionID string
	UnitID        pgtype.Text
	GroupID       pgtype.Text
	ProgramID     pgtype.Text
	DegreeLevelID pgtype.Text
	FieldOfStudy  pgtype.Text
	StudentNumber pgtype.Text
	Status        interface{}
	Qualification pgtype.Text
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
}

// ============================ person bindings ============================
func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (OikumeneaPersonEducationEnrollment, error) {
	row := q.db.QueryRow(ctx, insertEnrollment,
		arg.PersonID,
		arg.InstitutionID,
		arg.UnitID,
		arg.GroupID,
		arg.ProgramID,
		arg.DegreeLevelID,
		arg.FieldOfStudy,
		arg.StudentNumber,
		arg.Status,
		arg.Qualification,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i OikumeneaPersonEducationEnrollment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.InstitutionID,
		&i.UnitID,
		&i.GroupID,
		&i.DegreeLevelID,
		&i.FieldOfStudy,
		&i.Status,
		&i.Qualification,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProgramID,
		&i.StudentNumber,
	)
	return i, err
}

const insertGroup = `-- name: InsertGroup :one

INSERT INTO oikumenea.education_groups (unit_id, code, name, admission_year)
VALUES ($1, $2, $3, $4)
RETURNING id, unit_id, code, name, admission_year, status, created_at, updated_at, deleted_at
`

type InsertGroupParams struct {
	UnitID        string
	Code          string
	Name          string
	AdmissionYear pgtype.Int4
}

// ============================ groups ============================
func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (OikumeneaEducationGroup, error) {
	row := q.db.QueryRow(ctx, insertGroup,
		arg.UnitID,
		arg.Code,
		arg.Name,
		arg.AdmissionYear,
	)
	var i OikumeneaEducationGroup
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Code,
		&i.Name,
		&i.AdmissionYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertOrgProfile = `-- name: InsertOrgProfile :one

INSERT INTO oikumenea.education_org_profiles (institution_id, kind_id, country_id, founded_on, closed_on)
VALUES ($1, $2, $3, $4, $5)
RETURNING institution_id, kind_id, country_id, founded_on, closed_on, state, created_at, updated_at, deleted_at
`

type InsertOrgProfileParams struct {
	InstitutionID string
	KindID        string
	CountryID     pgtype.Text
	FoundedOn     pgtype.Date
	ClosedOn      pgtype.Date
}

// ============================ institutions (tenant org + education_org_profiles sidecar — M41) ============================
// An institution is a `university`-domain tenant organization (code/name/visibility) plus an
// education_org_profiles sidecar (kind/country/dates/state). The org itself is created/updated through
// the tenant service; these queries own the sidecar and the joined read view.
func (q *Queries) InsertOrgProfile(ctx context.Context, arg InsertOrgProfileParams) (OikumeneaEducationOrgProfile, error) {
	row := q.db.QueryRow(ctx, insertOrgProfile,
		arg.InstitutionID,
		arg.KindID,
		arg.CountryID,
		arg.FoundedOn,
		arg.ClosedOn,
	)
	var i OikumeneaEducationOrgProfile
	err := row.Scan(
		&i.InstitutionID,
		&i.KindID,
		&i.CountryID,
		&i.FoundedOn,
		&i.ClosedOn,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPosition = `-- name: InsertPosition :one

INSERT INTO oikumenea.education_positions (institution_id, unit_id, code, title, sort_order)
VALUES (
  $1, $2, $3, $4,
  COALESCE($5, (
    SELECT COALESCE(MAX(sort_order), 0) + 1 FROM oikumenea.education_positions
    WHERE institution_id = $1 AND status = 'active' AND deleted_at IS NULL
  ))
)
RETURNING id, institution_id, unit_id, code, title, status, sort_order, created_at, updated_at, deleted_at
`

type InsertPositionParams struct {
	InstitutionID string
	UnitID        pgtype.Text
	Code          string
	Title         string
	SortOrder     interface{}
}

// ============================ positions ============================
func (q *Queries) InsertPosition(ctx context.Context, arg InsertPositionParams) (OikumeneaEducationPosition, error) {
	row := q.db.QueryRow(ctx, insertPosition,
		arg.InstitutionID,
		arg.UnitID,
		arg.Code,
		arg.Title,
		arg.SortOrder,
	)
	var i OikumeneaEducationPosition
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.UnitID,
		&i.Code,
		&i.Title,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAppointmentsByPerson = `-- name: ListAppointmentsByPerson :many
SELECT a.id, a.person_id, a.position_id, a.status, a.effective_from, a.effective_to, a.created_at, a.updated_at, a.deleted_at, p.title AS position_title, p.institution_id AS institution_id, i.name AS institution_name
FROM oikumenea.education_appointments a
JOIN oikumenea.education_positions p ON p.id = a.position_id
JOIN oikumenea.tenant_organizations i ON i.id = p.institution_id
WHERE a.person_id = $1 AND a.deleted_at IS NULL
ORDER BY a.status, a.effective_from DESC NULLS LAST, a.id
`

type ListAppointmentsByPersonRow struct {
	ID              string
	PersonID        string
	PositionID      string
	Status          string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveTo     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	PositionTitle   string
	InstitutionID   string
	InstitutionName string
}

func (q *Queries) ListAppointmentsByPerson(ctx context.Context, personID string) ([]ListAppointmentsByPersonRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsByPersonRow
	for rows.Next() {
		var i ListAppointmentsByPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.PositionID,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PositionTitle,
			&i.InstitutionID,
			&i.InstitutionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildingsByInstitution = `-- name: ListBuildingsByInstitution :many
SELECT id, institution_id, unit_id, location_id, code, name, kind, created_at, updated_at, deleted_at FROM oikumenea.education_buildings
WHERE institution_id = $1 AND deleted_at IS NULL
ORDER BY code
`

func (q *Queries) ListBuildingsByInstitution(ctx context.Context, institutionID string) ([]OikumeneaEducationBuilding, error) {
	rows, err := q.db.Query(ctx, listBuildingsByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaEducationBuilding
	for rows.Next() {
		var i OikumeneaEducationBuilding
		if err := rows.Scan(
			&i.ID,
			&i.InstitutionID,
			&i.UnitID,
			&i.LocationID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDegreeLevels = `-- name: ListDegreeLevels :many
SELECT id, code, name, isced_level, status, sort_order, created_at, updated_at, deleted_at FROM oikumenea.education_degree_levels
WHERE deleted_at IS NULL ORDER BY isced_level
`

func (q *Queries) ListDegreeLevels(ctx context.Context) ([]OikumeneaEducationDegreeLevel, error) {
	rows, err := q.db.Query(ctx, listDegreeLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaEducationDegreeLevel
	for rows.Next() {
		var i OikumeneaEducationDegreeLevel
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IscedLevel,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDormitoryStaysByPerson = `-- name: ListDormitoryStaysByPerson :many
SELECT id, person_id, building_id, room, status, effective_from, effective_to, created_at, updated_at, deleted_at FROM oikumenea.person_dormitory_stays
WHERE person_id = $1 AND deleted_at IS NULL
ORDER BY effective_from DESC NULLS LAST, id
`

func (q *Queries) ListDormitoryStaysByPerson(ctx context.Context, personID string) ([]OikumeneaPersonDormitoryStay, error) {
	rows, err := q.db.Query(ctx, listDormitoryStaysByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaPersonDormitoryStay
	for rows.Next() {
		var i OikumeneaPersonDormitoryStay
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.BuildingID,
			&i.Room,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsByPerson = `-- name: ListEnrollmentsByPerson :many
SELECT id, person_id, institution_id, unit_id, group_id, degree_level_id, field_of_study, status, qualification, effective_from, effective_to, created_at, updated_at, deleted_at, program_id, student_number FROM oikumenea.person_education_enrollments
WHERE person_id = $1 AND deleted_at IS NULL
ORDER BY effective_from DESC NULLS LAST, id
`

func (q *Queries) ListEnrollmentsByPerson(ctx context.Context, personID string) ([]OikumeneaPersonEducationEnrollment, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaPersonEducationEnrollment
	for rows.Next() {
		var i OikumeneaPersonEducationEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.InstitutionID,
			&i.UnitID,
			&i.GroupID,
			&i.DegreeLevelID,
			&i.FieldOfStudy,
			&i.Status,
			&i.Qualification,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProgramID,
			&i.StudentNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilledPositionsByInstitution = `-- name: ListFilledPositionsByInstitution :many
SELECT p.id, p.institution_id, p.unit_id, p.code, p.title, p.status, p.sort_order, p.created_at, p.updated_at, p.deleted_at FROM oikumenea.education_positions p
WHERE p.institution_id = $1 AND p.status = 'active' AND p.deleted_at IS NULL
  AND EXISTS (
    SELECT 1 FROM oikumenea.education_appointments a
    WHERE a.position_id = p.id AND a.status = 'active' AND a.deleted_at IS NULL
  )
  AND ($2 = '' OR p.id::text > $2)
ORDER BY p.id
LIMIT $3
`

type ListFilledPositionsByInstitutionParams struct {
	InstitutionID string
	After         interface{}
	Lim           int32
}

func (q *Queries) ListFilledPositionsByInstitution(ctx context.Context, arg ListFilledPositionsByInstitutionParams) ([]OikumeneaEducationPosition, error) {
	rows, err := q.db.Query(ctx, listFilledPositionsByInstitution, arg.InstitutionID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaEducationPosition
	for rows.Next() {
		var i OikumeneaEducationPosition
		if err := rows.Scan(
			&i.ID,
			&i.InstitutionID,
			&i.UnitID,
			&i.Code,
			&i.Title,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByUnit = `-- name: ListGroupsByUnit :many
SELECT id, unit_id, code, name, admission_year, status, created_at, updated_at, deleted_at FROM oikumenea.education_groups
WHERE unit_id = $1 AND deleted_at IS NULL
ORDER BY code
`

func (q *Queries) ListGroupsByUnit(ctx context.Context, unitID string) ([]OikumeneaEducationGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaEducationGroup
	for rows.Next() {
		var i OikumeneaEducationGroup
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Code,
			&i.Name,
			&i.AdmissionYear,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstitutionKinds = `-- name: ListInstitutionKinds :many


SELECT id, code, name, status, sort_order, created_at, updated_at, deleted_at FROM oikumenea.education_institution_kinds
WHERE deleted_at IS NULL ORDER BY sort_order, code
`

// Education module queries (docs/modules/education.md / D-Education). External reference institutions,
// their recursive structure tree (+ a maintained transitive closure), buildings, groups, the
// positions/appointments (mirrors membership), and the person bindings (enrollments, dorm stays). RID
// PKs default at the database. Soft-delete + reversible status flips throughout; a NULL narg leaves the
// stored value unchanged on update (COALESCE). FKs validate referenced entities (mapped in the adapter).
// ============================ catalogs ============================
func (q *Queries) ListInstitutionKinds(ctx context.Context) ([]OikumeneaEducationInstitutionKind, error) {
	rows, err := q.db.Query(ctx, listInstitutionKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaEducationInstitutionKind
	for rows.Next() {
		var i OikumeneaEducationInstitutionKind
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT o.id, o.code, o.name,
  p.kind_id, p.country_id, p.founded_on, p.closed_on, p.state, p.created_at, p.updated_at
FROM oikumenea.education_org_profiles p
JOIN oikumenea.tenant_organizations o ON o.id = p.institution_id AND o.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND ($1 = '' OR o.id::text > $1)
ORDER BY o.id
LIMIT $2
`

type ListInstitutionsParams struct {
	After interface{}
	Lim   int32
}

type ListInstitutionsRow struct {
	ID        string
	Code      string
	Name      string
	KindID    string
	CountryID pgtype.Text
	FoundedOn pgtype.Date
	ClosedOn  pgtype.Date
	State     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Active institutions (orgs with an education profile), keyset-paginated by org RID. A text query routes
// to SearchInstitutions instead (review R-21): a `(@query = ” OR …)` guard would defeat the trigram GIN.
func (q *Queries) ListInstitutions(ctx context.Context, arg ListInstitutionsParams) ([]ListInstitutionsRow, error) {
	rows, err := q.db.Query(ctx, listInstitutions, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstitutionsRow
	for rows.Next() {
		var i ListInstitutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.KindID,
			&i.CountryID,
			&i.FoundedOn,
			&i.ClosedOn,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByInstitution = `-- name: ListPositionsByInstitution :many
SELECT id, institution_id, unit_id, code, title, status, sort_order, created_at, updated_at, deleted_at FROM oikumenea.education_positions
WHERE institution_id = $1 AND status = 'active' AND deleted_at IS NULL
  AND ($2 = '' OR id::text > $2)
ORDER BY id
LIMIT $3
`

type ListPositionsByInstitutionParams struct {
	InstitutionID string
	After         interface{}
	Lim           int32
}

func (q *Queries) ListPositionsByInstitution(ctx context.Context, arg ListPositionsByInstitutionParams) ([]OikumeneaEducationPosition, error) {
	rows, err := q.db.Query(ctx, listPositionsByInstitution, arg.InstitutionID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaEducationPosition
	for rows.Next() {
		var i OikumeneaEducationPosition
		if err := rows.Scan(
			&i.ID,
			&i.InstitutionID,
			&i.UnitID,
			&i.Code,
			&i.Title,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacantPositionsByInstitution = `-- name: ListVacantPositionsByInstitution :many
SELECT p.id, p.institution_id, p.unit_id, p.code, p.title, p.status, p.sort_order, p.created_at, p.updated_at, p.deleted_at FROM oikumenea.education_positions p
WHERE p.institution_id = $1 AND p.status = 'active' AND p.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM oikumenea.education_appointments a
    WHERE a.position_id = p.id AND a.status = 'active' AND a.deleted_at IS NULL
  )
  AND ($2 = '' OR p.id::text > $2)
ORDER BY p.id
LIMIT $3
`

type ListVacantPositionsByInstitutionParams struct {
	InstitutionID string
	After         interface{}
	Lim           int32
}

func (q *Queries) ListVacantPositionsByInstitution(ctx context.Context, arg ListVacantPositionsByInstitutionParams) ([]OikumeneaEducationPosition, error) {
	rows, err := q.db.Query(ctx, listVacantPositionsByInstitution, arg.InstitutionID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaEducationPosition
	for rows.Next() {
		var i OikumeneaEducationPosition
		if err := rows.Scan(
			&i.ID,
			&i.InstitutionID,
			&i.UnitID,
			&i.Code,
			&i.Title,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchInstitutions = `-- name: SearchInstitutions :many
SELECT o.id, o.code, o.name,
  p.kind_id, p.country_id, p.founded_on, p.closed_on, p.state, p.created_at, p.updated_at
FROM oikumenea.education_org_profiles p
JOIN oikumenea.tenant_organizations o ON o.id = p.institution_id AND o.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND o.search_text ILIKE '%' || $1 || '%'
  AND ($2 = '' OR o.id::text > $2)
ORDER BY o.id
LIMIT $3
`

type SearchInstitutionsParams struct {
	Query pgtype.Text
	After interface{}
	Lim   int32
}

type SearchInstitutionsRow struct {
	ID        string
	Code      string
	Name      string
	KindID    string
	CountryID pgtype.Text
	FoundedOn pgtype.Date
	ClosedOn  pgtype.Date
	State     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// The trigram-served twin of ListInstitutions (review R-21): an unconditional case-insensitive match over
// the tenant_organizations STORED search_text haystack, served by the tenant_organizations_search_trgm
// GIN. Same projection and keyset as ListInstitutions so the two rows are convertible in the repository.
func (q *Queries) SearchInstitutions(ctx context.Context, arg SearchInstitutionsParams) ([]SearchInstitutionsRow, error) {
	rows, err := q.db.Query(ctx, searchInstitutions, arg.Query, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchInstitutionsRow
	for rows.Next() {
		var i SearchInstitutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.KindID,
			&i.CountryID,
			&i.FoundedOn,
			&i.ClosedOn,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBuilding = `-- name: SoftDeleteBuilding :execrows
UPDATE oikumenea.education_buildings SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBuilding(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteBuilding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDormitoryStay = `-- name: SoftDeleteDormitoryStay :execrows
UPDATE oikumenea.person_dormitory_stays SET deleted_at = now()
WHERE id = $1 AND person_id = $2 AND deleted_at IS NULL
`

type SoftDeleteDormitoryStayParams struct {
	ID       string
	PersonID string
}

func (q *Queries) SoftDeleteDormitoryStay(ctx context.Context, arg SoftDeleteDormitoryStayParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDormitoryStay, arg.ID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteEnrollment = `-- name: SoftDeleteEnrollment :execrows
UPDATE oikumenea.person_education_enrollments SET deleted_at = now()
WHERE id = $1 AND person_id = $2 AND deleted_at IS NULL
`

type SoftDeleteEnrollmentParams struct {
	ID       string
	PersonID string
}

func (q *Queries) SoftDeleteEnrollment(ctx context.Context, arg SoftDeleteEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEnrollment, arg.ID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteGroup = `-- name: SoftDeleteGroup :execrows
UPDATE oikumenea.education_groups SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteInstitution = `-- name: SoftDeleteInstitution :execrows
UPDATE oikumenea.education_org_profiles SET deleted_at = now()
WHERE institution_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteInstitution(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInstitution, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBuilding = `-- name: UpdateBuilding :one
UPDATE oikumenea.education_buildings SET
  name        = COALESCE($1, name),
  kind        = COALESCE($2, kind),
  unit_id     = COALESCE($3, unit_id),
  location_id = COALESCE($4, location_id)
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, institution_id, unit_id, location_id, code, name, kind, created_at, updated_at, deleted_at
`

type UpdateBuildingParams struct {
	Name       pgtype.Text
	Kind       pgtype.Text
	UnitID     pgtype.Text
	LocationID pgtype.Text
	ID         string
}

func (q *Queries) UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) (OikumeneaEducationBuilding, error) {
	row := q.db.QueryRow(ctx, updateBuilding,
		arg.Name,
		arg.Kind,
		arg.UnitID,
		arg.LocationID,
		arg.ID,
	)
	var i OikumeneaEducationBuilding
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.UnitID,
		&i.LocationID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDormitoryStay = `-- name: UpdateDormitoryStay :one
UPDATE oikumenea.person_dormitory_stays SET
  building_id    = COALESCE($1, building_id),
  room           = COALESCE($2, room),
  status         = COALESCE($3, status),
  effective_from = COALESCE($4, effective_from),
  effective_to   = COALESCE($5, effective_to)
WHERE id = $6 AND person_id = $7 AND deleted_at IS NULL
RETURNING id, person_id, building_id, room, status, effective_from, effective_to, created_at, updated_at, deleted_at
`

type UpdateDormitoryStayParams struct {
	BuildingID    pgtype.Text
	Room          pgtype.Text
	Status        pgtype.Text
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	ID            string
	PersonID      string
}

func (q *Queries) UpdateDormitoryStay(ctx context.Context, arg UpdateDormitoryStayParams) (OikumeneaPersonDormitoryStay, error) {
	row := q.db.QueryRow(ctx, updateDormitoryStay,
		arg.BuildingID,
		arg.Room,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.ID,
		arg.PersonID,
	)
	var i OikumeneaPersonDormitoryStay
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BuildingID,
		&i.Room,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEnrollment = `-- name: UpdateEnrollment :one
UPDATE oikumenea.person_education_enrollments SET
  institution_id  = COALESCE($1, institution_id),
  unit_id         = COALESCE($2, unit_id),
  group_id        = COALESCE($3, group_id),
  program_id      = COALESCE($4, program_id),
  degree_level_id = COALESCE($5, degree_level_id),
  field_of_study  = COALESCE($6, field_of_study),
  student_number  = COALESCE($7, student_number),
  status          = COALESCE($8, status),
  qualification   = COALESCE($9, qualification),
  effective_from  = COALESCE($10, effective_from),
  effective_to    = COALESCE($11, effective_to)
WHERE id = $12 AND person_id = $13 AND deleted_at IS NULL
RETURNING id, person_id, institution_id, unit_id, group_id, degree_level_id, field_of_study, status, qualification, effective_from, effective_to, created_at, updated_at, deleted_at, program_id, student_number
`

type UpdateEnrollmentParams struct {
	InstitutionID pgtype.Text
	UnitID        pgtype.Text
	GroupID       pgtype.Text
	ProgramID     pgtype.Text
	DegreeLevelID pgtype.Text
	FieldOfStudy  pgtype.Text
	StudentNumber pgtype.Text
	Status        pgtype.Text
	Qualification pgtype.Text
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	ID            string
	PersonID      string
}

func (q *Queries) UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (OikumeneaPersonEducationEnrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollment,
		arg.InstitutionID,
		arg.UnitID,
		arg.GroupID,
		arg.ProgramID,
		arg.DegreeLevelID,
		arg.FieldOfStudy,
		arg.StudentNumber,
		arg.Status,
		arg.Qualification,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.ID,
		arg.PersonID,
	)
	var i OikumeneaPersonEducationEnrollment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.InstitutionID,
		&i.UnitID,
		&i.GroupID,
		&i.DegreeLevelID,
		&i.FieldOfStudy,
		&i.Status,
		&i.Qualification,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProgramID,
		&i.StudentNumber,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE oikumenea.education_groups SET
  name           = COALESCE($1, name),
  admission_year = COALESCE($2, admission_year),
  status         = COALESCE($3, status)
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, unit_id, code, name, admission_year, status, created_at, updated_at, deleted_at
`

type UpdateGroupParams struct {
	Name          pgtype.Text
	AdmissionYear pgtype.Int4
	Status        pgtype.Text
	ID            string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (OikumeneaEducationGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.AdmissionYear,
		arg.Status,
		arg.ID,
	)
	var i OikumeneaEducationGroup
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Code,
		&i.Name,
		&i.AdmissionYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrgProfile = `-- name: UpdateOrgProfile :one
UPDATE oikumenea.education_org_profiles SET
  kind_id    = COALESCE($1, kind_id),
  country_id = COALESCE($2, country_id),
  founded_on = COALESCE($3, founded_on),
  closed_on  = COALESCE($4, closed_on),
  state      = COALESCE($5, state)
WHERE institution_id = $6 AND deleted_at IS NULL
RETURNING institution_id, kind_id, country_id, founded_on, closed_on, state, created_at, updated_at, deleted_at
`

type UpdateOrgProfileParams struct {
	KindID    pgtype.Text
	CountryID pgtype.Text
	FoundedOn pgtype.Date
	ClosedOn  pgtype.Date
	State     pgtype.Text
	ID        string
}

func (q *Queries) UpdateOrgProfile(ctx context.Context, arg UpdateOrgProfileParams) (OikumeneaEducationOrgProfile, error) {
	row := q.db.QueryRow(ctx, updateOrgProfile,
		arg.KindID,
		arg.CountryID,
		arg.FoundedOn,
		arg.ClosedOn,
		arg.State,
		arg.ID,
	)
	var i OikumeneaEducationOrgProfile
	err := row.Scan(
		&i.InstitutionID,
		&i.KindID,
		&i.CountryID,
		&i.FoundedOn,
		&i.ClosedOn,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE oikumenea.education_positions SET
  title      = COALESCE($1, title),
  sort_order = COALESCE($2, sort_order)
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, institution_id, unit_id, code, title, status, sort_order, created_at, updated_at, deleted_at
`

type UpdatePositionParams struct {
	Title     pgtype.Text
	SortOrder pgtype.Int4
	ID        string
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (OikumeneaEducationPosition, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.Title, arg.SortOrder, arg.ID)
	var i OikumeneaEducationPosition
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.UnitID,
		&i.Code,
		&i.Title,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertInstitutionKind = `-- name: UpsertInstitutionKind :one
INSERT INTO oikumenea.education_institution_kinds (code, name, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (code) WHERE deleted_at IS NULL
DO UPDATE SET name = EXCLUDED.name, sort_order = COALESCE(EXCLUDED.sort_order, oikumenea.education_institution_kinds.sort_order), updated_at = now()
RETURNING id, code, name, status, sort_order, created_at, updated_at, deleted_at
`

type UpsertInstitutionKindParams struct {
	Code      string
	Name      string
	SortOrder pgtype.Int4
}

func (q *Queries) UpsertInstitutionKind(ctx context.Context, arg UpsertInstitutionKindParams) (OikumeneaEducationInstitutionKind, error) {
	row := q.db.QueryRow(ctx, upsertInstitutionKind, arg.Code, arg.Name, arg.SortOrder)
	var i OikumeneaEducationInstitutionKind
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
