-- 0023 religion (M22 — Religion core: multi-faith taxonomy & organization).
--
-- The religion domain (docs/modules/religion.md / D-Religion, refined M22 design 2026-06-19). This is
-- the M22 SLICE ONLY: the faith taxonomy + the organization attributes. Clergy (M23), lay affiliation
-- (M24) and discovery/sites (M25) are designed-but-deferred and ship in later migrations.
--
-- Binding design rule (D-Religion): NO faith's vocabulary is hard-coded. Every faith term — religion,
-- branch, tradition, denomination, theism type, org kind, policy kind — is a CATALOG ROW (D-Code /
-- D-i18n), never a CHECK enum and never an `if faith == …` branch. The only CHECK enums here are fixed
-- lifecycle statuses.
--
-- Taxonomy shape (refined): a SINGLE recursive `religion_taxa` tree (parent_id self-FK) + a maintained
-- `religion_taxa_closure` — reusing the proven language_languoids-forest / education_unit_closure
-- pattern, NOT three fixed catalog tables. Each taxon carries a catalog-driven level marker
-- (`rank_id` → religion_taxon_ranks: religion→branch→tradition→sub_tradition→denomination) so the main
-- branches stay findable, an optional `wikidata_id` anchor, and a denormalized root `religion_id`
-- (derived via the closure here, like language_languoids.family_code).
--
-- Organization: a religious body is a tenant_units row (reused, not a new hierarchy) placed in the
-- three seeded religion graphs (canonical authority-bearing; tradition + affiliation directory-only).
-- A unit's faith attributes are religion_org_profiles (1:1, keyed by the unit RID) + the M:N
-- religion_org_classifications (many tradition tags, one primary). Religion-type (theism) classification
-- resolves nearest-declared-wins down the closure, and a unit may override via religion_unit_classifications.
--
-- new_id() reads no GUC (D-ResourceIdentifiers), so the curated taxonomy seed (generated by the
-- reproducible deploy/religion-presets/gen-presets.py, anchored to Wikidata QIDs) is embedded directly.
--
-- RLS: the four UNIT-SCOPED tables (org_profiles / org_classifications / unit_classifications /
-- org_policies) carry the app.readable_units / app.writable_units backstop (D-RLSDefenseInDepth),
-- mirroring membership_positions. The instance-level catalogs + the taxonomy tree/closure carry NO RLS
-- (reference data, not scoped to tenant_units — like education and tenant_graphs/closure).
--
-- Expand-only (L-UpgradeSafe / D-Migrations); depends on 0000 (new_id), 0003 tenant (tenant_units /
-- tenant_graphs), 0005 person (person_persons) and 0011 (the RLS app role).

-- ---------------------------------------------------------------------------------------------------
-- RID registry (D-ResourceIdentifiers): the new `religion` service (16) + its object/link/action types.
-- pkg/rid mirrors these and asserts equality at boot (kind<>3), so they are added in both places together.
-- ---------------------------------------------------------------------------------------------------
INSERT INTO oikumenea.platform_rid_services (code, module) VALUES (16, 'religion');

INSERT INTO oikumenea.platform_rid_types (service_code, kind, type_code, type_name) VALUES
  -- religion objects
  (16,1,1,'taxon'),(16,1,2,'taxon_rank'),(16,1,3,'classification'),
  (16,1,4,'org_kind'),(16,1,5,'policy_kind'),(16,1,6,'org_policy'),
  -- religion links
  (16,2,1,'classified_as'),
  -- religion Action RID (kind=3, excluded from the Go-mirror size check)
  (16,3,0,'action');

-- ===================================================================================================
-- Catalogs (D-Code / D-i18n): code + translatable name (default-locale here, other locales in the
-- localization store). Instance-admin-managed.
-- ===================================================================================================

-- religion_taxon_ranks — the ordered STRUCTURAL level scaffold (religion → branch → tradition →
-- sub_tradition → denomination). Structural, not faith vocabulary; a faith need not use every level
-- (the closure carries true depth). Extensible.
CREATE TABLE oikumenea.religion_taxon_ranks (
  id         uuid PRIMARY KEY DEFAULT oikumenea.new_id(16,1,2),  -- religion / object / taxon_rank
  code       text NOT NULL,
  name       text NOT NULL,                  -- default-locale display name; translatable via the i18n store
  ordinal    integer NOT NULL,               -- relative depth/rank of the level (religion=0 … denomination=4)
  status     text NOT NULL DEFAULT 'active' CHECK (status IN ('active','retired')),
  sort_order integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT religion_taxon_ranks_rid_shape
    CHECK (oikumenea.rid_service(id)=16 AND oikumenea.rid_kind(id)=1 AND oikumenea.rid_type(id)=2)
);
CREATE UNIQUE INDEX religion_taxon_ranks_code_active
  ON oikumenea.religion_taxon_ranks (code) WHERE deleted_at IS NULL;
CREATE TRIGGER religion_taxon_ranks_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_taxon_ranks
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_taxon_ranks.id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxon_ranks.code IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxon_ranks.name IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxon_ranks.ordinal IS 'pii:none';

INSERT INTO oikumenea.religion_taxon_ranks (code, name, ordinal, sort_order) VALUES
  ('religion','Religion',0,0),
  ('branch','Branch',1,1),
  ('tradition','Tradition',2,2),
  ('sub_tradition','Sub-tradition',3,3),
  ('denomination','Denomination',4,4);

-- religion_classifications — the religion-type ("theism") catalog, attached M:N to taxa (and overridable
-- per unit). A faith may carry several (Hinduism = monotheistic + polytheistic + monistic).
CREATE TABLE oikumenea.religion_classifications (
  id          uuid PRIMARY KEY DEFAULT oikumenea.new_id(16,1,3),  -- religion / object / classification
  code        text NOT NULL,
  name        text NOT NULL,
  description text,
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active','retired')),
  sort_order  integer,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  CONSTRAINT religion_classifications_rid_shape
    CHECK (oikumenea.rid_service(id)=16 AND oikumenea.rid_kind(id)=1 AND oikumenea.rid_type(id)=3)
);
CREATE UNIQUE INDEX religion_classifications_code_active
  ON oikumenea.religion_classifications (code) WHERE deleted_at IS NULL;
CREATE TRIGGER religion_classifications_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_classifications
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_classifications.id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_classifications.code IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_classifications.name IS 'pii:none';

INSERT INTO oikumenea.religion_classifications (code, name, sort_order) VALUES
  ('monotheistic','Monotheistic',10),
  ('polytheistic','Polytheistic',20),
  ('henotheistic','Henotheistic',30),
  ('monistic','Monistic',40),
  ('nontheistic','Nontheistic',50),
  ('pantheistic','Pantheistic',60),
  ('panentheistic','Panentheistic',70),
  ('animistic','Animistic',80),
  ('dualistic','Dualistic',90),
  ('deistic','Deistic',100),
  ('agnostic','Agnostic',110),
  ('atheistic','Atheistic',120);

-- ===================================================================================================
-- Taxonomy: the recursive religion_taxa tree + its maintained closure (+ theism tags on taxa).
-- ===================================================================================================

-- religion_taxa — one node in the faith classification tree. `parent_id` is a strict-tree containment
-- self-FK (RESTRICT; NULL = a root religion) — NOT a reified Link. `rank_id` is the level marker;
-- `religion_id` is the denormalized root (derived via closure, below). `code` is unique among active.
CREATE TABLE oikumenea.religion_taxa (
  id             uuid PRIMARY KEY DEFAULT oikumenea.new_id(16,1,1),  -- religion / object / taxon
  parent_id      uuid REFERENCES oikumenea.religion_taxa(id) ON DELETE RESTRICT,  -- NULL = root religion
  rank_id        uuid NOT NULL REFERENCES oikumenea.religion_taxon_ranks(id) ON DELETE RESTRICT,
  religion_id    uuid REFERENCES oikumenea.religion_taxa(id) ON DELETE RESTRICT,  -- denormalized root (derived)
  code           text NOT NULL,
  name           text NOT NULL,                 -- default-locale display name; translatable via the i18n store
  description    text,
  wikidata_id    text,                          -- optional external anchor (e.g. Q5043)
  icon           text,
  sort_order     integer,
  source         text,                          -- importing/curating dataset id (provenance)
  source_version text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  deleted_at     timestamptz,
  CONSTRAINT religion_taxa_rid_shape
    CHECK (oikumenea.rid_service(id)=16 AND oikumenea.rid_kind(id)=1 AND oikumenea.rid_type(id)=1),
  CONSTRAINT religion_taxa_not_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE UNIQUE INDEX religion_taxa_code_active
  ON oikumenea.religion_taxa (code) WHERE deleted_at IS NULL;
CREATE INDEX religion_taxa_parent_idx ON oikumenea.religion_taxa (parent_id);
CREATE INDEX religion_taxa_rank_idx ON oikumenea.religion_taxa (rank_id) WHERE deleted_at IS NULL;
CREATE INDEX religion_taxa_religion_idx ON oikumenea.religion_taxa (religion_id) WHERE deleted_at IS NULL;
CREATE INDEX religion_taxa_wikidata_idx ON oikumenea.religion_taxa (wikidata_id) WHERE deleted_at IS NULL;
CREATE TRIGGER religion_taxa_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_taxa
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_taxa.id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa.parent_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa.rank_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa.religion_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa.code IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa.name IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa.wikidata_id IS 'pii:none';

-- religion_taxa_closure — derived transitive closure of the taxonomy tree (mirrors
-- education_unit_closure / language_languoid_closure). Composite key, no RID; reflexive (t,t,0) row.
-- Rebuilt in SQL on every taxon insert/reparent by the application; bulk-built from the seed below.
CREATE TABLE oikumenea.religion_taxa_closure (
  ancestor_id   uuid NOT NULL REFERENCES oikumenea.religion_taxa(id) ON DELETE CASCADE,
  descendant_id uuid NOT NULL REFERENCES oikumenea.religion_taxa(id) ON DELETE CASCADE,
  depth         integer NOT NULL,
  PRIMARY KEY (ancestor_id, descendant_id)
);
CREATE INDEX religion_taxa_closure_descendant_idx
  ON oikumenea.religion_taxa_closure (descendant_id);
COMMENT ON COLUMN oikumenea.religion_taxa_closure.ancestor_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa_closure.descendant_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxa_closure.depth IS 'pii:none';

-- religion_taxon_classifications — theism tags on a taxon (M:N). Bare join, no RID. The resolution
-- (nearest-declared-wins down the closure) is computed at read time, never stored.
CREATE TABLE oikumenea.religion_taxon_classifications (
  taxon_id          uuid NOT NULL REFERENCES oikumenea.religion_taxa(id) ON DELETE CASCADE,
  classification_id uuid NOT NULL REFERENCES oikumenea.religion_classifications(id) ON DELETE RESTRICT,
  created_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (taxon_id, classification_id)
);
COMMENT ON COLUMN oikumenea.religion_taxon_classifications.taxon_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_taxon_classifications.classification_id IS 'pii:none';

-- ---------------------------------------------------------------------------------------------------
-- Curated taxonomy seed (deploy/religion-presets, anchored to Wikidata QIDs). Inserted in waves by
-- level so each row's parent already exists; codes are globally unique so parents resolve by code.
-- Depth is uneven on purpose (Christianity is deepest; the major Orthodox/Catholic/Oriental churches
-- are seeded at denomination level under their branch). Source-tagged for provenance/idempotency.
-- ---------------------------------------------------------------------------------------------------

-- Wave 0 — religions (root; parent NULL).
INSERT INTO oikumenea.religion_taxa (code, name, rank_id, wikidata_id, sort_order, source, source_version)
SELECT v.code, v.name, r.id, v.qid, v.so, 'religion-presets', '2026.06'
FROM (VALUES
  ('christianity','Christianity','Q5043',10),
  ('islam','Islam','Q432',20),
  ('judaism','Judaism','Q9268',30),
  ('hinduism','Hinduism','Q9089',40),
  ('buddhism','Buddhism','Q748',50),
  ('sikhism','Sikhism','Q9554',60),
  ('jainism','Jainism','Q9163',70),
  ('bahai','Bahá''í Faith','Q43066',80),
  ('shinto','Shinto','Q1409',90),
  ('taoism','Taoism','Q9598',100),
  ('confucianism','Confucianism','Q9581',110),
  ('zoroastrianism','Zoroastrianism','Q9601',120),
  ('atheism','Atheism','Q7066',124),
  ('agnosticism','Agnosticism','Q41719',126),
  ('traditional','Traditional & indigenous religions',NULL,130),
  ('other','Other / unclassified',NULL,140)
) AS v(code,name,qid,so)
JOIN oikumenea.religion_taxon_ranks r ON r.code='religion';

-- Wave 1 — branches (parent = a religion).
INSERT INTO oikumenea.religion_taxa (code, name, rank_id, parent_id, wikidata_id, sort_order, source, source_version)
SELECT v.code, v.name, rk.id, p.id, v.qid, v.so, 'religion-presets', '2026.06'
FROM (VALUES
  -- Christianity (the major branches)
  ('christianity','catholicism','Catholicism','Q1841',10),
  ('christianity','eastern_orthodoxy','Eastern Orthodoxy','Q3333484',20),
  ('christianity','oriental_orthodoxy','Oriental Orthodoxy','Q156954',30),
  ('christianity','church_of_the_east','Church of the East','Q470330',40),
  ('christianity','protestantism','Protestantism','Q23540',50),
  ('christianity','restorationism','Restorationism & nontrinitarian','Q1140229',60),
  ('christianity','independent_christianity','Independent / nondenominational',NULL,70),
  -- Islam
  ('islam','sunni','Sunni Islam','Q7444',10),
  ('islam','shia','Shia Islam','Q9585',20),
  ('islam','ibadi','Ibadi Islam','Q319540',30),
  ('islam','sufism','Sufism','Q9622',40),
  ('islam','ahmadiyya','Ahmadiyya','Q170027',50),
  -- Judaism
  ('judaism','orthodox_judaism','Orthodox Judaism','Q170238',10),
  ('judaism','conservative_judaism','Conservative Judaism','Q188476',20),
  ('judaism','reform_judaism','Reform Judaism','Q102045',30),
  ('judaism','reconstructionist_judaism','Reconstructionist Judaism','Q1150985',40),
  ('judaism','karaite_judaism','Karaite Judaism','Q484591',50),
  -- Hinduism
  ('hinduism','vaishnavism','Vaishnavism','Q842337',10),
  ('hinduism','shaivism','Shaivism','Q319183',20),
  ('hinduism','shaktism','Shaktism','Q1132099',30),
  ('hinduism','smartism','Smartism','Q707348',40),
  -- Buddhism
  ('buddhism','theravada','Theravāda','Q49003',10),
  ('buddhism','mahayana','Mahāyāna','Q43361',20),
  ('buddhism','vajrayana','Vajrayāna','Q489704',30),
  -- Jainism
  ('jainism','digambara','Digambara','Q1189537',10),
  ('jainism','svetambara','Śvetāmbara','Q726177',20)
) AS v(parent_code,code,name,qid,so)
JOIN oikumenea.religion_taxon_ranks rk ON rk.code='branch'
JOIN oikumenea.religion_taxa p ON p.code=v.parent_code AND p.deleted_at IS NULL;

-- Wave 2 — traditions / movements (parent = a branch).
INSERT INTO oikumenea.religion_taxa (code, name, rank_id, parent_id, wikidata_id, sort_order, source, source_version)
SELECT v.code, v.name, rk.id, p.id, v.qid, v.so, 'religion-presets', '2026.06'
FROM (VALUES
  -- Catholicism (by communion / ritual family)
  ('catholicism','latin_church','Latin Church','Q612330',10),
  ('catholicism','eastern_catholic','Eastern Catholic Churches','Q751392',20),
  -- Protestantism (the historic families)
  ('protestantism','lutheranism','Lutheranism','Q75809',10),
  ('protestantism','reformed','Reformed (Calvinism)','Q101849',20),
  ('protestantism','anglicanism','Anglicanism','Q6423963',30),
  ('protestantism','anabaptism','Anabaptism','Q104088',40),
  ('protestantism','baptist','Baptist','Q93191',50),
  ('protestantism','methodism','Methodism','Q104400',60),
  ('protestantism','pentecostalism','Pentecostalism','Q170022',70),
  ('protestantism','adventism','Adventism','Q164359',80),
  ('protestantism','holiness','Holiness movement','Q1535557',90),
  ('protestantism','evangelicalism','Evangelicalism','Q170997',100),
  ('protestantism','quakerism','Quakerism (Friends)','Q170582',110)
) AS v(parent_code,code,name,qid,so)
JOIN oikumenea.religion_taxon_ranks rk ON rk.code='tradition'
JOIN oikumenea.religion_taxa p ON p.code=v.parent_code AND p.deleted_at IS NULL;

-- Wave 3 — sub-traditions (rite / school / madhhab; parent = a tradition or branch).
INSERT INTO oikumenea.religion_taxa (code, name, rank_id, parent_id, wikidata_id, sort_order, source, source_version)
SELECT v.code, v.name, rk.id, p.id, v.qid, v.so, 'religion-presets', '2026.06'
FROM (VALUES
  -- Sunni schools of jurisprudence (madhāhib)
  ('sunni','hanafi','Hanafi','Q223097',10),
  ('sunni','maliki','Maliki','Q207922',20),
  ('sunni','shafii','Shafiʿi','Q220910',30),
  ('sunni','hanbali','Hanbali','Q200671',40),
  -- Shia branches
  ('shia','twelver','Twelver (Ithnāʿasharī)','Q170382',10),
  ('shia','ismailism','Ismailism','Q179872',20),
  ('shia','zaidiyyah','Zaidiyyah','Q319618',30),
  -- Orthodox Judaism currents
  ('orthodox_judaism','hasidic','Hasidic Judaism','Q170581',10),
  ('orthodox_judaism','modern_orthodox','Modern Orthodox Judaism','Q1426764',20),
  ('orthodox_judaism','haredi','Haredi Judaism','Q208163',30),
  -- Reformed currents
  ('reformed','presbyterianism','Presbyterianism','Q178169',10),
  ('reformed','congregationalism','Congregationalism','Q1062789',20),
  ('reformed','continental_reformed','Continental Reformed','Q1129121',30)
) AS v(parent_code,code,name,qid,so)
JOIN oikumenea.religion_taxon_ranks rk ON rk.code='sub_tradition'
JOIN oikumenea.religion_taxa p ON p.code=v.parent_code AND p.deleted_at IS NULL;

-- Wave 4 — denominations: the globally-significant historic churches/bodies (Christianity-focused per
-- the M22 boundary). Parent = the relevant branch/tradition (levels may be skipped — the closure
-- carries true depth). Local governed instances (a specific diocese/parish) remain tenant_units.
INSERT INTO oikumenea.religion_taxa (code, name, rank_id, parent_id, wikidata_id, sort_order, source, source_version)
SELECT v.code, v.name, rk.id, p.id, v.qid, v.so, 'religion-presets', '2026.06'
FROM (VALUES
  -- Eastern Orthodox autocephalous churches
  ('eastern_orthodoxy','ecumenical_patriarchate','Ecumenical Patriarchate of Constantinople','Q656861',10),
  ('eastern_orthodoxy','church_of_greece','Church of Greece','Q732221',20),
  ('eastern_orthodoxy','russian_orthodox_church','Russian Orthodox Church','Q60150',30),
  ('eastern_orthodoxy','serbian_orthodox_church','Serbian Orthodox Church','Q170377',40),
  ('eastern_orthodoxy','romanian_orthodox_church','Romanian Orthodox Church','Q463041',50),
  ('eastern_orthodoxy','bulgarian_orthodox_church','Bulgarian Orthodox Church','Q463848',60),
  ('eastern_orthodoxy','georgian_orthodox_church','Georgian Orthodox Church','Q1129877',70),
  ('eastern_orthodoxy','orthodox_church_of_ukraine','Orthodox Church of Ukraine','Q30901814',80),
  ('eastern_orthodoxy','orthodox_church_in_america','Orthodox Church in America','Q673354',90),
  -- Oriental Orthodox churches
  ('oriental_orthodoxy','coptic_orthodox_church','Coptic Orthodox Church','Q56183',10),
  ('oriental_orthodoxy','armenian_apostolic_church','Armenian Apostolic Church','Q102140',20),
  ('oriental_orthodoxy','ethiopian_orthodox_tewahedo','Ethiopian Orthodox Tewahedo Church','Q260415',30),
  ('oriental_orthodoxy','syriac_orthodox_church','Syriac Orthodox Church','Q464345',40),
  ('oriental_orthodoxy','malankara_orthodox_church','Malankara Orthodox Syrian Church','Q1815695',50),
  -- Church of the East
  ('church_of_the_east','assyrian_church_of_the_east','Assyrian Church of the East','Q178379',10),
  ('church_of_the_east','ancient_church_of_the_east','Ancient Church of the East','Q1130645',20),
  -- Eastern Catholic sui-iuris churches
  ('eastern_catholic','ukrainian_greek_catholic_church','Ukrainian Greek Catholic Church','Q1192126',10),
  ('eastern_catholic','maronite_church','Maronite Church','Q827512',20),
  ('eastern_catholic','melkite_greek_catholic_church','Melkite Greek Catholic Church','Q1185801',30),
  ('eastern_catholic','chaldean_catholic_church','Chaldean Catholic Church','Q656801',40),
  ('eastern_catholic','syro_malabar_church','Syro-Malabar Church','Q1163901',50),
  ('eastern_catholic','armenian_catholic_church','Armenian Catholic Church','Q807607',60),
  -- Major Protestant denominations (under their tradition)
  ('lutheranism','elca','Evangelical Lutheran Church in America','Q1340004',10),
  ('lutheranism','lcms','Lutheran Church – Missouri Synod','Q1473773',20),
  ('baptist','southern_baptist_convention','Southern Baptist Convention','Q815672',10),
  ('methodism','united_methodist_church','United Methodist Church','Q1446703',10),
  ('anglicanism','church_of_england','Church of England','Q82708',10),
  ('anglicanism','episcopal_church_usa','Episcopal Church (USA)','Q1366000',20),
  ('pentecostalism','assemblies_of_god','Assemblies of God','Q598397',10),
  ('adventism','seventh_day_adventist_church','Seventh-day Adventist Church','Q104319',10),
  -- Restorationist / nontrinitarian bodies
  ('restorationism','lds_church','Church of Jesus Christ of Latter-day Saints','Q19595',10),
  ('restorationism','jehovahs_witnesses','Jehovah''s Witnesses','Q35269',20)
) AS v(parent_code,code,name,qid,so)
JOIN oikumenea.religion_taxon_ranks rk ON rk.code='denomination'
JOIN oikumenea.religion_taxa p ON p.code=v.parent_code AND p.deleted_at IS NULL;

-- Bulk-build the closure over the seeded tree (reflexive + every ancestor→descendant pair).
INSERT INTO oikumenea.religion_taxa_closure (ancestor_id, descendant_id, depth)
WITH RECURSIVE anc AS (
  SELECT id AS ancestor_id, id AS descendant_id, 0 AS depth
  FROM oikumenea.religion_taxa WHERE deleted_at IS NULL
  UNION ALL
  SELECT a.ancestor_id, t.id, a.depth + 1
  FROM anc a
  JOIN oikumenea.religion_taxa t ON t.parent_id = a.descendant_id AND t.deleted_at IS NULL
)
SELECT ancestor_id, descendant_id, depth FROM anc;

-- Derive each taxon's denormalized root religion_id (the ancestor whose parent is NULL).
UPDATE oikumenea.religion_taxa t
SET religion_id = root.ancestor_id
FROM (
  SELECT c.descendant_id, c.ancestor_id
  FROM oikumenea.religion_taxa_closure c
  JOIN oikumenea.religion_taxa a ON a.id = c.ancestor_id AND a.parent_id IS NULL
) root
WHERE root.descendant_id = t.id;

-- Theism tags, seeded at the religion level (overridable lower down via the closure resolution).
INSERT INTO oikumenea.religion_taxon_classifications (taxon_id, classification_id)
SELECT t.id, c.id
FROM (VALUES
  ('christianity','monotheistic'),
  ('islam','monotheistic'),
  ('judaism','monotheistic'),
  ('sikhism','monotheistic'),
  ('bahai','monotheistic'),
  ('zoroastrianism','monotheistic'),
  ('zoroastrianism','dualistic'),
  ('hinduism','monotheistic'),
  ('hinduism','polytheistic'),
  ('hinduism','henotheistic'),
  ('hinduism','monistic'),
  ('buddhism','nontheistic'),
  ('jainism','nontheistic'),
  ('jainism','polytheistic'),
  ('shinto','polytheistic'),
  ('shinto','animistic'),
  ('taoism','pantheistic'),
  ('taoism','polytheistic'),
  ('confucianism','nontheistic'),
  ('atheism','atheistic'),
  ('agnosticism','agnostic'),
  ('traditional','animistic'),
  ('traditional','polytheistic')
) AS v(taxon_code, class_code)
JOIN oikumenea.religion_taxa t ON t.code=v.taxon_code AND t.deleted_at IS NULL
JOIN oikumenea.religion_classifications c ON c.code=v.class_code;

-- ===================================================================================================
-- Organization catalogs.
-- ===================================================================================================

-- religion_org_kinds — descriptive labels for the organizational level of a religious-body unit
-- (never branched on). Optional religion_id ties a kind to a faith (NULL = generic across faiths).
CREATE TABLE oikumenea.religion_org_kinds (
  id          uuid PRIMARY KEY DEFAULT oikumenea.new_id(16,1,4),  -- religion / object / org_kind
  religion_id uuid REFERENCES oikumenea.religion_taxa(id) ON DELETE RESTRICT,  -- NULL = generic
  code        text NOT NULL,
  name        text NOT NULL,
  ordinal     integer,                       -- relative depth/rank of the org level
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active','retired')),
  sort_order  integer,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  CONSTRAINT religion_org_kinds_rid_shape
    CHECK (oikumenea.rid_service(id)=16 AND oikumenea.rid_kind(id)=1 AND oikumenea.rid_type(id)=4)
);
CREATE UNIQUE INDEX religion_org_kinds_code_active
  ON oikumenea.religion_org_kinds (code) WHERE deleted_at IS NULL;
CREATE TRIGGER religion_org_kinds_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_org_kinds
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_org_kinds.id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_kinds.religion_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_kinds.code IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_kinds.name IS 'pii:none';

INSERT INTO oikumenea.religion_org_kinds (code, name, ordinal, sort_order) VALUES
  ('denomination','Denomination',10,10),
  ('jurisdiction','Jurisdiction',20,20),
  ('diocese','Diocese / Eparchy',30,30),
  ('deanery','Deanery',40,40),
  ('parish','Parish',50,50),
  ('congregation','Congregation',60,60),
  ('mission','Mission',70,70),
  ('monastery','Monastery',80,80),
  ('community','Community',90,90),
  ('mosque_community','Mosque community',100,100),
  ('temple_community','Temple community',110,110),
  ('council','Council / Association',120,120);

-- religion_policy_kinds — the data-driven org-policy vocabulary (replaces any faith-specific doctrinal flag).
CREATE TABLE oikumenea.religion_policy_kinds (
  id          uuid PRIMARY KEY DEFAULT oikumenea.new_id(16,1,5),  -- religion / object / policy_kind
  code        text NOT NULL,
  name        text NOT NULL,
  description text,
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active','retired')),
  sort_order  integer,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  CONSTRAINT religion_policy_kinds_rid_shape
    CHECK (oikumenea.rid_service(id)=16 AND oikumenea.rid_kind(id)=1 AND oikumenea.rid_type(id)=5)
);
CREATE UNIQUE INDEX religion_policy_kinds_code_active
  ON oikumenea.religion_policy_kinds (code) WHERE deleted_at IS NULL;
CREATE TRIGGER religion_policy_kinds_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_policy_kinds
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_policy_kinds.id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_policy_kinds.code IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_policy_kinds.name IS 'pii:none';

INSERT INTO oikumenea.religion_policy_kinds (code, name, description, sort_order) VALUES
  ('excludes_child_creation','Excludes child creation','Blocks creating organizations beneath this body',10),
  ('excluded_body','Excluded body','Marks this body as excluded/derecognized for a stated reason',20);

-- ===================================================================================================
-- Organization (reuses tenant_units): per-unit faith profile + classifications + theism override + policies.
-- These four tables are UNIT-SCOPED and carry the RLS backstop (below).
-- ===================================================================================================

-- religion_org_profiles — 1:1 faith attributes of a religious-body unit. Keyed by the unit RID (an
-- extension of the Unit object — no own RID). `org_kind_id` is the descriptive level label.
CREATE TABLE oikumenea.religion_org_profiles (
  unit_id     uuid PRIMARY KEY REFERENCES oikumenea.tenant_units(id) ON DELETE RESTRICT,
  org_kind_id uuid REFERENCES oikumenea.religion_org_kinds(id) ON DELETE RESTRICT,
  short_code  text,                          -- optional display/search abbreviation
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE TRIGGER religion_org_profiles_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_org_profiles
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_org_profiles.unit_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_profiles.org_kind_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_profiles.short_code IS 'pii:none';

-- religion_org_classifications — the M:N tradition tags on a unit (link__classified_as), one primary.
CREATE TABLE oikumenea.religion_org_classifications (
  id         uuid PRIMARY KEY DEFAULT oikumenea.new_id(16,2,1),  -- religion / link / classified_as
  unit_id    uuid NOT NULL REFERENCES oikumenea.tenant_units(id) ON DELETE CASCADE,
  taxon_id   uuid NOT NULL REFERENCES oikumenea.religion_taxa(id) ON DELETE RESTRICT,
  is_primary boolean NOT NULL DEFAULT false,
  source     text,
  confidence text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT religion_org_classifications_rid_shape
    CHECK (oikumenea.rid_service(id)=16 AND oikumenea.rid_kind(id)=2 AND oikumenea.rid_type(id)=1)
);
-- A unit tags a taxon at most once; at most one PRIMARY tag per unit.
CREATE UNIQUE INDEX religion_org_classifications_unit_taxon_active
  ON oikumenea.religion_org_classifications (unit_id, taxon_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX religion_org_classifications_one_primary
  ON oikumenea.religion_org_classifications (unit_id) WHERE is_primary AND deleted_at IS NULL;
CREATE INDEX religion_org_classifications_taxon_idx
  ON oikumenea.religion_org_classifications (taxon_id) WHERE deleted_at IS NULL;
CREATE TRIGGER religion_org_classifications_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_org_classifications
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_org_classifications.id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_classifications.unit_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_classifications.taxon_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_classifications.is_primary IS 'pii:none';

-- religion_unit_classifications — the OPTIONAL per-unit theism override (bare join, no RID). When a
-- unit declares any rows here they OVERRIDE the inherited taxon classification (nearest-declared-wins).
CREATE TABLE oikumenea.religion_unit_classifications (
  unit_id           uuid NOT NULL REFERENCES oikumenea.tenant_units(id) ON DELETE CASCADE,
  classification_id uuid NOT NULL REFERENCES oikumenea.religion_classifications(id) ON DELETE RESTRICT,
  created_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (unit_id, classification_id)
);
COMMENT ON COLUMN oikumenea.religion_unit_classifications.unit_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_unit_classifications.classification_id IS 'pii:none';

-- religion_org_policies — a data-driven eligibility/exclusion rule on a unit (the generic analog of any
-- faith-specific doctrinal gate). excludes_child_creation blocks child creation (enforced in the app).
CREATE TABLE oikumenea.religion_org_policies (
  id                 uuid PRIMARY KEY DEFAULT oikumenea.new_id(16,1,6),  -- religion / object / org_policy
  unit_id            uuid NOT NULL REFERENCES oikumenea.tenant_units(id) ON DELETE CASCADE,
  policy_kind_id     uuid NOT NULL REFERENCES oikumenea.religion_policy_kinds(id) ON DELETE RESTRICT,
  reason             text,
  decided_by_person_id uuid REFERENCES oikumenea.person_persons(id) ON DELETE SET NULL,
  decided_at         timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  deleted_at         timestamptz,
  CONSTRAINT religion_org_policies_rid_shape
    CHECK (oikumenea.rid_service(id)=16 AND oikumenea.rid_kind(id)=1 AND oikumenea.rid_type(id)=6)
);
CREATE UNIQUE INDEX religion_org_policies_unit_kind_active
  ON oikumenea.religion_org_policies (unit_id, policy_kind_id) WHERE deleted_at IS NULL;
CREATE INDEX religion_org_policies_unit_idx
  ON oikumenea.religion_org_policies (unit_id) WHERE deleted_at IS NULL;
CREATE TRIGGER religion_org_policies_set_updated_at
  BEFORE UPDATE ON oikumenea.religion_org_policies
  FOR EACH ROW EXECUTE FUNCTION oikumenea.set_updated_at();
COMMENT ON COLUMN oikumenea.religion_org_policies.id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_policies.unit_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_policies.policy_kind_id IS 'pii:none';
COMMENT ON COLUMN oikumenea.religion_org_policies.decided_by_person_id IS 'pii:none';

-- ===================================================================================================
-- The three seeded religion graphs (D-Graphs / D-DirectoryGraphs). canonical = governance/jurisdiction
-- (authority-bearing; the PDP cascades subtree grants); tradition + affiliation = directory-only.
-- Idempotent (ON CONFLICT on the partial-unique code index), mirroring tenant's boot seed.
-- ===================================================================================================
INSERT INTO oikumenea.tenant_graphs (code, name, is_default, is_authority_bearing) VALUES
  ('canonical',   'Canonical',   false, true),
  ('tradition',   'Tradition',   false, false),
  ('affiliation', 'Affiliation', false, false)
ON CONFLICT (code) WHERE deleted_at IS NULL DO NOTHING;

-- ===================================================================================================
-- RLS backstop (D-RLSDefenseInDepth) on the unit-scoped religion tables. Mirrors membership_positions:
-- keyed on the unit_id column against app.readable_units / app.writable_units (instance admin bypass via
-- app.is_instance_admin). The app-layer PDP + shadow gate over the canonical graph remain AUTHORITATIVE.
-- The instance-level catalogs + the taxonomy tree/closure carry NO RLS (reference data).
-- ===================================================================================================
ALTER TABLE oikumenea.religion_org_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE oikumenea.religion_org_profiles FORCE ROW LEVEL SECURITY;
CREATE POLICY religion_org_profiles_reach ON oikumenea.religion_org_profiles
  USING (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.readable_units', true), ''), ',')::uuid[]))
  WITH CHECK (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.writable_units', true), ''), ',')::uuid[]));

ALTER TABLE oikumenea.religion_org_classifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE oikumenea.religion_org_classifications FORCE ROW LEVEL SECURITY;
CREATE POLICY religion_org_classifications_reach ON oikumenea.religion_org_classifications
  USING (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.readable_units', true), ''), ',')::uuid[]))
  WITH CHECK (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.writable_units', true), ''), ',')::uuid[]));

ALTER TABLE oikumenea.religion_unit_classifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE oikumenea.religion_unit_classifications FORCE ROW LEVEL SECURITY;
CREATE POLICY religion_unit_classifications_reach ON oikumenea.religion_unit_classifications
  USING (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.readable_units', true), ''), ',')::uuid[]))
  WITH CHECK (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.writable_units', true), ''), ',')::uuid[]));

ALTER TABLE oikumenea.religion_org_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE oikumenea.religion_org_policies FORCE ROW LEVEL SECURITY;
CREATE POLICY religion_org_policies_reach ON oikumenea.religion_org_policies
  USING (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.readable_units', true), ''), ',')::uuid[]))
  WITH CHECK (coalesce(current_setting('app.is_instance_admin', true), '') = 'true'
         OR unit_id = ANY (string_to_array(nullif(current_setting('app.writable_units', true), ''), ',')::uuid[]));

-- Advance the single-row schema-version marker the boot-time readiness gate reads (upgrade-safety.md).
UPDATE oikumenea.schema_version SET revision = '0023_religion', applied_at = now() WHERE singleton;
