// Code generated by conjure-go. DO NOT EDIT.

package connector

import (
	"github.com/palantir/pkg/datetime"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

/*
A registered connector — a deployable agent beside the core. `principalId` is the M51 service
principal it authenticates as; disabling that principal stops its reports and wiring reads at
once, so there is no separate kill switch here.
*/
type Connector struct {
	Id string `json:"id"`
	// Stable, locale-agnostic handle (D-Code) — what operators and audit rows reference.
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// The service principal this agent authenticates as. Bound by the core from the caller.
	PrincipalId *string `json:"principalId,omitempty"`
	// active | disabled.
	Status string `json:"status"`
	/*
	   When the core last heard from this agent (registration or a run report). A liveness HINT,
	   not a health verdict — the core never probes connectors.
	*/
	LastSeenAt *datetime.DateTime `json:"lastSeenAt,omitempty"`
	CreatedAt  datetime.DateTime  `json:"createdAt"`
	UpdatedAt  datetime.DateTime  `json:"updatedAt"`
}

func (o Connector) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Connector) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type ConnectorPage struct {
	Connectors    []Connector `json:"connectors"`
	NextPageToken *string     `json:"nextPageToken,omitempty"`
}

func (o ConnectorPage) MarshalJSON() ([]byte, error) {
	if o.Connectors == nil {
		o.Connectors = make([]Connector, 0)
	}
	type _tmpConnectorPage ConnectorPage
	return safejson.Marshal(_tmpConnectorPage(o))
}

func (o *ConnectorPage) UnmarshalJSON(data []byte) error {
	type _tmpConnectorPage ConnectorPage
	var rawConnectorPage _tmpConnectorPage
	if err := safejson.Unmarshal(data, &rawConnectorPage); err != nil {
		return err
	}
	if rawConnectorPage.Connectors == nil {
		rawConnectorPage.Connectors = make([]Connector, 0)
	}
	*o = ConnectorPage(rawConnectorPage)
	return nil
}

func (o ConnectorPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ConnectorPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
One dataset a connector syncs, as reported by that connector. A read model: the connector
stays authoritative for execution, because scheduling lives in the connector.
*/
type ConnectorSource struct {
	Id          string `json:"id"`
	ConnectorId string `json:"connectorId"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	/*
	   The core import target for push-mode sources (e.g. geo-places). Absent for sources that
	   only feed the connector's own lookups.
	*/
	ObjectType *string `json:"objectType,omitempty"`
	// The connector's own schedule string, verbatim, for display. The core never parses it.
	Schedule *string `json:"schedule,omitempty"`
	Enabled  bool    `json:"enabled"`
}

func (o ConnectorSource) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ConnectorSource) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type ConnectorSourceList struct {
	Sources []ConnectorSource `json:"sources"`
}

func (o ConnectorSourceList) MarshalJSON() ([]byte, error) {
	if o.Sources == nil {
		o.Sources = make([]ConnectorSource, 0)
	}
	type _tmpConnectorSourceList ConnectorSourceList
	return safejson.Marshal(_tmpConnectorSourceList(o))
}

func (o *ConnectorSourceList) UnmarshalJSON(data []byte) error {
	type _tmpConnectorSourceList ConnectorSourceList
	var rawConnectorSourceList _tmpConnectorSourceList
	if err := safejson.Unmarshal(data, &rawConnectorSourceList); err != nil {
		return err
	}
	if rawConnectorSourceList.Sources == nil {
		rawConnectorSourceList.Sources = make([]ConnectorSource, 0)
	}
	*o = ConnectorSourceList(rawConnectorSourceList)
	return nil
}

func (o ConnectorSourceList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ConnectorSourceList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
A connector's idempotent self-description. Carries NO principalId: the core binds the row to
the calling principal, so a connector cannot register as another. Re-registering updates the
row and REPLACES the declared source set (sources absent from the payload are retired), which
makes boot-time registration converge without an operator reconciling drift by hand.
*/
type RegisterConnectorRequest struct {
	Code        string              `json:"code"`
	Name        string              `json:"name"`
	Description *string             `json:"description,omitempty"`
	Sources     []SourceDeclaration `json:"sources"`
}

func (o RegisterConnectorRequest) MarshalJSON() ([]byte, error) {
	if o.Sources == nil {
		o.Sources = make([]SourceDeclaration, 0)
	}
	type _tmpRegisterConnectorRequest RegisterConnectorRequest
	return safejson.Marshal(_tmpRegisterConnectorRequest(o))
}

func (o *RegisterConnectorRequest) UnmarshalJSON(data []byte) error {
	type _tmpRegisterConnectorRequest RegisterConnectorRequest
	var rawRegisterConnectorRequest _tmpRegisterConnectorRequest
	if err := safejson.Unmarshal(data, &rawRegisterConnectorRequest); err != nil {
		return err
	}
	if rawRegisterConnectorRequest.Sources == nil {
		rawRegisterConnectorRequest.Sources = make([]SourceDeclaration, 0)
	}
	*o = RegisterConnectorRequest(rawRegisterConnectorRequest)
	return nil
}

func (o RegisterConnectorRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RegisterConnectorRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
Report a run — opening it (`state: running`) and closing it (`succeeded`/`failed`) are the
same call. IDEMPOTENT on (source, externalRunId): a connector retrying its report updates the
run rather than duplicating it, which matters because connectors retry with backoff.
*/
type ReportSyncRunRequest struct {
	// The source's code within the CALLING connector — not a RID, so a connector needs no prior read.
	SourceCode    string             `json:"sourceCode"`
	ExternalRunId *string            `json:"externalRunId,omitempty"`
	State         string             `json:"state"`
	Created       *int               `json:"created,omitempty"`
	Updated       *int               `json:"updated,omitempty"`
	Skipped       *int               `json:"skipped,omitempty"`
	Error         *string            `json:"error,omitempty"`
	StartedAt     *datetime.DateTime `json:"startedAt,omitempty"`
	FinishedAt    *datetime.DateTime `json:"finishedAt,omitempty"`
}

func (o ReportSyncRunRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ReportSyncRunRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// One source in a registration payload.
type SourceDeclaration struct {
	Code       string  `json:"code"`
	Name       string  `json:"name"`
	ObjectType *string `json:"objectType,omitempty"`
	Schedule   *string `json:"schedule,omitempty"`
	// Defaults to true when absent.
	Enabled *bool `json:"enabled,omitempty"`
}

func (o SourceDeclaration) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *SourceDeclaration) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
One reported execution of a source. The counts are the CONNECTOR's account of its work — the
core stores what it is told and does not recompute them.
*/
type SyncRun struct {
	Id       string `json:"id"`
	SourceId string `json:"sourceId"`
	/*
	   The connector's own run id (hermenea's import_runs.id — the same value the M49 chunked
	   envelopes carry as `runId`), so a run correlates with the connector's ledger and with
	   per-row import provenance.
	*/
	ExternalRunId *string `json:"externalRunId,omitempty"`
	// running | succeeded | failed.
	State      string             `json:"state"`
	Created    int                `json:"created"`
	Updated    int                `json:"updated"`
	Skipped    int                `json:"skipped"`
	Error      *string            `json:"error,omitempty"`
	StartedAt  datetime.DateTime  `json:"startedAt"`
	FinishedAt *datetime.DateTime `json:"finishedAt,omitempty"`
}

func (o SyncRun) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *SyncRun) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type SyncRunPage struct {
	Runs          []SyncRun `json:"runs"`
	NextPageToken *string   `json:"nextPageToken,omitempty"`
}

func (o SyncRunPage) MarshalJSON() ([]byte, error) {
	if o.Runs == nil {
		o.Runs = make([]SyncRun, 0)
	}
	type _tmpSyncRunPage SyncRunPage
	return safejson.Marshal(_tmpSyncRunPage(o))
}

func (o *SyncRunPage) UnmarshalJSON(data []byte) error {
	type _tmpSyncRunPage SyncRunPage
	var rawSyncRunPage _tmpSyncRunPage
	if err := safejson.Unmarshal(data, &rawSyncRunPage); err != nil {
		return err
	}
	if rawSyncRunPage.Runs == nil {
		rawSyncRunPage.Runs = make([]SyncRun, 0)
	}
	*o = SyncRunPage(rawSyncRunPage)
	return nil
}

func (o SyncRunPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *SyncRunPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
