// Code generated by conjure-go. DO NOT EDIT.

package hermenea

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/go-oikumenea/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

// The ingestion/scheduler companion's control + read API.
type HermeneaServiceClient interface {
	// Enqueue a sync job for a registered source (the push trigger from oikumenea).
	TriggerSync(ctx context.Context, authHeader bearertoken.Token, sourceArg string) (JobRef, error)
	// List the registered import sources.
	ListSources(ctx context.Context, authHeader bearertoken.Token) ([]ImportSource, error)
	// List import-run lineage (most recent first).
	ListRuns(ctx context.Context, authHeader bearertoken.Token) ([]ImportRun, error)
	// List worker jobs (most recent first).
	ListJobs(ctx context.Context, authHeader bearertoken.Token) ([]WorkerJob, error)
	/*
	   Run a live watchlist screening check (D-Watchlists, M34): the first SYNCHRONOUS oikumenea→hermenea
	   call. Hermenea owns the outbound egress to OFAC/EU/UN/INTERPOL and a ≤24h cache; only per-person
	   match metadata is returned. The real interpol.api.bund.dev connector ships; sanctions providers
	   are a documented pluggable stub.
	*/
	CheckWatchlist(ctx context.Context, authHeader bearertoken.Token, requestArg WatchlistQuery) (WatchlistResult, error)
}

type hermeneaServiceClient struct {
	client httpclient.Client
}

func NewHermeneaServiceClient(client httpclient.Client) HermeneaServiceClient {
	return &hermeneaServiceClient{client: client}
}

func (c *hermeneaServiceClient) TriggerSync(ctx context.Context, authHeader bearertoken.Token, sourceArg string) (JobRef, error) {
	var returnVal *JobRef
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("TriggerSync"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/hermenea/v1/sync/%s", url.PathEscape(fmt.Sprint(sourceArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(JobRef), werror.WrapWithContextParams(ctx, err, "triggerSync failed")
	}
	if returnVal == nil {
		return *new(JobRef), werror.ErrorWithContextParams(ctx, "triggerSync response cannot be nil")
	}
	return *returnVal, nil
}

func (c *hermeneaServiceClient) ListSources(ctx context.Context, authHeader bearertoken.Token) ([]ImportSource, error) {
	var returnVal []ImportSource
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListSources"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/hermenea/v1/sources"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return nil, werror.WrapWithContextParams(ctx, err, "listSources failed")
	}
	if returnVal == nil {
		return nil, werror.ErrorWithContextParams(ctx, "listSources response cannot be nil")
	}
	return returnVal, nil
}

func (c *hermeneaServiceClient) ListRuns(ctx context.Context, authHeader bearertoken.Token) ([]ImportRun, error) {
	var returnVal []ImportRun
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListRuns"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/hermenea/v1/runs"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return nil, werror.WrapWithContextParams(ctx, err, "listRuns failed")
	}
	if returnVal == nil {
		return nil, werror.ErrorWithContextParams(ctx, "listRuns response cannot be nil")
	}
	return returnVal, nil
}

func (c *hermeneaServiceClient) ListJobs(ctx context.Context, authHeader bearertoken.Token) ([]WorkerJob, error) {
	var returnVal []WorkerJob
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListJobs"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/hermenea/v1/jobs"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return nil, werror.WrapWithContextParams(ctx, err, "listJobs failed")
	}
	if returnVal == nil {
		return nil, werror.ErrorWithContextParams(ctx, "listJobs response cannot be nil")
	}
	return returnVal, nil
}

func (c *hermeneaServiceClient) CheckWatchlist(ctx context.Context, authHeader bearertoken.Token, requestArg WatchlistQuery) (WatchlistResult, error) {
	var returnVal *WatchlistResult
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("CheckWatchlist"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/hermenea/v1/watchlist/check"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(WatchlistResult), werror.WrapWithContextParams(ctx, err, "checkWatchlist failed")
	}
	if returnVal == nil {
		return *new(WatchlistResult), werror.ErrorWithContextParams(ctx, "checkWatchlist response cannot be nil")
	}
	return *returnVal, nil
}

// The ingestion/scheduler companion's control + read API.
type HermeneaServiceClientWithAuth interface {
	// Enqueue a sync job for a registered source (the push trigger from oikumenea).
	TriggerSync(ctx context.Context, sourceArg string) (JobRef, error)
	// List the registered import sources.
	ListSources(ctx context.Context) ([]ImportSource, error)
	// List import-run lineage (most recent first).
	ListRuns(ctx context.Context) ([]ImportRun, error)
	// List worker jobs (most recent first).
	ListJobs(ctx context.Context) ([]WorkerJob, error)
	/*
	   Run a live watchlist screening check (D-Watchlists, M34): the first SYNCHRONOUS oikumenea→hermenea
	   call. Hermenea owns the outbound egress to OFAC/EU/UN/INTERPOL and a ≤24h cache; only per-person
	   match metadata is returned. The real interpol.api.bund.dev connector ships; sanctions providers
	   are a documented pluggable stub.
	*/
	CheckWatchlist(ctx context.Context, requestArg WatchlistQuery) (WatchlistResult, error)
}

func NewHermeneaServiceClientWithAuth(client HermeneaServiceClient, authHeader bearertoken.Token) HermeneaServiceClientWithAuth {
	return &hermeneaServiceClientWithAuth{client: client, authHeader: authHeader}
}

type hermeneaServiceClientWithAuth struct {
	client     HermeneaServiceClient
	authHeader bearertoken.Token
}

func (c *hermeneaServiceClientWithAuth) TriggerSync(ctx context.Context, sourceArg string) (JobRef, error) {
	return c.client.TriggerSync(ctx, c.authHeader, sourceArg)
}

func (c *hermeneaServiceClientWithAuth) ListSources(ctx context.Context) ([]ImportSource, error) {
	return c.client.ListSources(ctx, c.authHeader)
}

func (c *hermeneaServiceClientWithAuth) ListRuns(ctx context.Context) ([]ImportRun, error) {
	return c.client.ListRuns(ctx, c.authHeader)
}

func (c *hermeneaServiceClientWithAuth) ListJobs(ctx context.Context) ([]WorkerJob, error) {
	return c.client.ListJobs(ctx, c.authHeader)
}

func (c *hermeneaServiceClientWithAuth) CheckWatchlist(ctx context.Context, requestArg WatchlistQuery) (WatchlistResult, error) {
	return c.client.CheckWatchlist(ctx, c.authHeader, requestArg)
}

func NewHermeneaServiceClientWithTokenProvider(client HermeneaServiceClient, tokenProvider httpclient.TokenProvider) HermeneaServiceClientWithAuth {
	return &hermeneaServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type hermeneaServiceClientWithTokenProvider struct {
	client        HermeneaServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *hermeneaServiceClientWithTokenProvider) TriggerSync(ctx context.Context, sourceArg string) (JobRef, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(JobRef), err
	}
	return c.client.TriggerSync(ctx, bearertoken.Token(token), sourceArg)
}

func (c *hermeneaServiceClientWithTokenProvider) ListSources(ctx context.Context) ([]ImportSource, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return nil, err
	}
	return c.client.ListSources(ctx, bearertoken.Token(token))
}

func (c *hermeneaServiceClientWithTokenProvider) ListRuns(ctx context.Context) ([]ImportRun, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return nil, err
	}
	return c.client.ListRuns(ctx, bearertoken.Token(token))
}

func (c *hermeneaServiceClientWithTokenProvider) ListJobs(ctx context.Context) ([]WorkerJob, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return nil, err
	}
	return c.client.ListJobs(ctx, bearertoken.Token(token))
}

func (c *hermeneaServiceClientWithTokenProvider) CheckWatchlist(ctx context.Context, requestArg WatchlistQuery) (WatchlistResult, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(WatchlistResult), err
	}
	return c.client.CheckWatchlist(ctx, bearertoken.Token(token), requestArg)
}
