// Code generated by conjure-go. DO NOT EDIT.

package dataimport

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/go-oikumenea/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

/*
The generic reference-data import endpoint (instance-scope, import.manage). Called by the
hermenea companion's loader; idempotent and non-destructive.
*/
type ImportServiceClient interface {
	// Idempotently upsert a canonical envelope into the {objectType} catalog.
	ImportObjects(ctx context.Context, authHeader bearertoken.Token, objectTypeArg string, envelopeArg CanonicalEnvelope) (ImportResult, error)
}

type importServiceClient struct {
	client httpclient.Client
}

func NewImportServiceClient(client httpclient.Client) ImportServiceClient {
	return &importServiceClient{client: client}
}

func (c *importServiceClient) ImportObjects(ctx context.Context, authHeader bearertoken.Token, objectTypeArg string, envelopeArg CanonicalEnvelope) (ImportResult, error) {
	var returnVal *ImportResult
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ImportObjects"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/import/v1/import/%s", url.PathEscape(fmt.Sprint(objectTypeArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(envelopeArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(ImportResult), werror.WrapWithContextParams(ctx, err, "importObjects failed")
	}
	if returnVal == nil {
		return *new(ImportResult), werror.ErrorWithContextParams(ctx, "importObjects response cannot be nil")
	}
	return *returnVal, nil
}

/*
The generic reference-data import endpoint (instance-scope, import.manage). Called by the
hermenea companion's loader; idempotent and non-destructive.
*/
type ImportServiceClientWithAuth interface {
	// Idempotently upsert a canonical envelope into the {objectType} catalog.
	ImportObjects(ctx context.Context, objectTypeArg string, envelopeArg CanonicalEnvelope) (ImportResult, error)
}

func NewImportServiceClientWithAuth(client ImportServiceClient, authHeader bearertoken.Token) ImportServiceClientWithAuth {
	return &importServiceClientWithAuth{client: client, authHeader: authHeader}
}

type importServiceClientWithAuth struct {
	client     ImportServiceClient
	authHeader bearertoken.Token
}

func (c *importServiceClientWithAuth) ImportObjects(ctx context.Context, objectTypeArg string, envelopeArg CanonicalEnvelope) (ImportResult, error) {
	return c.client.ImportObjects(ctx, c.authHeader, objectTypeArg, envelopeArg)
}

func NewImportServiceClientWithTokenProvider(client ImportServiceClient, tokenProvider httpclient.TokenProvider) ImportServiceClientWithAuth {
	return &importServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type importServiceClientWithTokenProvider struct {
	client        ImportServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *importServiceClientWithTokenProvider) ImportObjects(ctx context.Context, objectTypeArg string, envelopeArg CanonicalEnvelope) (ImportResult, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(ImportResult), err
	}
	return c.client.ImportObjects(ctx, bearertoken.Token(token), objectTypeArg, envelopeArg)
}
