// Code generated by conjure-go. DO NOT EDIT.

package dataimport

import (
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

/*
The interchange document hermenea produces and oikumenea upserts. `objectType` must equal the
path object-type. `records` are object-type-specific JSON objects the registered handler reads.
*/
type CanonicalEnvelope struct {
	// The importable object-type key (e.g. geo-countries); must match the path parameter.
	ObjectType string `json:"objectType"`
	// Stable source identifier (e.g. iso-3166) — stamped as row provenance.
	Source string `json:"source"`
	// The source's version/edition (e.g. 2024) — stamped as row provenance.
	SourceVersion *string `json:"sourceVersion,omitempty"`
	// License/attribution string carried for lineage (not persisted per-row).
	License *string `json:"license,omitempty"`
	// ISO-8601 timestamp the upstream snapshot was generated (lineage only).
	GeneratedAt *string `json:"generatedAt,omitempty"`
	/*
	   The owning organization RID when the target is ORG-OWNED operational data (M55 / the RLS
	   service arm): the import permission is then checked against this org, so an org-confined
	   connector imports only its own organization's data and a foreign-org grant is rejected.
	   Absent = an instance-wide reference catalog (the pre-M55 default), which demands an
	   instance-wide grant.
	*/
	OrgId *string `json:"orgId,omitempty"`
	// The object-type-specific records to upsert; each is a JSON object.
	Records []interface{} `json:"records"`
	/*
	   Hermenea's import-run identifier when the dataset arrives as a chunked sequence of
	   envelopes (R-05). Lineage/audit correlation only — oikumenea keeps no per-run state;
	   resumability is owned by the sender (last-acked seq on the hermenea job).
	*/
	RunId *string `json:"runId,omitempty"`
	/*
	   1-based chunk index within a chunked run. Chunks are sent sequentially and each is
	   applied in its own transaction; replaying a chunk is safe (every record apply is a
	   natural-key idempotent upsert). Absent (with runId/isLast absent) = a single-shot
	   envelope, the pre-chunking semantics.
	*/
	Seq *int `json:"seq,omitempty"`
	/*
	   True on the final chunk of a chunked run; triggers the object-type's batch
	   finalizers (e.g. the languoid closure + family_code rebuild). The final chunk may
	   carry zero records (a pure finalize marker).
	*/
	IsLast *bool `json:"isLast,omitempty"`
}

func (o CanonicalEnvelope) MarshalJSON() ([]byte, error) {
	if o.Records == nil {
		o.Records = make([]interface{}, 0)
	}
	type _tmpCanonicalEnvelope CanonicalEnvelope
	return safejson.Marshal(_tmpCanonicalEnvelope(o))
}

func (o *CanonicalEnvelope) UnmarshalJSON(data []byte) error {
	type _tmpCanonicalEnvelope CanonicalEnvelope
	var rawCanonicalEnvelope _tmpCanonicalEnvelope
	if err := safejson.Unmarshal(data, &rawCanonicalEnvelope); err != nil {
		return err
	}
	if rawCanonicalEnvelope.Records == nil {
		rawCanonicalEnvelope.Records = make([]interface{}, 0)
	}
	*o = CanonicalEnvelope(rawCanonicalEnvelope)
	return nil
}

func (o CanonicalEnvelope) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CanonicalEnvelope) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// The per-object-type outcome of one idempotent upsert.
type ImportResult struct {
	ObjectType string `json:"objectType"`
	// Rows newly inserted.
	Created int `json:"created"`
	// Existing rows whose values changed.
	Updated int `json:"updated"`
	// Rows already up to date (idempotent no-ops).
	Skipped int `json:"skipped"`
}

func (o ImportResult) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ImportResult) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
