// Code generated by conjure-go. DO NOT EDIT.

package religion

import (
	"context"
	"net/http"
	"strconv"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

/*
The multi-faith taxonomy (recursive religion_taxa + closure) with a catalog-driven level marker,
the religion-type classifications, the per-faith catalogs, and the per-unit organization attributes.
Reads gate on `religion.read`; taxonomy/catalog writes on `religion.catalog.manage` (instance);
per-unit organization writes on `religionorg.manage` (checked over the canonical graph). Writes are
audited in-process (D-Audit).
*/
type ReligionService interface {
	ListTaxonRanks(ctx context.Context, authHeader bearertoken.Token) (TaxonRankList, error)
	UpsertTaxonRank(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertTaxonRankRequest) (TaxonRank, error)
	ListClassifications(ctx context.Context, authHeader bearertoken.Token) (ClassificationList, error)
	UpsertClassification(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertClassificationRequest) (Classification, error)
	ListOrgKinds(ctx context.Context, authHeader bearertoken.Token) (OrgKindList, error)
	UpsertOrgKind(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertOrgKindRequest) (OrgKind, error)
	ListPolicyKinds(ctx context.Context, authHeader bearertoken.Token) (PolicyKindList, error)
	UpsertPolicyKind(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertPolicyKindRequest) (PolicyKind, error)
	// Search/filter the taxonomy. Filters compose; results carry closure depth where a parent/root is given.
	ListTaxa(ctx context.Context, authHeader bearertoken.Token, rankArg *string, parentArg *string, religionArg *string, classificationArg *string, queryArg *string, pageSizeArg *int, pageTokenArg *string) (TaxonPage, error)
	/*
	   Facet distributions over the taxonomy — the dashboard half of the facet vocabulary (M58 /
	   D-ObjectFacets). Takes exactly the filter args `listTaxa` takes (minus paging) plus an
	   optional `facets` CSV, so a dashboard and a list are two renderings of ONE request state
	   and a chart segment is a link to the same URL with one more filter applied.

	   `totalCount` equals the number of rows exhaustively paging `listTaxa` with these same
	   filters would return. One round-trip serves the whole dashboard.

	   ONE aggregate arm, with no subject and no scoped twin — but for the OPPOSITE reason to the
	   audit ledger's single arm. The taxonomy is flat instance-global reference data with no
	   row-level security and no unit reach (the RLS in this module is on the unit-scoped
	   `religion_org_*` tables, not here), so `religion.read` held anywhere is the whole
	   visibility decision and there is nothing for a second arm to narrow.

	   `subtree` and `classification` do not partition the result set — see TaxonStats.

	   The path is `/stats/taxa` rather than `/taxa/stats` because the server's router rejects a
	   literal path segment that is a sibling of `{taxonId}`.
	*/
	TaxonStats(ctx context.Context, authHeader bearertoken.Token, facetsArg *string, rankArg *string, parentArg *string, religionArg *string, classificationArg *string, queryArg *string) (TaxonStats, error)
	CreateTaxon(ctx context.Context, authHeader bearertoken.Token, requestArg CreateTaxonRequest) (Taxon, error)
	GetTaxon(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string) (Taxon, error)
	UpdateTaxon(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string, requestArg UpdateTaxonRequest) (Taxon, error)
	DeleteTaxon(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string) error
	// Move a taxon under a new parent, recomputing the closure. Returns Religion:TaxonCycleDetected on a cycle.
	ReparentTaxon(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string, requestArg ReparentTaxonRequest) (Taxon, error)
	/*
	   Recompute the whole-tree taxonomy closure (admin maintenance). Pathed under /taxonomy (not
	   /taxa) so the static segment does not collide with the /taxa/{taxonId} wildcard route.
	*/
	RebuildClosure(ctx context.Context, authHeader bearertoken.Token) (ClosureReport, error)
	// The taxon's resolved theism classifications (nearest declaring ancestor wins).
	GetEffectiveClassifications(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string) (ClassificationList, error)
	// Replace the theism tags declared directly on this taxon.
	SetTaxonClassifications(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string, requestArg SetClassificationsRequest) (ClassificationList, error)
	GetOrgProfile(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (OrgProfile, error)
	SetOrgProfile(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg SetOrgProfileRequest) (OrgProfile, error)
	AddOrgClassification(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg AddOrgClassificationRequest) (OrgClassification, error)
	RemoveOrgClassification(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, linkIdArg string) error
	// Replace the unit's theism override set (empty list clears it, restoring inheritance).
	SetUnitTypeOverride(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg SetClassificationsRequest) (ClassificationList, error)
	GetEffectiveType(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (EffectiveType, error)
	ListOrgPolicies(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (OrgPolicyList, error)
	AddOrgPolicy(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg AddOrgPolicyRequest) (OrgPolicy, error)
	RemoveOrgPolicy(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, policyIdArg string) error
	/*
	   Create a child religious-body unit under this parent in the canonical graph. Rejected with
	   Religion:ChildCreationExcluded if the parent carries an active excludes_child_creation policy.
	*/
	CreateChildOrg(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg CreateChildOrgRequest) (OrgProfile, error)
	/*
	   Create a top-level religious body (M41 / D-UnifiedOrgGraph): a `church`-domain tenant
	   organization + its root religious-body unit + profile. Instance-level (religion.catalog.manage).
	*/
	CreateRootOrg(ctx context.Context, authHeader bearertoken.Token, requestArg CreateRootOrgRequest) (OrgProfile, error)
	ListGradeCategories(ctx context.Context, authHeader bearertoken.Token) (GradeCategoryList, error)
	UpsertGradeCategory(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertGradeCategoryRequest) (GradeCategory, error)
	// List clergy grades, optionally filtered to a tradition taxon (RID or code), ordered by tradition then ordinal.
	ListClergyGrades(ctx context.Context, authHeader bearertoken.Token, traditionArg *string) (ClergyGradeList, error)
	UpsertClergyGrade(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertClergyGradeRequest) (ClergyGrade, error)
	ListOfficeTypes(ctx context.Context, authHeader bearertoken.Token) (OfficeTypeList, error)
	UpsertOfficeType(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertOfficeTypeRequest) (OfficeType, error)
	ListPersonClergyCredentials(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (ClergyCredentialList, error)
	// The clergy roster of an organization unit (people holding a credential conferred by it).
	ListUnitClergyCredentials(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (ClergyCredentialList, error)
	AddClergyCredential(ctx context.Context, authHeader bearertoken.Token, personIdArg string, requestArg AddClergyCredentialRequest) (ClergyCredential, error)
	// Flip a credential's status (e.g. suspend/revoke) and/or set effective-dating. Never deletes.
	UpdateClergyCredential(ctx context.Context, authHeader bearertoken.Token, credentialIdArg string, requestArg UpdateClergyCredentialRequest) (ClergyCredential, error)
	ListAffiliationTypes(ctx context.Context, authHeader bearertoken.Token) (AffiliationTypeList, error)
	UpsertAffiliationType(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertAffiliationTypeRequest) (AffiliationType, error)
	// List a person's lay religious affiliations. pii:special — gated on affiliation.manage; the belief value is decrypted.
	ListPersonAffiliations(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (AffiliationList, error)
	AddAffiliation(ctx context.Context, authHeader bearertoken.Token, personIdArg string, requestArg AddAffiliationRequest) (Affiliation, error)
	UpdateAffiliation(ctx context.Context, authHeader bearertoken.Token, affiliationIdArg string, requestArg UpdateAffiliationRequest) (Affiliation, error)
	DeleteAffiliation(ctx context.Context, authHeader bearertoken.Token, affiliationIdArg string) error
	ListSiteTypes(ctx context.Context, authHeader bearertoken.Token) (SiteTypeList, error)
	UpsertSiteType(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertSiteTypeRequest) (SiteType, error)
	ListServiceTypes(ctx context.Context, authHeader bearertoken.Token) (ServiceTypeList, error)
	UpsertServiceType(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertServiceTypeRequest) (ServiceType, error)
	// List an org unit's sites (exact coordinates, for authorized owners).
	ListUnitSites(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (SiteList, error)
	CreateSite(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg CreateSiteRequest) (Site, error)
	UpdateSite(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, requestArg UpdateSiteRequest) (Site, error)
	DeleteSite(ctx context.Context, authHeader bearertoken.Token, siteIdArg string) error
	ListSiteSchedules(ctx context.Context, authHeader bearertoken.Token, siteIdArg string) (ServiceScheduleList, error)
	CreateSchedule(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, requestArg CreateScheduleRequest) (ServiceSchedule, error)
	DeleteSchedule(ctx context.Context, authHeader bearertoken.Token, scheduleIdArg string) error
	ListUnitAliases(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (AliasList, error)
	CreateAlias(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg CreateAliasRequest) (Alias, error)
	DeleteAlias(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, aliasIdArg string) error
	/*
	   Closure-aware PostGIS discovery search over PUBLIC sites. Supply a radius (lat+lng+radiusM via
	   ST_DWithin) or a bounding box (minLat/minLng/maxLat/maxLng via ST_Intersects); optionally filter
	   by a religion taxon (org units classified under it via the taxonomy closure), a service language/
	   weekday/online toggle, and a fuzzy match on the unit code/name or an alias. Coordinates are
	   coarsened per each site's publicPrecision.
	*/
	SearchSites(ctx context.Context, authHeader bearertoken.Token, latArg *float64, lngArg *float64, radiusMArg *float64, minLatArg *float64, minLngArg *float64, maxLatArg *float64, maxLngArg *float64, religionArg *string, languageArg *string, dayOfWeekArg *int, onlineOnlyArg *bool, queryArg *string, pageSizeArg *int) (DiscoverySitePage, error)
}

// RegisterRoutesReligionService registers handlers for the ReligionService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesReligionService(router wrouter.Router, impl ReligionService, routerParams ...wrouter.RouteParam) error {
	handler := religionServiceHandler{impl: impl}
	resource := wresource.New("religionservice", router)
	if err := resource.Get("ListTaxonRanks", "/religion/v1/taxon-ranks", httpserver.NewJSONHandler(handler.HandleListTaxonRanks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listTaxonRanks route")
	}
	if err := resource.Put("UpsertTaxonRank", "/religion/v1/taxon-ranks", httpserver.NewJSONHandler(handler.HandleUpsertTaxonRank, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertTaxonRank route")
	}
	if err := resource.Get("ListClassifications", "/religion/v1/classifications", httpserver.NewJSONHandler(handler.HandleListClassifications, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listClassifications route")
	}
	if err := resource.Put("UpsertClassification", "/religion/v1/classifications", httpserver.NewJSONHandler(handler.HandleUpsertClassification, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertClassification route")
	}
	if err := resource.Get("ListOrgKinds", "/religion/v1/org-kinds", httpserver.NewJSONHandler(handler.HandleListOrgKinds, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listOrgKinds route")
	}
	if err := resource.Put("UpsertOrgKind", "/religion/v1/org-kinds", httpserver.NewJSONHandler(handler.HandleUpsertOrgKind, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertOrgKind route")
	}
	if err := resource.Get("ListPolicyKinds", "/religion/v1/policy-kinds", httpserver.NewJSONHandler(handler.HandleListPolicyKinds, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPolicyKinds route")
	}
	if err := resource.Put("UpsertPolicyKind", "/religion/v1/policy-kinds", httpserver.NewJSONHandler(handler.HandleUpsertPolicyKind, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertPolicyKind route")
	}
	if err := resource.Get("ListTaxa", "/religion/v1/taxa", httpserver.NewJSONHandler(handler.HandleListTaxa, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listTaxa route")
	}
	if err := resource.Get("TaxonStats", "/religion/v1/stats/taxa", httpserver.NewJSONHandler(handler.HandleTaxonStats, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add taxonStats route")
	}
	if err := resource.Post("CreateTaxon", "/religion/v1/taxa", httpserver.NewJSONHandler(handler.HandleCreateTaxon, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createTaxon route")
	}
	if err := resource.Get("GetTaxon", "/religion/v1/taxa/{taxonId}", httpserver.NewJSONHandler(handler.HandleGetTaxon, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getTaxon route")
	}
	if err := resource.Put("UpdateTaxon", "/religion/v1/taxa/{taxonId}", httpserver.NewJSONHandler(handler.HandleUpdateTaxon, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateTaxon route")
	}
	if err := resource.Delete("DeleteTaxon", "/religion/v1/taxa/{taxonId}", httpserver.NewJSONHandler(handler.HandleDeleteTaxon, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteTaxon route")
	}
	if err := resource.Post("ReparentTaxon", "/religion/v1/taxa/{taxonId}/reparent", httpserver.NewJSONHandler(handler.HandleReparentTaxon, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add reparentTaxon route")
	}
	if err := resource.Post("RebuildClosure", "/religion/v1/taxonomy/rebuild-closure", httpserver.NewJSONHandler(handler.HandleRebuildClosure, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add rebuildClosure route")
	}
	if err := resource.Get("GetEffectiveClassifications", "/religion/v1/taxa/{taxonId}/effective-classifications", httpserver.NewJSONHandler(handler.HandleGetEffectiveClassifications, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getEffectiveClassifications route")
	}
	if err := resource.Put("SetTaxonClassifications", "/religion/v1/taxa/{taxonId}/classifications", httpserver.NewJSONHandler(handler.HandleSetTaxonClassifications, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add setTaxonClassifications route")
	}
	if err := resource.Get("GetOrgProfile", "/religion/v1/units/{unitId}/religion-profile", httpserver.NewJSONHandler(handler.HandleGetOrgProfile, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getOrgProfile route")
	}
	if err := resource.Put("SetOrgProfile", "/religion/v1/units/{unitId}/religion-profile", httpserver.NewJSONHandler(handler.HandleSetOrgProfile, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add setOrgProfile route")
	}
	if err := resource.Post("AddOrgClassification", "/religion/v1/units/{unitId}/classifications", httpserver.NewJSONHandler(handler.HandleAddOrgClassification, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add addOrgClassification route")
	}
	if err := resource.Delete("RemoveOrgClassification", "/religion/v1/units/{unitId}/classifications/{linkId}", httpserver.NewJSONHandler(handler.HandleRemoveOrgClassification, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add removeOrgClassification route")
	}
	if err := resource.Put("SetUnitTypeOverride", "/religion/v1/units/{unitId}/type-overrides", httpserver.NewJSONHandler(handler.HandleSetUnitTypeOverride, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add setUnitTypeOverride route")
	}
	if err := resource.Get("GetEffectiveType", "/religion/v1/units/{unitId}/effective-type", httpserver.NewJSONHandler(handler.HandleGetEffectiveType, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getEffectiveType route")
	}
	if err := resource.Get("ListOrgPolicies", "/religion/v1/units/{unitId}/religion-policies", httpserver.NewJSONHandler(handler.HandleListOrgPolicies, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listOrgPolicies route")
	}
	if err := resource.Post("AddOrgPolicy", "/religion/v1/units/{unitId}/religion-policies", httpserver.NewJSONHandler(handler.HandleAddOrgPolicy, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add addOrgPolicy route")
	}
	if err := resource.Delete("RemoveOrgPolicy", "/religion/v1/units/{unitId}/religion-policies/{policyId}", httpserver.NewJSONHandler(handler.HandleRemoveOrgPolicy, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add removeOrgPolicy route")
	}
	if err := resource.Post("CreateChildOrg", "/religion/v1/units/{unitId}/child-orgs", httpserver.NewJSONHandler(handler.HandleCreateChildOrg, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createChildOrg route")
	}
	if err := resource.Post("CreateRootOrg", "/religion/v1/religion-orgs", httpserver.NewJSONHandler(handler.HandleCreateRootOrg, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createRootOrg route")
	}
	if err := resource.Get("ListGradeCategories", "/religion/v1/grade-categories", httpserver.NewJSONHandler(handler.HandleListGradeCategories, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listGradeCategories route")
	}
	if err := resource.Put("UpsertGradeCategory", "/religion/v1/grade-categories", httpserver.NewJSONHandler(handler.HandleUpsertGradeCategory, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertGradeCategory route")
	}
	if err := resource.Get("ListClergyGrades", "/religion/v1/clergy-grades", httpserver.NewJSONHandler(handler.HandleListClergyGrades, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listClergyGrades route")
	}
	if err := resource.Put("UpsertClergyGrade", "/religion/v1/clergy-grades", httpserver.NewJSONHandler(handler.HandleUpsertClergyGrade, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertClergyGrade route")
	}
	if err := resource.Get("ListOfficeTypes", "/religion/v1/office-types", httpserver.NewJSONHandler(handler.HandleListOfficeTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listOfficeTypes route")
	}
	if err := resource.Put("UpsertOfficeType", "/religion/v1/office-types", httpserver.NewJSONHandler(handler.HandleUpsertOfficeType, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertOfficeType route")
	}
	if err := resource.Get("ListPersonClergyCredentials", "/religion/v1/persons/{personId}/clergy-credentials", httpserver.NewJSONHandler(handler.HandleListPersonClergyCredentials, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPersonClergyCredentials route")
	}
	if err := resource.Get("ListUnitClergyCredentials", "/religion/v1/units/{unitId}/clergy-credentials", httpserver.NewJSONHandler(handler.HandleListUnitClergyCredentials, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listUnitClergyCredentials route")
	}
	if err := resource.Post("AddClergyCredential", "/religion/v1/persons/{personId}/clergy-credentials", httpserver.NewJSONHandler(handler.HandleAddClergyCredential, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add addClergyCredential route")
	}
	if err := resource.Put("UpdateClergyCredential", "/religion/v1/clergy-credentials/{credentialId}", httpserver.NewJSONHandler(handler.HandleUpdateClergyCredential, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateClergyCredential route")
	}
	if err := resource.Get("ListAffiliationTypes", "/religion/v1/affiliation-types", httpserver.NewJSONHandler(handler.HandleListAffiliationTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listAffiliationTypes route")
	}
	if err := resource.Put("UpsertAffiliationType", "/religion/v1/affiliation-types", httpserver.NewJSONHandler(handler.HandleUpsertAffiliationType, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertAffiliationType route")
	}
	if err := resource.Get("ListPersonAffiliations", "/religion/v1/persons/{personId}/affiliations", httpserver.NewJSONHandler(handler.HandleListPersonAffiliations, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPersonAffiliations route")
	}
	if err := resource.Post("AddAffiliation", "/religion/v1/persons/{personId}/affiliations", httpserver.NewJSONHandler(handler.HandleAddAffiliation, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add addAffiliation route")
	}
	if err := resource.Put("UpdateAffiliation", "/religion/v1/affiliations/{affiliationId}", httpserver.NewJSONHandler(handler.HandleUpdateAffiliation, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateAffiliation route")
	}
	if err := resource.Delete("DeleteAffiliation", "/religion/v1/affiliations/{affiliationId}", httpserver.NewJSONHandler(handler.HandleDeleteAffiliation, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteAffiliation route")
	}
	if err := resource.Get("ListSiteTypes", "/religion/v1/site-types", httpserver.NewJSONHandler(handler.HandleListSiteTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listSiteTypes route")
	}
	if err := resource.Put("UpsertSiteType", "/religion/v1/site-types", httpserver.NewJSONHandler(handler.HandleUpsertSiteType, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertSiteType route")
	}
	if err := resource.Get("ListServiceTypes", "/religion/v1/service-types", httpserver.NewJSONHandler(handler.HandleListServiceTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listServiceTypes route")
	}
	if err := resource.Put("UpsertServiceType", "/religion/v1/service-types", httpserver.NewJSONHandler(handler.HandleUpsertServiceType, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertServiceType route")
	}
	if err := resource.Get("ListUnitSites", "/religion/v1/units/{unitId}/sites", httpserver.NewJSONHandler(handler.HandleListUnitSites, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listUnitSites route")
	}
	if err := resource.Post("CreateSite", "/religion/v1/units/{unitId}/sites", httpserver.NewJSONHandler(handler.HandleCreateSite, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createSite route")
	}
	if err := resource.Put("UpdateSite", "/religion/v1/sites/{siteId}", httpserver.NewJSONHandler(handler.HandleUpdateSite, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateSite route")
	}
	if err := resource.Delete("DeleteSite", "/religion/v1/sites/{siteId}", httpserver.NewJSONHandler(handler.HandleDeleteSite, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteSite route")
	}
	if err := resource.Get("ListSiteSchedules", "/religion/v1/sites/{siteId}/schedules", httpserver.NewJSONHandler(handler.HandleListSiteSchedules, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listSiteSchedules route")
	}
	if err := resource.Post("CreateSchedule", "/religion/v1/sites/{siteId}/schedules", httpserver.NewJSONHandler(handler.HandleCreateSchedule, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createSchedule route")
	}
	if err := resource.Delete("DeleteSchedule", "/religion/v1/schedules/{scheduleId}", httpserver.NewJSONHandler(handler.HandleDeleteSchedule, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteSchedule route")
	}
	if err := resource.Get("ListUnitAliases", "/religion/v1/units/{unitId}/aliases", httpserver.NewJSONHandler(handler.HandleListUnitAliases, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listUnitAliases route")
	}
	if err := resource.Post("CreateAlias", "/religion/v1/units/{unitId}/aliases", httpserver.NewJSONHandler(handler.HandleCreateAlias, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createAlias route")
	}
	if err := resource.Delete("DeleteAlias", "/religion/v1/units/{unitId}/aliases/{aliasId}", httpserver.NewJSONHandler(handler.HandleDeleteAlias, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteAlias route")
	}
	if err := resource.Get("SearchSites", "/religion/v1/discovery/sites", httpserver.NewJSONHandler(handler.HandleSearchSites, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add searchSites route")
	}
	return nil
}

type religionServiceHandler struct {
	impl ReligionService
}

func (r *religionServiceHandler) HandleListTaxonRanks(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListTaxonRanks(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertTaxonRank(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertTaxonRankRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertTaxonRank(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListClassifications(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListClassifications(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertClassification(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertClassificationRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertClassification(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListOrgKinds(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListOrgKinds(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertOrgKind(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertOrgKindRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertOrgKind(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListPolicyKinds(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListPolicyKinds(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertPolicyKind(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertPolicyKindRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertPolicyKind(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListTaxa(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var rankArg *string
	if rankArgStr := req.URL.Query().Get("rank"); rankArgStr != "" {
		rankArgInternal := rankArgStr
		rankArg = &rankArgInternal
	}
	var parentArg *string
	if parentArgStr := req.URL.Query().Get("parent"); parentArgStr != "" {
		parentArgInternal := parentArgStr
		parentArg = &parentArgInternal
	}
	var religionArg *string
	if religionArgStr := req.URL.Query().Get("religion"); religionArgStr != "" {
		religionArgInternal := religionArgStr
		religionArg = &religionArgInternal
	}
	var classificationArg *string
	if classificationArgStr := req.URL.Query().Get("classification"); classificationArgStr != "" {
		classificationArgInternal := classificationArgStr
		classificationArg = &classificationArgInternal
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var pageSizeArg *int
	if pageSizeArgStr := req.URL.Query().Get("pageSize"); pageSizeArgStr != "" {
		pageSizeArgInternal, err := strconv.Atoi(pageSizeArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"pageSize\" as integer")
		}
		pageSizeArg = &pageSizeArgInternal
	}
	var pageTokenArg *string
	if pageTokenArgStr := req.URL.Query().Get("pageToken"); pageTokenArgStr != "" {
		pageTokenArgInternal := pageTokenArgStr
		pageTokenArg = &pageTokenArgInternal
	}
	respArg, err := r.impl.ListTaxa(req.Context(), bearertoken.Token(authHeader), rankArg, parentArg, religionArg, classificationArg, queryArg, pageSizeArg, pageTokenArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleTaxonStats(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var facetsArg *string
	if facetsArgStr := req.URL.Query().Get("facets"); facetsArgStr != "" {
		facetsArgInternal := facetsArgStr
		facetsArg = &facetsArgInternal
	}
	var rankArg *string
	if rankArgStr := req.URL.Query().Get("rank"); rankArgStr != "" {
		rankArgInternal := rankArgStr
		rankArg = &rankArgInternal
	}
	var parentArg *string
	if parentArgStr := req.URL.Query().Get("parent"); parentArgStr != "" {
		parentArgInternal := parentArgStr
		parentArg = &parentArgInternal
	}
	var religionArg *string
	if religionArgStr := req.URL.Query().Get("religion"); religionArgStr != "" {
		religionArgInternal := religionArgStr
		religionArg = &religionArgInternal
	}
	var classificationArg *string
	if classificationArgStr := req.URL.Query().Get("classification"); classificationArgStr != "" {
		classificationArgInternal := classificationArgStr
		classificationArg = &classificationArgInternal
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	respArg, err := r.impl.TaxonStats(req.Context(), bearertoken.Token(authHeader), facetsArg, rankArg, parentArg, religionArg, classificationArg, queryArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleCreateTaxon(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateTaxonRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.CreateTaxon(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleGetTaxon(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	taxonIdArg, ok := pathParams["taxonId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"taxonId\" not present")
	}
	respArg, err := r.impl.GetTaxon(req.Context(), bearertoken.Token(authHeader), taxonIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpdateTaxon(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	taxonIdArg, ok := pathParams["taxonId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"taxonId\" not present")
	}
	var requestArg UpdateTaxonRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpdateTaxon(req.Context(), bearertoken.Token(authHeader), taxonIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleDeleteTaxon(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	taxonIdArg, ok := pathParams["taxonId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"taxonId\" not present")
	}
	if err := r.impl.DeleteTaxon(req.Context(), bearertoken.Token(authHeader), taxonIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (r *religionServiceHandler) HandleReparentTaxon(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	taxonIdArg, ok := pathParams["taxonId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"taxonId\" not present")
	}
	var requestArg ReparentTaxonRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.ReparentTaxon(req.Context(), bearertoken.Token(authHeader), taxonIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleRebuildClosure(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.RebuildClosure(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleGetEffectiveClassifications(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	taxonIdArg, ok := pathParams["taxonId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"taxonId\" not present")
	}
	respArg, err := r.impl.GetEffectiveClassifications(req.Context(), bearertoken.Token(authHeader), taxonIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleSetTaxonClassifications(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	taxonIdArg, ok := pathParams["taxonId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"taxonId\" not present")
	}
	var requestArg SetClassificationsRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.SetTaxonClassifications(req.Context(), bearertoken.Token(authHeader), taxonIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleGetOrgProfile(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := r.impl.GetOrgProfile(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleSetOrgProfile(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg SetOrgProfileRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.SetOrgProfile(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleAddOrgClassification(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg AddOrgClassificationRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.AddOrgClassification(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleRemoveOrgClassification(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	linkIdArg, ok := pathParams["linkId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"linkId\" not present")
	}
	if err := r.impl.RemoveOrgClassification(req.Context(), bearertoken.Token(authHeader), unitIdArg, linkIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (r *religionServiceHandler) HandleSetUnitTypeOverride(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg SetClassificationsRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.SetUnitTypeOverride(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleGetEffectiveType(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := r.impl.GetEffectiveType(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListOrgPolicies(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := r.impl.ListOrgPolicies(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleAddOrgPolicy(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg AddOrgPolicyRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.AddOrgPolicy(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleRemoveOrgPolicy(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	policyIdArg, ok := pathParams["policyId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"policyId\" not present")
	}
	if err := r.impl.RemoveOrgPolicy(req.Context(), bearertoken.Token(authHeader), unitIdArg, policyIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (r *religionServiceHandler) HandleCreateChildOrg(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg CreateChildOrgRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.CreateChildOrg(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleCreateRootOrg(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateRootOrgRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.CreateRootOrg(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListGradeCategories(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListGradeCategories(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertGradeCategory(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertGradeCategoryRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertGradeCategory(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListClergyGrades(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var traditionArg *string
	if traditionArgStr := req.URL.Query().Get("tradition"); traditionArgStr != "" {
		traditionArgInternal := traditionArgStr
		traditionArg = &traditionArgInternal
	}
	respArg, err := r.impl.ListClergyGrades(req.Context(), bearertoken.Token(authHeader), traditionArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertClergyGrade(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertClergyGradeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertClergyGrade(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListOfficeTypes(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListOfficeTypes(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertOfficeType(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertOfficeTypeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertOfficeType(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListPersonClergyCredentials(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	respArg, err := r.impl.ListPersonClergyCredentials(req.Context(), bearertoken.Token(authHeader), personIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListUnitClergyCredentials(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := r.impl.ListUnitClergyCredentials(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleAddClergyCredential(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	var requestArg AddClergyCredentialRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.AddClergyCredential(req.Context(), bearertoken.Token(authHeader), personIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpdateClergyCredential(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	credentialIdArg, ok := pathParams["credentialId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"credentialId\" not present")
	}
	var requestArg UpdateClergyCredentialRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpdateClergyCredential(req.Context(), bearertoken.Token(authHeader), credentialIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListAffiliationTypes(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListAffiliationTypes(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertAffiliationType(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertAffiliationTypeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertAffiliationType(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListPersonAffiliations(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	respArg, err := r.impl.ListPersonAffiliations(req.Context(), bearertoken.Token(authHeader), personIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleAddAffiliation(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	var requestArg AddAffiliationRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.AddAffiliation(req.Context(), bearertoken.Token(authHeader), personIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpdateAffiliation(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	affiliationIdArg, ok := pathParams["affiliationId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"affiliationId\" not present")
	}
	var requestArg UpdateAffiliationRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpdateAffiliation(req.Context(), bearertoken.Token(authHeader), affiliationIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleDeleteAffiliation(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	affiliationIdArg, ok := pathParams["affiliationId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"affiliationId\" not present")
	}
	if err := r.impl.DeleteAffiliation(req.Context(), bearertoken.Token(authHeader), affiliationIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (r *religionServiceHandler) HandleListSiteTypes(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListSiteTypes(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertSiteType(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertSiteTypeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertSiteType(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListServiceTypes(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := r.impl.ListServiceTypes(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpsertServiceType(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertServiceTypeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpsertServiceType(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleListUnitSites(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := r.impl.ListUnitSites(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleCreateSite(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg CreateSiteRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.CreateSite(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleUpdateSite(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var requestArg UpdateSiteRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.UpdateSite(req.Context(), bearertoken.Token(authHeader), siteIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleDeleteSite(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	if err := r.impl.DeleteSite(req.Context(), bearertoken.Token(authHeader), siteIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (r *religionServiceHandler) HandleListSiteSchedules(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	respArg, err := r.impl.ListSiteSchedules(req.Context(), bearertoken.Token(authHeader), siteIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleCreateSchedule(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var requestArg CreateScheduleRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.CreateSchedule(req.Context(), bearertoken.Token(authHeader), siteIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleDeleteSchedule(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	scheduleIdArg, ok := pathParams["scheduleId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"scheduleId\" not present")
	}
	if err := r.impl.DeleteSchedule(req.Context(), bearertoken.Token(authHeader), scheduleIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (r *religionServiceHandler) HandleListUnitAliases(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := r.impl.ListUnitAliases(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleCreateAlias(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	var requestArg CreateAliasRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.CreateAlias(req.Context(), bearertoken.Token(authHeader), unitIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *religionServiceHandler) HandleDeleteAlias(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	aliasIdArg, ok := pathParams["aliasId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"aliasId\" not present")
	}
	if err := r.impl.DeleteAlias(req.Context(), bearertoken.Token(authHeader), unitIdArg, aliasIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (r *religionServiceHandler) HandleSearchSites(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var latArg *float64
	if latArgStr := req.URL.Query().Get("lat"); latArgStr != "" {
		latArgInternal, err := strconv.ParseFloat(latArgStr, 64)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"lat\" as double")
		}
		latArg = &latArgInternal
	}
	var lngArg *float64
	if lngArgStr := req.URL.Query().Get("lng"); lngArgStr != "" {
		lngArgInternal, err := strconv.ParseFloat(lngArgStr, 64)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"lng\" as double")
		}
		lngArg = &lngArgInternal
	}
	var radiusMArg *float64
	if radiusMArgStr := req.URL.Query().Get("radiusM"); radiusMArgStr != "" {
		radiusMArgInternal, err := strconv.ParseFloat(radiusMArgStr, 64)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"radiusM\" as double")
		}
		radiusMArg = &radiusMArgInternal
	}
	var minLatArg *float64
	if minLatArgStr := req.URL.Query().Get("minLat"); minLatArgStr != "" {
		minLatArgInternal, err := strconv.ParseFloat(minLatArgStr, 64)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"minLat\" as double")
		}
		minLatArg = &minLatArgInternal
	}
	var minLngArg *float64
	if minLngArgStr := req.URL.Query().Get("minLng"); minLngArgStr != "" {
		minLngArgInternal, err := strconv.ParseFloat(minLngArgStr, 64)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"minLng\" as double")
		}
		minLngArg = &minLngArgInternal
	}
	var maxLatArg *float64
	if maxLatArgStr := req.URL.Query().Get("maxLat"); maxLatArgStr != "" {
		maxLatArgInternal, err := strconv.ParseFloat(maxLatArgStr, 64)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"maxLat\" as double")
		}
		maxLatArg = &maxLatArgInternal
	}
	var maxLngArg *float64
	if maxLngArgStr := req.URL.Query().Get("maxLng"); maxLngArgStr != "" {
		maxLngArgInternal, err := strconv.ParseFloat(maxLngArgStr, 64)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"maxLng\" as double")
		}
		maxLngArg = &maxLngArgInternal
	}
	var religionArg *string
	if religionArgStr := req.URL.Query().Get("religion"); religionArgStr != "" {
		religionArgInternal := religionArgStr
		religionArg = &religionArgInternal
	}
	var languageArg *string
	if languageArgStr := req.URL.Query().Get("language"); languageArgStr != "" {
		languageArgInternal := languageArgStr
		languageArg = &languageArgInternal
	}
	var dayOfWeekArg *int
	if dayOfWeekArgStr := req.URL.Query().Get("dayOfWeek"); dayOfWeekArgStr != "" {
		dayOfWeekArgInternal, err := strconv.Atoi(dayOfWeekArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"dayOfWeek\" as integer")
		}
		dayOfWeekArg = &dayOfWeekArgInternal
	}
	var onlineOnlyArg *bool
	if onlineOnlyArgStr := req.URL.Query().Get("onlineOnly"); onlineOnlyArgStr != "" {
		onlineOnlyArgInternal, err := strconv.ParseBool(onlineOnlyArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"onlineOnly\" as boolean")
		}
		onlineOnlyArg = &onlineOnlyArgInternal
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var pageSizeArg *int
	if pageSizeArgStr := req.URL.Query().Get("pageSize"); pageSizeArgStr != "" {
		pageSizeArgInternal, err := strconv.Atoi(pageSizeArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"pageSize\" as integer")
		}
		pageSizeArg = &pageSizeArgInternal
	}
	respArg, err := r.impl.SearchSites(req.Context(), bearertoken.Token(authHeader), latArg, lngArg, radiusMArg, minLatArg, minLngArg, maxLatArg, maxLngArg, religionArg, languageArg, dayOfWeekArg, onlineOnlyArg, queryArg, pageSizeArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}
