// Code generated by conjure-go. DO NOT EDIT.

package membership

import (
	"github.com/palantir/pkg/datetime"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

// Add a person's belonging to a unit, optionally filling a position. The position (if given) must belong to the unit.
type CreateMembershipRequest struct {
	PersonId string `json:"personId"`
	UnitId   string `json:"unitId"`
	// The position to fill; omit for plain belonging.
	PositionId *string `json:"positionId,omitempty"`
	// Optional provenance pointer to the authorizing order item (D-Orders).
	OrderItemId *string `json:"orderItemId,omitempty"`
	// When the membership takes effect; defaults to now.
	EffectiveFrom *datetime.DateTime `json:"effectiveFrom,omitempty"`
}

func (o CreateMembershipRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateMembershipRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Create a billet in a unit (vacant). The title is the default-locale fallback; additional locales are set via LocalizationService.
type CreatePositionRequest struct {
	Code string `json:"code"`
	// The default-locale title (the i18n fallback); translatable separately.
	Title          string  `json:"title"`
	RequiredRankId *string `json:"requiredRankId,omitempty"`
	SortOrder      *int    `json:"sortOrder,omitempty"`
}

func (o CreatePositionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreatePositionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// End a membership, vacating any filled billet (reversible status flip + effectiveTo).
type EndMembershipRequest struct {
	// When the membership ended; defaults to now.
	EffectiveTo *datetime.DateTime `json:"effectiveTo,omitempty"`
	// Optional provenance pointer to the authorizing order item (D-Orders).
	OrderItemId *string `json:"orderItemId,omitempty"`
}

func (o EndMembershipRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *EndMembershipRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Fill a vacant position with a person (a membership referencing the position; its unit is the position's unit).
type FillPositionRequest struct {
	PersonId      string             `json:"personId"`
	OrderItemId   *string            `json:"orderItemId,omitempty"`
	EffectiveFrom *datetime.DateTime `json:"effectiveFrom,omitempty"`
}

func (o FillPositionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *FillPositionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
A person's belonging to a unit (the reified link__member_of), effective-dated, optionally
filling a position. A position-less membership is plain belonging. Reversible: ending flips
status and sets effectiveTo rather than deleting, vacating any filled billet.
*/
type Membership struct {
	// The membership's URN RID (carried as a plain string).
	Id string `json:"id"`
	// The URN RID of the person who belongs / fills.
	PersonId string `json:"personId"`
	// The URN RID of the unit belonged to.
	UnitId string `json:"unitId"`
	// The URN RID of the position this membership fills; null for plain belonging.
	PositionId *string `json:"positionId,omitempty"`
	// Provenance — the order (наказ) item that authorized this fill/belonging (D-Orders); null when created without an order.
	OrderItemId *string `json:"orderItemId,omitempty"`
	// One of active | ended.
	Status        string            `json:"status"`
	EffectiveFrom datetime.DateTime `json:"effectiveFrom"`
	// When the membership ended; null while active.
	EffectiveTo *datetime.DateTime `json:"effectiveTo,omitempty"`
	CreatedAt   datetime.DateTime  `json:"createdAt"`
	UpdatedAt   datetime.DateTime  `json:"updatedAt"`
}

func (o Membership) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Membership) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A page of memberships plus the opaque token for the next page (empty when exhausted).
type MembershipPage struct {
	Memberships   []Membership `json:"memberships"`
	NextPageToken *string      `json:"nextPageToken,omitempty"`
}

func (o MembershipPage) MarshalJSON() ([]byte, error) {
	if o.Memberships == nil {
		o.Memberships = make([]Membership, 0)
	}
	type _tmpMembershipPage MembershipPage
	return safejson.Marshal(_tmpMembershipPage(o))
}

func (o *MembershipPage) UnmarshalJSON(data []byte) error {
	type _tmpMembershipPage MembershipPage
	var rawMembershipPage _tmpMembershipPage
	if err := safejson.Unmarshal(data, &rawMembershipPage); err != nil {
		return err
	}
	if rawMembershipPage.Memberships == nil {
		rawMembershipPage.Memberships = make([]Membership, 0)
	}
	*o = MembershipPage(rawMembershipPage)
	return nil
}

func (o MembershipPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *MembershipPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
A unit-owned billet (D-Position) — an Object that exists whether or not anyone fills it (a
VACANCY is an active position with no active filling). Position grants no authority. The
current holder is populated by getPosition and is null in list responses.
*/
type Position struct {
	// The position's URN RID (carried as a plain string).
	Id string `json:"id"`
	// The URN RID of the owning unit.
	UnitId string `json:"unitId"`
	// Stable, locale-agnostic identifier, unique within the unit; immutable by convention.
	Code string `json:"code"`
	// The billet title as a locale -> text map (default-locale fallback + i18n translations).
	Title map[string]string `json:"title"`
	// Optional advisory establishment rank (a rank RID); never enforced against any filler.
	RequiredRankId *string `json:"requiredRankId,omitempty"`
	// One of active | abolished (abolish is a reversible status flip).
	Status string `json:"status"`
	// App-managed display order within the unit.
	SortOrder *int `json:"sortOrder,omitempty"`
	// The current active filling, if any. Populated by getPosition; null in list responses.
	Holder    *Membership       `json:"holder,omitempty"`
	CreatedAt datetime.DateTime `json:"createdAt"`
	UpdatedAt datetime.DateTime `json:"updatedAt"`
}

func (o Position) MarshalJSON() ([]byte, error) {
	if o.Title == nil {
		o.Title = make(map[string]string)
	}
	type _tmpPosition Position
	return safejson.Marshal(_tmpPosition(o))
}

func (o *Position) UnmarshalJSON(data []byte) error {
	type _tmpPosition Position
	var rawPosition _tmpPosition
	if err := safejson.Unmarshal(data, &rawPosition); err != nil {
		return err
	}
	if rawPosition.Title == nil {
		rawPosition.Title = make(map[string]string)
	}
	*o = Position(rawPosition)
	return nil
}

func (o Position) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Position) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A page of positions plus the opaque token for the next page (empty when exhausted).
type PositionPage struct {
	Positions     []Position `json:"positions"`
	NextPageToken *string    `json:"nextPageToken,omitempty"`
}

func (o PositionPage) MarshalJSON() ([]byte, error) {
	if o.Positions == nil {
		o.Positions = make([]Position, 0)
	}
	type _tmpPositionPage PositionPage
	return safejson.Marshal(_tmpPositionPage(o))
}

func (o *PositionPage) UnmarshalJSON(data []byte) error {
	type _tmpPositionPage PositionPage
	var rawPositionPage _tmpPositionPage
	if err := safejson.Unmarshal(data, &rawPositionPage); err != nil {
		return err
	}
	if rawPositionPage.Positions == nil {
		rawPositionPage.Positions = make([]Position, 0)
	}
	*o = PositionPage(rawPositionPage)
	return nil
}

func (o PositionPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *PositionPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Update a position's title / required rank / sort order. `code` and unit are immutable. Omitted fields are unchanged.
type UpdatePositionRequest struct {
	Title *string `json:"title,omitempty"`
	// Set the advisory required rank; omitted leaves it unchanged (clearing it is an open seam).
	RequiredRankId *string `json:"requiredRankId,omitempty"`
	SortOrder      *int    `json:"sortOrder,omitempty"`
}

func (o UpdatePositionRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdatePositionRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
