// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package tenantsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultGraphs = `-- name: ClearDefaultGraphs :exec
UPDATE oikumenea.tenant_graphs SET is_default = false WHERE is_default AND deleted_at IS NULL
`

// Unset is_default on every active graph (run before promoting a new default).
func (q *Queries) ClearDefaultGraphs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultGraphs)
	return err
}

const closureHasPath = `-- name: ClosureHasPath :one

SELECT EXISTS(
  SELECT 1 FROM oikumenea.tenant_unit_closure
  WHERE graph_id = $1 AND ancestor_id = $2 AND descendant_id = $3
) AS reachable
`

type ClosureHasPathParams struct {
	GraphID      string
	AncestorID   string
	DescendantID string
}

// ============================ closure ============================
// Is `ancestor_id` an ancestor of `descendant_id` in this graph? Used for the cycle guard
// (a new parent->child edge is a cycle iff the child already reaches the parent).
func (q *Queries) ClosureHasPath(ctx context.Context, arg ClosureHasPathParams) (bool, error) {
	row := q.db.QueryRow(ctx, closureHasPath, arg.GraphID, arg.AncestorID, arg.DescendantID)
	var reachable bool
	err := row.Scan(&reachable)
	return reachable, err
}

const countActiveGraphs = `-- name: CountActiveGraphs :one
SELECT count(*)::int AS active_count FROM oikumenea.tenant_graphs WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveGraphs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveGraphs)
	var active_count int32
	err := row.Scan(&active_count)
	return active_count, err
}

const deleteClosureForGraph = `-- name: DeleteClosureForGraph :exec
DELETE FROM oikumenea.tenant_unit_closure WHERE graph_id = $1
`

func (q *Queries) DeleteClosureForGraph(ctx context.Context, graphID string) error {
	_, err := q.db.Exec(ctx, deleteClosureForGraph, graphID)
	return err
}

const deleteEdge = `-- name: DeleteEdge :execrows
DELETE FROM oikumenea.tenant_unit_edges
WHERE graph_id = $1 AND parent_id = $2 AND child_id = $3
`

type DeleteEdgeParams struct {
	GraphID  string
	ParentID string
	ChildID  string
}

func (q *Queries) DeleteEdge(ctx context.Context, arg DeleteEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEdge, arg.GraphID, arg.ParentID, arg.ChildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGraphByCode = `-- name: GetGraphByCode :one
SELECT id, code, name, is_default, is_authority_bearing, created_at, updated_at, deleted_at FROM oikumenea.tenant_graphs WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGraphByCode(ctx context.Context, code string) (OikumeneaTenantGraph, error) {
	row := q.db.QueryRow(ctx, getGraphByCode, code)
	var i OikumeneaTenantGraph
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.IsAuthorityBearing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGraphByID = `-- name: GetGraphByID :one
SELECT id, code, name, is_default, is_authority_bearing, created_at, updated_at, deleted_at FROM oikumenea.tenant_graphs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGraphByID(ctx context.Context, id string) (OikumeneaTenantGraph, error) {
	row := q.db.QueryRow(ctx, getGraphByID, id)
	var i OikumeneaTenantGraph
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.IsAuthorityBearing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, code, name, unit_kind, level, visibility, state, metadata, created_at, updated_at, deleted_at FROM oikumenea.tenant_units WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUnit(ctx context.Context, id string) (OikumeneaTenantUnit, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i OikumeneaTenantUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UnitKind,
		&i.Level,
		&i.Visibility,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const graphHasLiveEdges = `-- name: GraphHasLiveEdges :one
SELECT EXISTS(
  SELECT 1 FROM oikumenea.tenant_unit_edges WHERE graph_id = $1
) AS has_edges
`

func (q *Queries) GraphHasLiveEdges(ctx context.Context, graphID string) (bool, error) {
	row := q.db.QueryRow(ctx, graphHasLiveEdges, graphID)
	var has_edges bool
	err := row.Scan(&has_edges)
	return has_edges, err
}

const insertEdge = `-- name: InsertEdge :one

INSERT INTO oikumenea.tenant_unit_edges (graph_id, parent_id, child_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, graph_id, parent_id, child_id, created_at, created_by
`

type InsertEdgeParams struct {
	GraphID   string
	ParentID  string
	ChildID   string
	CreatedBy pgtype.Text
}

// ============================ edges ============================
func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) (OikumeneaTenantUnitEdge, error) {
	row := q.db.QueryRow(ctx, insertEdge,
		arg.GraphID,
		arg.ParentID,
		arg.ChildID,
		arg.CreatedBy,
	)
	var i OikumeneaTenantUnitEdge
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.ParentID,
		&i.ChildID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertGraph = `-- name: InsertGraph :one

INSERT INTO oikumenea.tenant_graphs (code, name, is_authority_bearing)
VALUES ($1, $2, $3)
RETURNING id, code, name, is_default, is_authority_bearing, created_at, updated_at, deleted_at
`

type InsertGraphParams struct {
	Code               string
	Name               string
	IsAuthorityBearing bool
}

// ============================ graphs ============================
func (q *Queries) InsertGraph(ctx context.Context, arg InsertGraphParams) (OikumeneaTenantGraph, error) {
	row := q.db.QueryRow(ctx, insertGraph, arg.Code, arg.Name, arg.IsAuthorityBearing)
	var i OikumeneaTenantGraph
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.IsAuthorityBearing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertLifecycleEvent = `-- name: InsertLifecycleEvent :exec

INSERT INTO oikumenea.tenant_unit_lifecycle_events
  (unit_id, from_state, to_state, reason, actor_person_id, request_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLifecycleEventParams struct {
	UnitID        string
	FromState     string
	ToState       string
	Reason        pgtype.Text
	ActorPersonID pgtype.Text
	RequestID     string
}

// ============================ lifecycle ============================
func (q *Queries) InsertLifecycleEvent(ctx context.Context, arg InsertLifecycleEventParams) error {
	_, err := q.db.Exec(ctx, insertLifecycleEvent,
		arg.UnitID,
		arg.FromState,
		arg.ToState,
		arg.Reason,
		arg.ActorPersonID,
		arg.RequestID,
	)
	return err
}

const insertUnit = `-- name: InsertUnit :one


INSERT INTO oikumenea.tenant_units (code, name, unit_kind, level, visibility, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, name, unit_kind, level, visibility, state, metadata, created_at, updated_at, deleted_at
`

type InsertUnitParams struct {
	Code       string
	Name       string
	UnitKind   pgtype.Text
	Level      pgtype.Int2
	Visibility string
	Metadata   []byte
}

// Tenant module queries (docs/modules/tenant.md). Units as a DAG per graph + a maintained
// transitive closure recomputed in the write transaction on every edge change. Units/graphs
// soft-delete; edges hard-delete on detach; the closure is derived (no RID).
// ============================ units ============================
// Create a unit. The RID PK defaults at the database; the partial-unique code guards duplicates.
func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) (OikumeneaTenantUnit, error) {
	row := q.db.QueryRow(ctx, insertUnit,
		arg.Code,
		arg.Name,
		arg.UnitKind,
		arg.Level,
		arg.Visibility,
		arg.Metadata,
	)
	var i OikumeneaTenantUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UnitKind,
		&i.Level,
		&i.Visibility,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAncestors = `-- name: ListAncestors :many
SELECT u.id, u.code, u.name, u.visibility, c.depth
FROM oikumenea.tenant_unit_closure c
JOIN oikumenea.tenant_units u ON u.id = c.ancestor_id AND u.deleted_at IS NULL
WHERE c.graph_id = $1 AND c.descendant_id = $2 AND c.depth > 0
ORDER BY c.depth, u.code
`

type ListAncestorsParams struct {
	GraphID string
	UnitID  string
}

type ListAncestorsRow struct {
	ID         string
	Code       string
	Name       string
	Visibility string
	Depth      int32
}

// Ancestors of @unit_id in @graph_id (strict; excludes self), nearest first.
func (q *Queries) ListAncestors(ctx context.Context, arg ListAncestorsParams) ([]ListAncestorsRow, error) {
	rows, err := q.db.Query(ctx, listAncestors, arg.GraphID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAncestorsRow
	for rows.Next() {
		var i ListAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Visibility,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDescendants = `-- name: ListDescendants :many
SELECT u.id, u.code, u.name, u.visibility, c.depth
FROM oikumenea.tenant_unit_closure c
JOIN oikumenea.tenant_units u ON u.id = c.descendant_id AND u.deleted_at IS NULL
WHERE c.graph_id = $1 AND c.ancestor_id = $2 AND c.depth > 0
  AND ($3::text IS NULL OR c.descendant_id > $3::text)
ORDER BY c.descendant_id
LIMIT $4
`

type ListDescendantsParams struct {
	GraphID string
	UnitID  string
	After   pgtype.Text
	Lim     int32
}

type ListDescendantsRow struct {
	ID         string
	Code       string
	Name       string
	Visibility string
	Depth      int32
}

// The subtree of @unit_id in @graph_id (strict; excludes self), keyset-paginated by descendant id.
func (q *Queries) ListDescendants(ctx context.Context, arg ListDescendantsParams) ([]ListDescendantsRow, error) {
	rows, err := q.db.Query(ctx, listDescendants,
		arg.GraphID,
		arg.UnitID,
		arg.After,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDescendantsRow
	for rows.Next() {
		var i ListDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Visibility,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphs = `-- name: ListGraphs :many
SELECT id, code, name, is_default, is_authority_bearing, created_at, updated_at, deleted_at FROM oikumenea.tenant_graphs WHERE deleted_at IS NULL ORDER BY created_at, code
`

func (q *Queries) ListGraphs(ctx context.Context) ([]OikumeneaTenantGraph, error) {
	rows, err := q.db.Query(ctx, listGraphs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaTenantGraph
	for rows.Next() {
		var i OikumeneaTenantGraph
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsDefault,
			&i.IsAuthorityBearing,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, code, name, unit_kind, level, visibility, state, metadata, created_at, updated_at, deleted_at FROM oikumenea.tenant_units
WHERE deleted_at IS NULL
  AND ($1::smallint IS NULL OR level = $1::smallint)
  AND ($2::text IS NULL OR id > $2::text)
ORDER BY id
LIMIT $3
`

type ListUnitsParams struct {
	Level pgtype.Int2
	After pgtype.Text
	Lim   int32
}

// Keyset pagination over the time-ordered RID (id), optional level filter.
func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]OikumeneaTenantUnit, error) {
	rows, err := q.db.Query(ctx, listUnits, arg.Level, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OikumeneaTenantUnit
	for rows.Next() {
		var i OikumeneaTenantUnit
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.UnitKind,
			&i.Level,
			&i.Visibility,
			&i.State,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildClosureForGraph = `-- name: RebuildClosureForGraph :exec
WITH RECURSIVE
  nodes AS (
    SELECT parent_id AS u FROM oikumenea.tenant_unit_edges WHERE graph_id = $1
    UNION
    SELECT child_id FROM oikumenea.tenant_unit_edges WHERE graph_id = $1
  ),
  reach AS (
    SELECT u AS ancestor_id, u AS descendant_id, 0 AS depth FROM nodes
    UNION ALL
    SELECT r.ancestor_id, e.child_id, r.depth + 1
    FROM reach r
    JOIN oikumenea.tenant_unit_edges e
      ON e.graph_id = $1 AND e.parent_id = r.descendant_id
  )
INSERT INTO oikumenea.tenant_unit_closure (graph_id, ancestor_id, descendant_id, depth)
SELECT $1::text, ancestor_id, descendant_id, min(depth)::int
FROM reach
GROUP BY ancestor_id, descendant_id
`

// Recompute one graph's full transitive closure from its edges, in the caller's transaction.
// Reflexive (g,u,u,0) rows for every unit appearing in the graph's edges, then descend; collapse
// multi-path DAG depths to the shortest with MIN(depth). Cycle-free by construction (guarded).
func (q *Queries) RebuildClosureForGraph(ctx context.Context, graphID string) error {
	_, err := q.db.Exec(ctx, rebuildClosureForGraph, graphID)
	return err
}

const setUnitState = `-- name: SetUnitState :one
UPDATE oikumenea.tenant_units SET state = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, code, name, unit_kind, level, visibility, state, metadata, created_at, updated_at, deleted_at
`

type SetUnitStateParams struct {
	State string
	ID    string
}

func (q *Queries) SetUnitState(ctx context.Context, arg SetUnitStateParams) (OikumeneaTenantUnit, error) {
	row := q.db.QueryRow(ctx, setUnitState, arg.State, arg.ID)
	var i OikumeneaTenantUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UnitKind,
		&i.Level,
		&i.Visibility,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteGraph = `-- name: SoftDeleteGraph :one
UPDATE oikumenea.tenant_graphs SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, is_default, is_authority_bearing, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteGraph(ctx context.Context, id string) (OikumeneaTenantGraph, error) {
	row := q.db.QueryRow(ctx, softDeleteGraph, id)
	var i OikumeneaTenantGraph
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.IsAuthorityBearing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGraph = `-- name: UpdateGraph :one
UPDATE oikumenea.tenant_graphs SET
  name                 = COALESCE($1, name),
  is_default           = COALESCE($2, is_default),
  is_authority_bearing = COALESCE($3, is_authority_bearing)
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, code, name, is_default, is_authority_bearing, created_at, updated_at, deleted_at
`

type UpdateGraphParams struct {
	Name               pgtype.Text
	IsDefault          pgtype.Bool
	IsAuthorityBearing pgtype.Bool
	ID                 string
}

func (q *Queries) UpdateGraph(ctx context.Context, arg UpdateGraphParams) (OikumeneaTenantGraph, error) {
	row := q.db.QueryRow(ctx, updateGraph,
		arg.Name,
		arg.IsDefault,
		arg.IsAuthorityBearing,
		arg.ID,
	)
	var i OikumeneaTenantGraph
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.IsAuthorityBearing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE oikumenea.tenant_units SET
  name       = COALESCE($1, name),
  unit_kind  = COALESCE($2, unit_kind),
  level      = COALESCE($3, level),
  visibility = COALESCE($4, visibility),
  metadata   = COALESCE($5, metadata)
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, code, name, unit_kind, level, visibility, state, metadata, created_at, updated_at, deleted_at
`

type UpdateUnitParams struct {
	Name       pgtype.Text
	UnitKind   pgtype.Text
	Level      pgtype.Int2
	Visibility pgtype.Text
	Metadata   []byte
	ID         string
}

// Partial update: a NULL narg leaves the stored value unchanged (COALESCE). `code` is immutable.
func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (OikumeneaTenantUnit, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.Name,
		arg.UnitKind,
		arg.Level,
		arg.Visibility,
		arg.Metadata,
		arg.ID,
	)
	var i OikumeneaTenantUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UnitKind,
		&i.Level,
		&i.Visibility,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertClosureStatus = `-- name: UpsertClosureStatus :exec
INSERT INTO oikumenea.tenant_closure_status (graph_id, last_checked_at, missing_count, extra_count, in_drift, sample)
VALUES ($1, now(), $2, $3, $4, $5)
ON CONFLICT (graph_id) DO UPDATE SET
  last_checked_at = now(),
  missing_count   = EXCLUDED.missing_count,
  extra_count     = EXCLUDED.extra_count,
  in_drift        = EXCLUDED.in_drift,
  sample          = EXCLUDED.sample
`

type UpsertClosureStatusParams struct {
	GraphID      string
	MissingCount int32
	ExtraCount   int32
	InDrift      bool
	Sample       []byte
}

func (q *Queries) UpsertClosureStatus(ctx context.Context, arg UpsertClosureStatusParams) error {
	_, err := q.db.Exec(ctx, upsertClosureStatus,
		arg.GraphID,
		arg.MissingCount,
		arg.ExtraCount,
		arg.InDrift,
		arg.Sample,
	)
	return err
}

const verifyClosureForGraph = `-- name: VerifyClosureForGraph :one
WITH RECURSIVE
  nodes AS (
    SELECT te.parent_id AS u FROM oikumenea.tenant_unit_edges te WHERE te.graph_id = $1
    UNION
    SELECT te.child_id FROM oikumenea.tenant_unit_edges te WHERE te.graph_id = $1
  ),
  reach AS (
    SELECT u AS ancestor_id, u AS descendant_id, 0 AS depth FROM nodes
    UNION ALL
    SELECT r.ancestor_id, e.child_id, r.depth + 1
    FROM reach r
    JOIN oikumenea.tenant_unit_edges e
      ON e.graph_id = $1 AND e.parent_id = r.descendant_id
  ),
  expected AS (
    SELECT DISTINCT ancestor_id, descendant_id FROM reach
  ),
  stored AS (
    SELECT tc.ancestor_id, tc.descendant_id FROM oikumenea.tenant_unit_closure tc WHERE tc.graph_id = $1
  ),
  missing AS (SELECT ancestor_id, descendant_id FROM expected EXCEPT SELECT ancestor_id, descendant_id FROM stored),
  extra   AS (SELECT ancestor_id, descendant_id FROM stored   EXCEPT SELECT ancestor_id, descendant_id FROM expected)
SELECT
  (SELECT count(*) FROM missing)::int AS missing_count,
  (SELECT count(*) FROM extra)::int   AS extra_count,
  (SELECT coalesce(jsonb_agg(s), '[]'::jsonb) FROM (
     (SELECT 'missing'::text AS kind, ancestor_id, descendant_id FROM missing LIMIT 5)
     UNION ALL
     (SELECT 'extra'::text AS kind, ancestor_id, descendant_id FROM extra LIMIT 5)
   ) s) AS sample
`

type VerifyClosureForGraphRow struct {
	MissingCount int32
	ExtraCount   int32
	Sample       interface{}
}

// Diff the stored closure against a freshly computed one (pair membership), returning the counts
// and a small sample for the drift report. Does not modify the stored closure.
func (q *Queries) VerifyClosureForGraph(ctx context.Context, graphID string) (VerifyClosureForGraphRow, error) {
	row := q.db.QueryRow(ctx, verifyClosureForGraph, graphID)
	var i VerifyClosureForGraphRow
	err := row.Scan(&i.MissingCount, &i.ExtraCount, &i.Sample)
	return i, err
}
