// Code generated by conjure-go. DO NOT EDIT.

package platform

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/olegamysk/go-oikumenea/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	werror "github.com/palantir/witchcraft-go-error"
)

type demoError struct {
	Reason string `json:"reason"`
}

func (o demoError) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *demoError) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewDemoError returns new instance of DemoError error.
func NewDemoError(reasonArg string) *DemoError {
	return &DemoError{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), demoError: demoError{Reason: reasonArg}}
}

// WrapWithDemoError returns new instance of DemoError error wrapping an existing error.
func WrapWithDemoError(err error, reasonArg string) *DemoError {
	return &DemoError{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, demoError: demoError{Reason: reasonArg}}
}

// DemoError is an error type.
/*
A deliberately-returned error used by GET /demo/error to prove the
werror -> Conjure SerializableError path end to end. Not a real domain error.
*/
type DemoError struct {
	errorInstanceID uuid.UUID
	demoError
	cause error
	stack werror.StackTrace
}

// IsDemoError returns true if err is an instance of DemoError.
func IsDemoError(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*DemoError)
	return ok
}

func (e *DemoError) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Platform:DemoError (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *DemoError) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *DemoError) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *DemoError) Message() string {
	return "INVALID_ARGUMENT Platform:DemoError"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *DemoError) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *DemoError) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *DemoError) Name() string {
	return "Platform:DemoError"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *DemoError) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *DemoError) Parameters() map[string]interface{} {
	return map[string]interface{}{"reason": e.Reason}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *DemoError) safeParams() map[string]interface{} {
	return map[string]interface{}{"reason": e.Reason, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *DemoError) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *DemoError) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *DemoError) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e DemoError) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.demoError)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Platform:DemoError", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *DemoError) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters demoError
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.demoError = parameters
	return nil
}

func init() {
	conjureerrors.RegisterErrorType("Platform:DemoError", reflect.TypeOf(DemoError{}))
}
