// Code generated by conjure-go. DO NOT EDIT.

package connector

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/olegamysk/go-oikumenea/clients/go/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	werror "github.com/palantir/witchcraft-go-error"
)

type connectorConflict struct {
	Reason string `json:"reason"`
}

func (o connectorConflict) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *connectorConflict) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewConnectorConflict returns new instance of ConnectorConflict error.
func NewConnectorConflict(reasonArg string) *ConnectorConflict {
	return &ConnectorConflict{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), connectorConflict: connectorConflict{Reason: reasonArg}}
}

// WrapWithConnectorConflict returns new instance of ConnectorConflict error wrapping an existing error.
func WrapWithConnectorConflict(err error, reasonArg string) *ConnectorConflict {
	return &ConnectorConflict{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, connectorConflict: connectorConflict{Reason: reasonArg}}
}

// ConnectorConflict is an error type.
// The code is registered to a different principal, or the payload collides with a live row.
type ConnectorConflict struct {
	errorInstanceID uuid.UUID
	connectorConflict
	cause error
	stack werror.StackTrace
}

// IsConnectorConflict returns true if err is an instance of ConnectorConflict.
func IsConnectorConflict(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*ConnectorConflict)
	return ok
}

func (e *ConnectorConflict) Error() string {
	return fmt.Sprintf("CONFLICT Connector:ConnectorConflict (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *ConnectorConflict) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *ConnectorConflict) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *ConnectorConflict) Message() string {
	return "CONFLICT Connector:ConnectorConflict"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *ConnectorConflict) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *ConnectorConflict) Code() errors.ErrorCode {
	return errors.Conflict
}

// Name returns an error name identifying error type.
func (e *ConnectorConflict) Name() string {
	return "Connector:ConnectorConflict"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *ConnectorConflict) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *ConnectorConflict) Parameters() map[string]interface{} {
	return map[string]interface{}{"reason": e.Reason}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *ConnectorConflict) safeParams() map[string]interface{} {
	return map[string]interface{}{"reason": e.Reason, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *ConnectorConflict) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *ConnectorConflict) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *ConnectorConflict) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e ConnectorConflict) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.connectorConflict)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.Conflict, ErrorName: "Connector:ConnectorConflict", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *ConnectorConflict) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters connectorConflict
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.connectorConflict = parameters
	return nil
}

type connectorInvalid struct {
	Reason string `json:"reason"`
}

func (o connectorInvalid) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *connectorInvalid) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewConnectorInvalid returns new instance of ConnectorInvalid error.
func NewConnectorInvalid(reasonArg string) *ConnectorInvalid {
	return &ConnectorInvalid{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), connectorInvalid: connectorInvalid{Reason: reasonArg}}
}

// WrapWithConnectorInvalid returns new instance of ConnectorInvalid error wrapping an existing error.
func WrapWithConnectorInvalid(err error, reasonArg string) *ConnectorInvalid {
	return &ConnectorInvalid{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, connectorInvalid: connectorInvalid{Reason: reasonArg}}
}

// ConnectorInvalid is an error type.
type ConnectorInvalid struct {
	errorInstanceID uuid.UUID
	connectorInvalid
	cause error
	stack werror.StackTrace
}

// IsConnectorInvalid returns true if err is an instance of ConnectorInvalid.
func IsConnectorInvalid(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*ConnectorInvalid)
	return ok
}

func (e *ConnectorInvalid) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Connector:ConnectorInvalid (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *ConnectorInvalid) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *ConnectorInvalid) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *ConnectorInvalid) Message() string {
	return "INVALID_ARGUMENT Connector:ConnectorInvalid"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *ConnectorInvalid) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *ConnectorInvalid) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *ConnectorInvalid) Name() string {
	return "Connector:ConnectorInvalid"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *ConnectorInvalid) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *ConnectorInvalid) Parameters() map[string]interface{} {
	return map[string]interface{}{"reason": e.Reason}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *ConnectorInvalid) safeParams() map[string]interface{} {
	return map[string]interface{}{"reason": e.Reason, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *ConnectorInvalid) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *ConnectorInvalid) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *ConnectorInvalid) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e ConnectorInvalid) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.connectorInvalid)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Connector:ConnectorInvalid", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *ConnectorInvalid) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters connectorInvalid
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.connectorInvalid = parameters
	return nil
}

type connectorNotFound struct {
	ConnectorId string `json:"connectorId"`
}

func (o connectorNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *connectorNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewConnectorNotFound returns new instance of ConnectorNotFound error.
func NewConnectorNotFound(connectorIdArg string) *ConnectorNotFound {
	return &ConnectorNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), connectorNotFound: connectorNotFound{ConnectorId: connectorIdArg}}
}

// WrapWithConnectorNotFound returns new instance of ConnectorNotFound error wrapping an existing error.
func WrapWithConnectorNotFound(err error, connectorIdArg string) *ConnectorNotFound {
	return &ConnectorNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, connectorNotFound: connectorNotFound{ConnectorId: connectorIdArg}}
}

// ConnectorNotFound is an error type.
type ConnectorNotFound struct {
	errorInstanceID uuid.UUID
	connectorNotFound
	cause error
	stack werror.StackTrace
}

// IsConnectorNotFound returns true if err is an instance of ConnectorNotFound.
func IsConnectorNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*ConnectorNotFound)
	return ok
}

func (e *ConnectorNotFound) Error() string {
	return fmt.Sprintf("NOT_FOUND Connector:ConnectorNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *ConnectorNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *ConnectorNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *ConnectorNotFound) Message() string {
	return "NOT_FOUND Connector:ConnectorNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *ConnectorNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *ConnectorNotFound) Code() errors.ErrorCode {
	return errors.NotFound
}

// Name returns an error name identifying error type.
func (e *ConnectorNotFound) Name() string {
	return "Connector:ConnectorNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *ConnectorNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *ConnectorNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{"connectorId": e.ConnectorId}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *ConnectorNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"connectorId": e.ConnectorId, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *ConnectorNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *ConnectorNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *ConnectorNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e ConnectorNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.connectorNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.NotFound, ErrorName: "Connector:ConnectorNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *ConnectorNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters connectorNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.connectorNotFound = parameters
	return nil
}

type sourceNotFound struct {
	SourceCode string `json:"sourceCode"`
}

func (o sourceNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *sourceNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewSourceNotFound returns new instance of SourceNotFound error.
func NewSourceNotFound(sourceCodeArg string) *SourceNotFound {
	return &SourceNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), sourceNotFound: sourceNotFound{SourceCode: sourceCodeArg}}
}

// WrapWithSourceNotFound returns new instance of SourceNotFound error wrapping an existing error.
func WrapWithSourceNotFound(err error, sourceCodeArg string) *SourceNotFound {
	return &SourceNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, sourceNotFound: sourceNotFound{SourceCode: sourceCodeArg}}
}

// SourceNotFound is an error type.
// The calling connector declares no source with this code.
type SourceNotFound struct {
	errorInstanceID uuid.UUID
	sourceNotFound
	cause error
	stack werror.StackTrace
}

// IsSourceNotFound returns true if err is an instance of SourceNotFound.
func IsSourceNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*SourceNotFound)
	return ok
}

func (e *SourceNotFound) Error() string {
	return fmt.Sprintf("NOT_FOUND Connector:SourceNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *SourceNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *SourceNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *SourceNotFound) Message() string {
	return "NOT_FOUND Connector:SourceNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *SourceNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *SourceNotFound) Code() errors.ErrorCode {
	return errors.NotFound
}

// Name returns an error name identifying error type.
func (e *SourceNotFound) Name() string {
	return "Connector:SourceNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *SourceNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *SourceNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{"sourceCode": e.SourceCode}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *SourceNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"sourceCode": e.SourceCode, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *SourceNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *SourceNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *SourceNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e SourceNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.sourceNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.NotFound, ErrorName: "Connector:SourceNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *SourceNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters sourceNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.sourceNotFound = parameters
	return nil
}

func init() {
	conjureerrors.RegisterErrorType("Connector:ConnectorConflict", reflect.TypeOf(ConnectorConflict{}))
	conjureerrors.RegisterErrorType("Connector:ConnectorInvalid", reflect.TypeOf(ConnectorInvalid{}))
	conjureerrors.RegisterErrorType("Connector:ConnectorNotFound", reflect.TypeOf(ConnectorNotFound{}))
	conjureerrors.RegisterErrorType("Connector:SourceNotFound", reflect.TypeOf(SourceNotFound{}))
}
