// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: language.sql

package languagesql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLanguoid = `-- name: GetLanguoid :one
SELECT l.id, l.code, l.level, l.name, l.parent_id, l.family_code, l.iso639_3, l.macroarea, l.status,
  EXISTS (
    SELECT 1 FROM oikumenea.language_languoids c
    WHERE c.parent_id = l.id AND c.level <> 'dialect'
  ) AS has_children
FROM oikumenea.language_languoids l WHERE l.id = $1
`

type GetLanguoidRow struct {
	ID          string
	Code        string
	Level       string
	Name        string
	ParentID    pgtype.Text
	FamilyCode  pgtype.Text
	Iso6393     pgtype.Text
	Macroarea   pgtype.Text
	Status      string
	HasChildren bool
}

func (q *Queries) GetLanguoid(ctx context.Context, id string) (GetLanguoidRow, error) {
	row := q.db.QueryRow(ctx, getLanguoid, id)
	var i GetLanguoidRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Name,
		&i.ParentID,
		&i.FamilyCode,
		&i.Iso6393,
		&i.Macroarea,
		&i.Status,
		&i.HasChildren,
	)
	return i, err
}

const listLanguoids = `-- name: ListLanguoids :many

SELECT l.id, l.code, l.level, l.name, l.parent_id, l.family_code, l.iso639_3, l.macroarea, l.status,
  EXISTS (
    SELECT 1 FROM oikumenea.language_languoids c
    WHERE c.parent_id = l.id AND c.level <> 'dialect'
  ) AS has_children
FROM oikumenea.language_languoids l
WHERE ($1::text = '' OR l.level = $1::text)
  AND ($2::text = '' OR l.family_code = $2::text)
  AND ($3::text = '' OR l.parent_id::text = $3::text)
  AND (NOT $4::bool OR l.parent_id IS NULL)
  AND ($5::text = '' OR l.name ILIKE '%' || $5::text || '%' OR l.code ILIKE $5::text || '%')
  AND ($6::text = '' OR l.code > $6::text)
ORDER BY l.code
LIMIT $7::int
`

type ListLanguoidsParams struct {
	Level    string
	Family   string
	Parent   string
	TopLevel bool
	Q        string
	After    string
	Lim      int32
}

type ListLanguoidsRow struct {
	ID          string
	Code        string
	Level       string
	Name        string
	ParentID    pgtype.Text
	FamilyCode  pgtype.Text
	Iso6393     pgtype.Text
	Macroarea   pgtype.Text
	Status      string
	HasChildren bool
}

// Language module queries (docs/modules/language.md; D-Languages, M18). Read-only lookups over the
// RID-keyed Glottolog languoid forest + ISO-15924 writing-system registry. The catalog is written by
// the hermenea import pipeline (language-scheme / language-scripts), not here.
// Languoids in code order, optionally filtered by level, root family (family_code), immediate parent
// (one tree level), top-level-only, a name/glottocode substring, and a keyset cursor (after: return
// rows whose code sorts strictly after it, for pagination). The empty-string / false sentinels disable
// each filter; the limit is clamped by the application. has_children flags whether
// the node has any non-dialect child, so a tree browser can show an expand affordance only where it
// leads somewhere (family → language; languages whose only children are dialects read as leaves).
func (q *Queries) ListLanguoids(ctx context.Context, arg ListLanguoidsParams) ([]ListLanguoidsRow, error) {
	rows, err := q.db.Query(ctx, listLanguoids,
		arg.Level,
		arg.Family,
		arg.Parent,
		arg.TopLevel,
		arg.Q,
		arg.After,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLanguoidsRow
	for rows.Next() {
		var i ListLanguoidsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Level,
			&i.Name,
			&i.ParentID,
			&i.FamilyCode,
			&i.Iso6393,
			&i.Macroarea,
			&i.Status,
			&i.HasChildren,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWritingSystems = `-- name: ListWritingSystems :many
SELECT id, code, name, script_type FROM oikumenea.writing_systems ORDER BY code
`

type ListWritingSystemsRow struct {
	ID         string
	Code       string
	Name       string
	ScriptType pgtype.Text
}

func (q *Queries) ListWritingSystems(ctx context.Context) ([]ListWritingSystemsRow, error) {
	rows, err := q.db.Query(ctx, listWritingSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWritingSystemsRow
	for rows.Next() {
		var i ListWritingSystemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ScriptType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
