// Code generated by conjure-go. DO NOT EDIT.

package authorization

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olegamysk/go-oikumenea/client/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

/*
The PDP + RBAC management. /authorize answers (person, action, unit) over the unit-graph
closure; roles/assignments/instance-admins are policy-as-data. /authorize requires
assignment.read (no self-exemption, OQ-5); role.* are instance-scope; assignment.grant/revoke
are unit-scoped on the target unit; instance.admin.manage is instance-scope. Writes audited
(D-Audit). Denied operations surface Authorization:PermissionDenied.
*/
type AuthorizationServiceClient interface {
	// Decide (subject, action, unit). Requires assignment.read reaching the unit.
	Authorize(ctx context.Context, authHeader bearertoken.Token, requestArg AuthorizeRequest) (AuthorizeResponse, error)
	// Batch decisions for one subject, with optional decision-explain (DS-16).
	AuthorizeBatch(ctx context.Context, authHeader bearertoken.Token, requestArg BatchAuthorizeRequest) (BatchAuthorizeResponse, error)
	// Create a custom role (instance-scope role.create). Returns Role:RoleConflict if the code is taken.
	CreateRole(ctx context.Context, authHeader bearertoken.Token, requestArg CreateRoleRequest) (Role, error)
	// List roles, token-paginated (role.read).
	ListRoles(ctx context.Context, authHeader bearertoken.Token, pageSizeArg *int, pageTokenArg *string) (RolePage, error)
	// Read one role with its permission set (role.read).
	GetRole(ctx context.Context, authHeader bearertoken.Token, roleIdArg string) (Role, error)
	// Edit a custom role (instance-scope role.update). Base roles return Role:RoleImmutable.
	UpdateRole(ctx context.Context, authHeader bearertoken.Token, roleIdArg string, requestArg UpdateRoleRequest) (Role, error)
	// Soft-delete a custom role (instance-scope role.delete). Blocked with Role:RoleInUse if assigned.
	DeleteRole(ctx context.Context, authHeader bearertoken.Token, roleIdArg string) error
	// Grant (subject, role, unit, scope, graph) + optional expiry (assignment.grant on the target unit).
	GrantAssignment(ctx context.Context, authHeader bearertoken.Token, requestArg GrantAssignmentRequest) (Assignment, error)
	// Revoke an assignment (reversible flip; assignment.revoke).
	RevokeAssignment(ctx context.Context, authHeader bearertoken.Token, assignmentIdArg string) (Assignment, error)
	// List active assignments by subjectPersonId OR targetUnitId (exactly one), token-paginated (assignment.read).
	ListAssignments(ctx context.Context, authHeader bearertoken.Token, subjectPersonIdArg *string, targetUnitIdArg *string, pageSizeArg *int, pageTokenArg *string) (AssignmentPage, error)
	// Grant instance-admin (instance.admin.manage). Returns Authorization:InstanceAdminConflict if already active.
	GrantInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, requestArg GrantInstanceAdminRequest) (InstanceAdmin, error)
	// Revoke instance-admin (instance.admin.manage; reversible flip).
	RevokeInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, instanceAdminIdArg string) (InstanceAdmin, error)
}

type authorizationServiceClient struct {
	client httpclient.Client
}

func NewAuthorizationServiceClient(client httpclient.Client) AuthorizationServiceClient {
	return &authorizationServiceClient{client: client}
}

func (c *authorizationServiceClient) Authorize(ctx context.Context, authHeader bearertoken.Token, requestArg AuthorizeRequest) (AuthorizeResponse, error) {
	var returnVal *AuthorizeResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Authorize"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/authorize"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(AuthorizeResponse), werror.WrapWithContextParams(ctx, err, "authorize failed")
	}
	if returnVal == nil {
		return *new(AuthorizeResponse), werror.ErrorWithContextParams(ctx, "authorize response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) AuthorizeBatch(ctx context.Context, authHeader bearertoken.Token, requestArg BatchAuthorizeRequest) (BatchAuthorizeResponse, error) {
	var returnVal *BatchAuthorizeResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("AuthorizeBatch"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/authorize/batch"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(BatchAuthorizeResponse), werror.WrapWithContextParams(ctx, err, "authorizeBatch failed")
	}
	if returnVal == nil {
		return *new(BatchAuthorizeResponse), werror.ErrorWithContextParams(ctx, "authorizeBatch response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) CreateRole(ctx context.Context, authHeader bearertoken.Token, requestArg CreateRoleRequest) (Role, error) {
	var returnVal *Role
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("CreateRole"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/roles"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(Role), werror.WrapWithContextParams(ctx, err, "createRole failed")
	}
	if returnVal == nil {
		return *new(Role), werror.ErrorWithContextParams(ctx, "createRole response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) ListRoles(ctx context.Context, authHeader bearertoken.Token, pageSizeArg *int, pageTokenArg *string) (RolePage, error) {
	var returnVal *RolePage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListRoles"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/roles"))
	queryParams := make(url.Values)
	if pageSizeArg != nil {
		queryParams.Set("pageSize", fmt.Sprint(*pageSizeArg))
	}
	if pageTokenArg != nil {
		queryParams.Set("pageToken", fmt.Sprint(*pageTokenArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(RolePage), werror.WrapWithContextParams(ctx, err, "listRoles failed")
	}
	if returnVal == nil {
		return *new(RolePage), werror.ErrorWithContextParams(ctx, "listRoles response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) GetRole(ctx context.Context, authHeader bearertoken.Token, roleIdArg string) (Role, error) {
	var returnVal *Role
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetRole"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/roles/%s", url.PathEscape(fmt.Sprint(roleIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(Role), werror.WrapWithContextParams(ctx, err, "getRole failed")
	}
	if returnVal == nil {
		return *new(Role), werror.ErrorWithContextParams(ctx, "getRole response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) UpdateRole(ctx context.Context, authHeader bearertoken.Token, roleIdArg string, requestArg UpdateRoleRequest) (Role, error) {
	var returnVal *Role
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("UpdateRole"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/roles/%s", url.PathEscape(fmt.Sprint(roleIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Put(ctx, requestParams...); err != nil {
		return *new(Role), werror.WrapWithContextParams(ctx, err, "updateRole failed")
	}
	if returnVal == nil {
		return *new(Role), werror.ErrorWithContextParams(ctx, "updateRole response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) DeleteRole(ctx context.Context, authHeader bearertoken.Token, roleIdArg string) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("DeleteRole"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/roles/%s", url.PathEscape(fmt.Sprint(roleIdArg))))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Delete(ctx, requestParams...); err != nil {
		return werror.WrapWithContextParams(ctx, err, "deleteRole failed")
	}
	return nil
}

func (c *authorizationServiceClient) GrantAssignment(ctx context.Context, authHeader bearertoken.Token, requestArg GrantAssignmentRequest) (Assignment, error) {
	var returnVal *Assignment
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GrantAssignment"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/assignments"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(Assignment), werror.WrapWithContextParams(ctx, err, "grantAssignment failed")
	}
	if returnVal == nil {
		return *new(Assignment), werror.ErrorWithContextParams(ctx, "grantAssignment response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) RevokeAssignment(ctx context.Context, authHeader bearertoken.Token, assignmentIdArg string) (Assignment, error) {
	var returnVal *Assignment
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("RevokeAssignment"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/assignments/%s", url.PathEscape(fmt.Sprint(assignmentIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Delete(ctx, requestParams...); err != nil {
		return *new(Assignment), werror.WrapWithContextParams(ctx, err, "revokeAssignment failed")
	}
	if returnVal == nil {
		return *new(Assignment), werror.ErrorWithContextParams(ctx, "revokeAssignment response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) ListAssignments(ctx context.Context, authHeader bearertoken.Token, subjectPersonIdArg *string, targetUnitIdArg *string, pageSizeArg *int, pageTokenArg *string) (AssignmentPage, error) {
	var returnVal *AssignmentPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListAssignments"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/assignments"))
	queryParams := make(url.Values)
	if subjectPersonIdArg != nil {
		queryParams.Set("subjectPersonId", fmt.Sprint(*subjectPersonIdArg))
	}
	if targetUnitIdArg != nil {
		queryParams.Set("targetUnitId", fmt.Sprint(*targetUnitIdArg))
	}
	if pageSizeArg != nil {
		queryParams.Set("pageSize", fmt.Sprint(*pageSizeArg))
	}
	if pageTokenArg != nil {
		queryParams.Set("pageToken", fmt.Sprint(*pageTokenArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(AssignmentPage), werror.WrapWithContextParams(ctx, err, "listAssignments failed")
	}
	if returnVal == nil {
		return *new(AssignmentPage), werror.ErrorWithContextParams(ctx, "listAssignments response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) GrantInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, requestArg GrantInstanceAdminRequest) (InstanceAdmin, error) {
	var returnVal *InstanceAdmin
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GrantInstanceAdmin"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/instance-admins"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(InstanceAdmin), werror.WrapWithContextParams(ctx, err, "grantInstanceAdmin failed")
	}
	if returnVal == nil {
		return *new(InstanceAdmin), werror.ErrorWithContextParams(ctx, "grantInstanceAdmin response cannot be nil")
	}
	return *returnVal, nil
}

func (c *authorizationServiceClient) RevokeInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, instanceAdminIdArg string) (InstanceAdmin, error) {
	var returnVal *InstanceAdmin
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("RevokeInstanceAdmin"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/authorization/v1/instance-admins/%s", url.PathEscape(fmt.Sprint(instanceAdminIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Delete(ctx, requestParams...); err != nil {
		return *new(InstanceAdmin), werror.WrapWithContextParams(ctx, err, "revokeInstanceAdmin failed")
	}
	if returnVal == nil {
		return *new(InstanceAdmin), werror.ErrorWithContextParams(ctx, "revokeInstanceAdmin response cannot be nil")
	}
	return *returnVal, nil
}

/*
The PDP + RBAC management. /authorize answers (person, action, unit) over the unit-graph
closure; roles/assignments/instance-admins are policy-as-data. /authorize requires
assignment.read (no self-exemption, OQ-5); role.* are instance-scope; assignment.grant/revoke
are unit-scoped on the target unit; instance.admin.manage is instance-scope. Writes audited
(D-Audit). Denied operations surface Authorization:PermissionDenied.
*/
type AuthorizationServiceClientWithAuth interface {
	// Decide (subject, action, unit). Requires assignment.read reaching the unit.
	Authorize(ctx context.Context, requestArg AuthorizeRequest) (AuthorizeResponse, error)
	// Batch decisions for one subject, with optional decision-explain (DS-16).
	AuthorizeBatch(ctx context.Context, requestArg BatchAuthorizeRequest) (BatchAuthorizeResponse, error)
	// Create a custom role (instance-scope role.create). Returns Role:RoleConflict if the code is taken.
	CreateRole(ctx context.Context, requestArg CreateRoleRequest) (Role, error)
	// List roles, token-paginated (role.read).
	ListRoles(ctx context.Context, pageSizeArg *int, pageTokenArg *string) (RolePage, error)
	// Read one role with its permission set (role.read).
	GetRole(ctx context.Context, roleIdArg string) (Role, error)
	// Edit a custom role (instance-scope role.update). Base roles return Role:RoleImmutable.
	UpdateRole(ctx context.Context, roleIdArg string, requestArg UpdateRoleRequest) (Role, error)
	// Soft-delete a custom role (instance-scope role.delete). Blocked with Role:RoleInUse if assigned.
	DeleteRole(ctx context.Context, roleIdArg string) error
	// Grant (subject, role, unit, scope, graph) + optional expiry (assignment.grant on the target unit).
	GrantAssignment(ctx context.Context, requestArg GrantAssignmentRequest) (Assignment, error)
	// Revoke an assignment (reversible flip; assignment.revoke).
	RevokeAssignment(ctx context.Context, assignmentIdArg string) (Assignment, error)
	// List active assignments by subjectPersonId OR targetUnitId (exactly one), token-paginated (assignment.read).
	ListAssignments(ctx context.Context, subjectPersonIdArg *string, targetUnitIdArg *string, pageSizeArg *int, pageTokenArg *string) (AssignmentPage, error)
	// Grant instance-admin (instance.admin.manage). Returns Authorization:InstanceAdminConflict if already active.
	GrantInstanceAdmin(ctx context.Context, requestArg GrantInstanceAdminRequest) (InstanceAdmin, error)
	// Revoke instance-admin (instance.admin.manage; reversible flip).
	RevokeInstanceAdmin(ctx context.Context, instanceAdminIdArg string) (InstanceAdmin, error)
}

func NewAuthorizationServiceClientWithAuth(client AuthorizationServiceClient, authHeader bearertoken.Token) AuthorizationServiceClientWithAuth {
	return &authorizationServiceClientWithAuth{client: client, authHeader: authHeader}
}

type authorizationServiceClientWithAuth struct {
	client     AuthorizationServiceClient
	authHeader bearertoken.Token
}

func (c *authorizationServiceClientWithAuth) Authorize(ctx context.Context, requestArg AuthorizeRequest) (AuthorizeResponse, error) {
	return c.client.Authorize(ctx, c.authHeader, requestArg)
}

func (c *authorizationServiceClientWithAuth) AuthorizeBatch(ctx context.Context, requestArg BatchAuthorizeRequest) (BatchAuthorizeResponse, error) {
	return c.client.AuthorizeBatch(ctx, c.authHeader, requestArg)
}

func (c *authorizationServiceClientWithAuth) CreateRole(ctx context.Context, requestArg CreateRoleRequest) (Role, error) {
	return c.client.CreateRole(ctx, c.authHeader, requestArg)
}

func (c *authorizationServiceClientWithAuth) ListRoles(ctx context.Context, pageSizeArg *int, pageTokenArg *string) (RolePage, error) {
	return c.client.ListRoles(ctx, c.authHeader, pageSizeArg, pageTokenArg)
}

func (c *authorizationServiceClientWithAuth) GetRole(ctx context.Context, roleIdArg string) (Role, error) {
	return c.client.GetRole(ctx, c.authHeader, roleIdArg)
}

func (c *authorizationServiceClientWithAuth) UpdateRole(ctx context.Context, roleIdArg string, requestArg UpdateRoleRequest) (Role, error) {
	return c.client.UpdateRole(ctx, c.authHeader, roleIdArg, requestArg)
}

func (c *authorizationServiceClientWithAuth) DeleteRole(ctx context.Context, roleIdArg string) error {
	return c.client.DeleteRole(ctx, c.authHeader, roleIdArg)
}

func (c *authorizationServiceClientWithAuth) GrantAssignment(ctx context.Context, requestArg GrantAssignmentRequest) (Assignment, error) {
	return c.client.GrantAssignment(ctx, c.authHeader, requestArg)
}

func (c *authorizationServiceClientWithAuth) RevokeAssignment(ctx context.Context, assignmentIdArg string) (Assignment, error) {
	return c.client.RevokeAssignment(ctx, c.authHeader, assignmentIdArg)
}

func (c *authorizationServiceClientWithAuth) ListAssignments(ctx context.Context, subjectPersonIdArg *string, targetUnitIdArg *string, pageSizeArg *int, pageTokenArg *string) (AssignmentPage, error) {
	return c.client.ListAssignments(ctx, c.authHeader, subjectPersonIdArg, targetUnitIdArg, pageSizeArg, pageTokenArg)
}

func (c *authorizationServiceClientWithAuth) GrantInstanceAdmin(ctx context.Context, requestArg GrantInstanceAdminRequest) (InstanceAdmin, error) {
	return c.client.GrantInstanceAdmin(ctx, c.authHeader, requestArg)
}

func (c *authorizationServiceClientWithAuth) RevokeInstanceAdmin(ctx context.Context, instanceAdminIdArg string) (InstanceAdmin, error) {
	return c.client.RevokeInstanceAdmin(ctx, c.authHeader, instanceAdminIdArg)
}

func NewAuthorizationServiceClientWithTokenProvider(client AuthorizationServiceClient, tokenProvider httpclient.TokenProvider) AuthorizationServiceClientWithAuth {
	return &authorizationServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type authorizationServiceClientWithTokenProvider struct {
	client        AuthorizationServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *authorizationServiceClientWithTokenProvider) Authorize(ctx context.Context, requestArg AuthorizeRequest) (AuthorizeResponse, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(AuthorizeResponse), err
	}
	return c.client.Authorize(ctx, bearertoken.Token(token), requestArg)
}

func (c *authorizationServiceClientWithTokenProvider) AuthorizeBatch(ctx context.Context, requestArg BatchAuthorizeRequest) (BatchAuthorizeResponse, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(BatchAuthorizeResponse), err
	}
	return c.client.AuthorizeBatch(ctx, bearertoken.Token(token), requestArg)
}

func (c *authorizationServiceClientWithTokenProvider) CreateRole(ctx context.Context, requestArg CreateRoleRequest) (Role, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Role), err
	}
	return c.client.CreateRole(ctx, bearertoken.Token(token), requestArg)
}

func (c *authorizationServiceClientWithTokenProvider) ListRoles(ctx context.Context, pageSizeArg *int, pageTokenArg *string) (RolePage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RolePage), err
	}
	return c.client.ListRoles(ctx, bearertoken.Token(token), pageSizeArg, pageTokenArg)
}

func (c *authorizationServiceClientWithTokenProvider) GetRole(ctx context.Context, roleIdArg string) (Role, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Role), err
	}
	return c.client.GetRole(ctx, bearertoken.Token(token), roleIdArg)
}

func (c *authorizationServiceClientWithTokenProvider) UpdateRole(ctx context.Context, roleIdArg string, requestArg UpdateRoleRequest) (Role, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Role), err
	}
	return c.client.UpdateRole(ctx, bearertoken.Token(token), roleIdArg, requestArg)
}

func (c *authorizationServiceClientWithTokenProvider) DeleteRole(ctx context.Context, roleIdArg string) error {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return err
	}
	return c.client.DeleteRole(ctx, bearertoken.Token(token), roleIdArg)
}

func (c *authorizationServiceClientWithTokenProvider) GrantAssignment(ctx context.Context, requestArg GrantAssignmentRequest) (Assignment, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Assignment), err
	}
	return c.client.GrantAssignment(ctx, bearertoken.Token(token), requestArg)
}

func (c *authorizationServiceClientWithTokenProvider) RevokeAssignment(ctx context.Context, assignmentIdArg string) (Assignment, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Assignment), err
	}
	return c.client.RevokeAssignment(ctx, bearertoken.Token(token), assignmentIdArg)
}

func (c *authorizationServiceClientWithTokenProvider) ListAssignments(ctx context.Context, subjectPersonIdArg *string, targetUnitIdArg *string, pageSizeArg *int, pageTokenArg *string) (AssignmentPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(AssignmentPage), err
	}
	return c.client.ListAssignments(ctx, bearertoken.Token(token), subjectPersonIdArg, targetUnitIdArg, pageSizeArg, pageTokenArg)
}

func (c *authorizationServiceClientWithTokenProvider) GrantInstanceAdmin(ctx context.Context, requestArg GrantInstanceAdminRequest) (InstanceAdmin, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(InstanceAdmin), err
	}
	return c.client.GrantInstanceAdmin(ctx, bearertoken.Token(token), requestArg)
}

func (c *authorizationServiceClientWithTokenProvider) RevokeInstanceAdmin(ctx context.Context, instanceAdminIdArg string) (InstanceAdmin, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(InstanceAdmin), err
	}
	return c.client.RevokeInstanceAdmin(ctx, bearertoken.Token(token), instanceAdminIdArg)
}
