// Code generated by conjure-go. DO NOT EDIT.

package vehicle

import (
	"context"
	"net/http"
	"strconv"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

/*
A vehicle registry: brand/model/type catalogs, vehicles, the brand->manufacturer link, and the
ownership+plate registration record. Reads gate on `vehicle.read`; vehicle/registration/
manufacturer writes on `vehicle.manage`; catalog-entry writes on `vehicle.catalog.manage`. Writes
are audited in-process (D-Audit).
*/
type VehicleService interface {
	ListVehicleTypes(ctx context.Context, authHeader bearertoken.Token) (VehicleTypeList, error)
	UpsertVehicleType(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertVehicleTypeRequest) (VehicleType, error)
	ListBrands(ctx context.Context, authHeader bearertoken.Token, queryArg *string) (BrandList, error)
	UpsertBrand(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertBrandRequest) (Brand, error)
	ListModels(ctx context.Context, authHeader bearertoken.Token, brandIdArg string) (ModelList, error)
	UpsertModel(ctx context.Context, authHeader bearertoken.Token, brandIdArg string, requestArg UpsertModelRequest) (Model, error)
	ListRegistrationNumberTypes(ctx context.Context, authHeader bearertoken.Token) (RegistrationNumberTypeList, error)
	UpsertRegistrationNumberType(ctx context.Context, authHeader bearertoken.Token, requestArg UpsertNumberTypeRequest) (RegistrationNumberType, error)
	CreateVehicle(ctx context.Context, authHeader bearertoken.Token, requestArg CreateVehicleRequest) (Vehicle, error)
	/*
	   List vehicles, token-paginated, narrowed by any combination of the facet filters below
	   (M58 / D-ObjectFacets). Every filter here is also a distribution on `vehicleStats`, so a
	   dashboard and a list are two renderings of one request state. Gated by `vehicle.read`.
	*/
	ListVehicles(ctx context.Context, authHeader bearertoken.Token, queryArg *string, typeIdArg *string, brandIdArg *string, modelIdArg *string, colorArg *string, statusArg *string, manufactureDateFromArg *string, manufactureDateToArg *string, registrationCountryArg *string, pageSizeArg *int, pageTokenArg *string) (VehiclePage, error)
	/*
	   Facet distributions over the fleet — the dashboard half of the facet vocabulary (M58 /
	   D-ObjectFacets). Takes exactly the filter args `listVehicles` takes (minus paging) plus an
	   optional `facets` CSV, so a dashboard and a list are two renderings of ONE request state
	   and a chart segment is a link to the same URL with one more filter applied.

	   `totalCount` equals the number of rows exhaustively paging `listVehicles` with these same
	   filters would return. One round-trip serves the whole dashboard.

	   ONE aggregate arm, with no subject and no scoped twin — for the same reason
	   `externalOrgStats` has one, and NOT the audit ledger's reason. `vehicle_vehicles` carries no
	   row-level security, no unit column and no reach predicate: `vehicle.read` held anywhere is
	   the whole visibility decision, so there is nothing for a second arm to narrow.

	   The path is `/stats/vehicles` rather than `/vehicles/stats` because the server's router
	   rejects a literal path segment that is a sibling of `{vehicleId}`.
	*/
	VehicleStats(ctx context.Context, authHeader bearertoken.Token, facetsArg *string, queryArg *string, typeIdArg *string, brandIdArg *string, modelIdArg *string, colorArg *string, statusArg *string, manufactureDateFromArg *string, manufactureDateToArg *string, registrationCountryArg *string) (VehicleStats, error)
	GetVehicle(ctx context.Context, authHeader bearertoken.Token, vehicleIdArg string) (Vehicle, error)
	UpdateVehicle(ctx context.Context, authHeader bearertoken.Token, vehicleIdArg string, requestArg UpdateVehicleRequest) (Vehicle, error)
	DeleteVehicle(ctx context.Context, authHeader bearertoken.Token, vehicleIdArg string) error
	ListRegistrations(ctx context.Context, authHeader bearertoken.Token, vehicleIdArg string) (RegistrationList, error)
	// Register (or transfer) the vehicle to a new owner; closes any active registration first.
	RegisterVehicle(ctx context.Context, authHeader bearertoken.Token, vehicleIdArg string, requestArg RegisterVehicleRequest) (Registration, error)
	// End an active registration without a new owner (e.g. deregistration).
	CloseRegistration(ctx context.Context, authHeader bearertoken.Token, registrationIdArg string) (Registration, error)
	ListManufacturers(ctx context.Context, authHeader bearertoken.Token, brandIdArg string) (ManufacturerList, error)
	AddManufacturer(ctx context.Context, authHeader bearertoken.Token, brandIdArg string, requestArg AddManufacturerRequest) (Manufacturer, error)
	RemoveManufacturer(ctx context.Context, authHeader bearertoken.Token, manufacturerIdArg string) error
	// Read-only view of the vehicle registrations a person owns (current + historical).
	ListPersonVehicles(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (PersonVehicles, error)
}

// RegisterRoutesVehicleService registers handlers for the VehicleService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesVehicleService(router wrouter.Router, impl VehicleService, routerParams ...wrouter.RouteParam) error {
	handler := vehicleServiceHandler{impl: impl}
	resource := wresource.New("vehicleservice", router)
	if err := resource.Get("ListVehicleTypes", "/vehicle/v1/vehicle-types", httpserver.NewJSONHandler(handler.HandleListVehicleTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listVehicleTypes route")
	}
	if err := resource.Put("UpsertVehicleType", "/vehicle/v1/vehicle-types", httpserver.NewJSONHandler(handler.HandleUpsertVehicleType, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertVehicleType route")
	}
	if err := resource.Get("ListBrands", "/vehicle/v1/brands", httpserver.NewJSONHandler(handler.HandleListBrands, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listBrands route")
	}
	if err := resource.Put("UpsertBrand", "/vehicle/v1/brands", httpserver.NewJSONHandler(handler.HandleUpsertBrand, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertBrand route")
	}
	if err := resource.Get("ListModels", "/vehicle/v1/brands/{brandId}/models", httpserver.NewJSONHandler(handler.HandleListModels, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listModels route")
	}
	if err := resource.Put("UpsertModel", "/vehicle/v1/brands/{brandId}/models", httpserver.NewJSONHandler(handler.HandleUpsertModel, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertModel route")
	}
	if err := resource.Get("ListRegistrationNumberTypes", "/vehicle/v1/registration-number-types", httpserver.NewJSONHandler(handler.HandleListRegistrationNumberTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listRegistrationNumberTypes route")
	}
	if err := resource.Put("UpsertRegistrationNumberType", "/vehicle/v1/registration-number-types", httpserver.NewJSONHandler(handler.HandleUpsertRegistrationNumberType, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add upsertRegistrationNumberType route")
	}
	if err := resource.Post("CreateVehicle", "/vehicle/v1/vehicles", httpserver.NewJSONHandler(handler.HandleCreateVehicle, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createVehicle route")
	}
	if err := resource.Get("ListVehicles", "/vehicle/v1/vehicles", httpserver.NewJSONHandler(handler.HandleListVehicles, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listVehicles route")
	}
	if err := resource.Get("VehicleStats", "/vehicle/v1/stats/vehicles", httpserver.NewJSONHandler(handler.HandleVehicleStats, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add vehicleStats route")
	}
	if err := resource.Get("GetVehicle", "/vehicle/v1/vehicles/{vehicleId}", httpserver.NewJSONHandler(handler.HandleGetVehicle, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getVehicle route")
	}
	if err := resource.Put("UpdateVehicle", "/vehicle/v1/vehicles/{vehicleId}", httpserver.NewJSONHandler(handler.HandleUpdateVehicle, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateVehicle route")
	}
	if err := resource.Delete("DeleteVehicle", "/vehicle/v1/vehicles/{vehicleId}", httpserver.NewJSONHandler(handler.HandleDeleteVehicle, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add deleteVehicle route")
	}
	if err := resource.Get("ListRegistrations", "/vehicle/v1/vehicles/{vehicleId}/registrations", httpserver.NewJSONHandler(handler.HandleListRegistrations, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listRegistrations route")
	}
	if err := resource.Post("RegisterVehicle", "/vehicle/v1/vehicles/{vehicleId}/registrations", httpserver.NewJSONHandler(handler.HandleRegisterVehicle, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add registerVehicle route")
	}
	if err := resource.Post("CloseRegistration", "/vehicle/v1/registrations/{registrationId}/close", httpserver.NewJSONHandler(handler.HandleCloseRegistration, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add closeRegistration route")
	}
	if err := resource.Get("ListManufacturers", "/vehicle/v1/brands/{brandId}/manufacturers", httpserver.NewJSONHandler(handler.HandleListManufacturers, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listManufacturers route")
	}
	if err := resource.Post("AddManufacturer", "/vehicle/v1/brands/{brandId}/manufacturers", httpserver.NewJSONHandler(handler.HandleAddManufacturer, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add addManufacturer route")
	}
	if err := resource.Delete("RemoveManufacturer", "/vehicle/v1/manufacturers/{manufacturerId}", httpserver.NewJSONHandler(handler.HandleRemoveManufacturer, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add removeManufacturer route")
	}
	if err := resource.Get("ListPersonVehicles", "/vehicle/v1/persons/{personId}/vehicles", httpserver.NewJSONHandler(handler.HandleListPersonVehicles, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPersonVehicles route")
	}
	return nil
}

type vehicleServiceHandler struct {
	impl VehicleService
}

func (v *vehicleServiceHandler) HandleListVehicleTypes(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := v.impl.ListVehicleTypes(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleUpsertVehicleType(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertVehicleTypeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.UpsertVehicleType(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleListBrands(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	respArg, err := v.impl.ListBrands(req.Context(), bearertoken.Token(authHeader), queryArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleUpsertBrand(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertBrandRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.UpsertBrand(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleListModels(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	brandIdArg, ok := pathParams["brandId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"brandId\" not present")
	}
	respArg, err := v.impl.ListModels(req.Context(), bearertoken.Token(authHeader), brandIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleUpsertModel(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	brandIdArg, ok := pathParams["brandId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"brandId\" not present")
	}
	var requestArg UpsertModelRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.UpsertModel(req.Context(), bearertoken.Token(authHeader), brandIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleListRegistrationNumberTypes(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := v.impl.ListRegistrationNumberTypes(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleUpsertRegistrationNumberType(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg UpsertNumberTypeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.UpsertRegistrationNumberType(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleCreateVehicle(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateVehicleRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.CreateVehicle(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleListVehicles(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var typeIdArg *string
	if typeIdArgStr := req.URL.Query().Get("typeId"); typeIdArgStr != "" {
		typeIdArgInternal := typeIdArgStr
		typeIdArg = &typeIdArgInternal
	}
	var brandIdArg *string
	if brandIdArgStr := req.URL.Query().Get("brandId"); brandIdArgStr != "" {
		brandIdArgInternal := brandIdArgStr
		brandIdArg = &brandIdArgInternal
	}
	var modelIdArg *string
	if modelIdArgStr := req.URL.Query().Get("modelId"); modelIdArgStr != "" {
		modelIdArgInternal := modelIdArgStr
		modelIdArg = &modelIdArgInternal
	}
	var colorArg *string
	if colorArgStr := req.URL.Query().Get("color"); colorArgStr != "" {
		colorArgInternal := colorArgStr
		colorArg = &colorArgInternal
	}
	var statusArg *string
	if statusArgStr := req.URL.Query().Get("status"); statusArgStr != "" {
		statusArgInternal := statusArgStr
		statusArg = &statusArgInternal
	}
	var manufactureDateFromArg *string
	if manufactureDateFromArgStr := req.URL.Query().Get("manufactureDateFrom"); manufactureDateFromArgStr != "" {
		manufactureDateFromArgInternal := manufactureDateFromArgStr
		manufactureDateFromArg = &manufactureDateFromArgInternal
	}
	var manufactureDateToArg *string
	if manufactureDateToArgStr := req.URL.Query().Get("manufactureDateTo"); manufactureDateToArgStr != "" {
		manufactureDateToArgInternal := manufactureDateToArgStr
		manufactureDateToArg = &manufactureDateToArgInternal
	}
	var registrationCountryArg *string
	if registrationCountryArgStr := req.URL.Query().Get("registrationCountry"); registrationCountryArgStr != "" {
		registrationCountryArgInternal := registrationCountryArgStr
		registrationCountryArg = &registrationCountryArgInternal
	}
	var pageSizeArg *int
	if pageSizeArgStr := req.URL.Query().Get("pageSize"); pageSizeArgStr != "" {
		pageSizeArgInternal, err := strconv.Atoi(pageSizeArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"pageSize\" as integer")
		}
		pageSizeArg = &pageSizeArgInternal
	}
	var pageTokenArg *string
	if pageTokenArgStr := req.URL.Query().Get("pageToken"); pageTokenArgStr != "" {
		pageTokenArgInternal := pageTokenArgStr
		pageTokenArg = &pageTokenArgInternal
	}
	respArg, err := v.impl.ListVehicles(req.Context(), bearertoken.Token(authHeader), queryArg, typeIdArg, brandIdArg, modelIdArg, colorArg, statusArg, manufactureDateFromArg, manufactureDateToArg, registrationCountryArg, pageSizeArg, pageTokenArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleVehicleStats(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var facetsArg *string
	if facetsArgStr := req.URL.Query().Get("facets"); facetsArgStr != "" {
		facetsArgInternal := facetsArgStr
		facetsArg = &facetsArgInternal
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var typeIdArg *string
	if typeIdArgStr := req.URL.Query().Get("typeId"); typeIdArgStr != "" {
		typeIdArgInternal := typeIdArgStr
		typeIdArg = &typeIdArgInternal
	}
	var brandIdArg *string
	if brandIdArgStr := req.URL.Query().Get("brandId"); brandIdArgStr != "" {
		brandIdArgInternal := brandIdArgStr
		brandIdArg = &brandIdArgInternal
	}
	var modelIdArg *string
	if modelIdArgStr := req.URL.Query().Get("modelId"); modelIdArgStr != "" {
		modelIdArgInternal := modelIdArgStr
		modelIdArg = &modelIdArgInternal
	}
	var colorArg *string
	if colorArgStr := req.URL.Query().Get("color"); colorArgStr != "" {
		colorArgInternal := colorArgStr
		colorArg = &colorArgInternal
	}
	var statusArg *string
	if statusArgStr := req.URL.Query().Get("status"); statusArgStr != "" {
		statusArgInternal := statusArgStr
		statusArg = &statusArgInternal
	}
	var manufactureDateFromArg *string
	if manufactureDateFromArgStr := req.URL.Query().Get("manufactureDateFrom"); manufactureDateFromArgStr != "" {
		manufactureDateFromArgInternal := manufactureDateFromArgStr
		manufactureDateFromArg = &manufactureDateFromArgInternal
	}
	var manufactureDateToArg *string
	if manufactureDateToArgStr := req.URL.Query().Get("manufactureDateTo"); manufactureDateToArgStr != "" {
		manufactureDateToArgInternal := manufactureDateToArgStr
		manufactureDateToArg = &manufactureDateToArgInternal
	}
	var registrationCountryArg *string
	if registrationCountryArgStr := req.URL.Query().Get("registrationCountry"); registrationCountryArgStr != "" {
		registrationCountryArgInternal := registrationCountryArgStr
		registrationCountryArg = &registrationCountryArgInternal
	}
	respArg, err := v.impl.VehicleStats(req.Context(), bearertoken.Token(authHeader), facetsArg, queryArg, typeIdArg, brandIdArg, modelIdArg, colorArg, statusArg, manufactureDateFromArg, manufactureDateToArg, registrationCountryArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleGetVehicle(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	vehicleIdArg, ok := pathParams["vehicleId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"vehicleId\" not present")
	}
	respArg, err := v.impl.GetVehicle(req.Context(), bearertoken.Token(authHeader), vehicleIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleUpdateVehicle(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	vehicleIdArg, ok := pathParams["vehicleId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"vehicleId\" not present")
	}
	var requestArg UpdateVehicleRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.UpdateVehicle(req.Context(), bearertoken.Token(authHeader), vehicleIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleDeleteVehicle(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	vehicleIdArg, ok := pathParams["vehicleId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"vehicleId\" not present")
	}
	if err := v.impl.DeleteVehicle(req.Context(), bearertoken.Token(authHeader), vehicleIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (v *vehicleServiceHandler) HandleListRegistrations(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	vehicleIdArg, ok := pathParams["vehicleId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"vehicleId\" not present")
	}
	respArg, err := v.impl.ListRegistrations(req.Context(), bearertoken.Token(authHeader), vehicleIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleRegisterVehicle(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	vehicleIdArg, ok := pathParams["vehicleId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"vehicleId\" not present")
	}
	var requestArg RegisterVehicleRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.RegisterVehicle(req.Context(), bearertoken.Token(authHeader), vehicleIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleCloseRegistration(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	registrationIdArg, ok := pathParams["registrationId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"registrationId\" not present")
	}
	respArg, err := v.impl.CloseRegistration(req.Context(), bearertoken.Token(authHeader), registrationIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleListManufacturers(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	brandIdArg, ok := pathParams["brandId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"brandId\" not present")
	}
	respArg, err := v.impl.ListManufacturers(req.Context(), bearertoken.Token(authHeader), brandIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleAddManufacturer(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	brandIdArg, ok := pathParams["brandId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"brandId\" not present")
	}
	var requestArg AddManufacturerRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.AddManufacturer(req.Context(), bearertoken.Token(authHeader), brandIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vehicleServiceHandler) HandleRemoveManufacturer(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	manufacturerIdArg, ok := pathParams["manufacturerId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"manufacturerId\" not present")
	}
	if err := v.impl.RemoveManufacturer(req.Context(), bearertoken.Token(authHeader), manufacturerIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (v *vehicleServiceHandler) HandleListPersonVehicles(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	respArg, err := v.impl.ListPersonVehicles(req.Context(), bearertoken.Token(authHeader), personIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}
