// Code generated by conjure-go. DO NOT EDIT.

package vehicle

import (
	"github.com/palantir/pkg/datetime"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

// Record that a company manufactures this brand (temporal).
type AddManufacturerRequest struct {
	CompanyId     string  `json:"companyId"`
	EffectiveFrom *string `json:"effectiveFrom,omitempty"`
	EffectiveTo   *string `json:"effectiveTo,omitempty"`
}

func (o AddManufacturerRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *AddManufacturerRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A vehicle marque (Toyota/BMW…); countryId is the country of origin (nullable).
type Brand struct {
	Id        string            `json:"id"`
	Code      string            `json:"code"`
	Name      map[string]string `json:"name"`
	CountryId *string           `json:"countryId,omitempty"`
	Status    string            `json:"status"`
	SortOrder *int              `json:"sortOrder,omitempty"`
}

func (o Brand) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpBrand Brand
	return safejson.Marshal(_tmpBrand(o))
}

func (o *Brand) UnmarshalJSON(data []byte) error {
	type _tmpBrand Brand
	var rawBrand _tmpBrand
	if err := safejson.Unmarshal(data, &rawBrand); err != nil {
		return err
	}
	if rawBrand.Name == nil {
		rawBrand.Name = make(map[string]string)
	}
	*o = Brand(rawBrand)
	return nil
}

func (o Brand) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Brand) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type BrandList struct {
	Brands []Brand `json:"brands"`
}

func (o BrandList) MarshalJSON() ([]byte, error) {
	if o.Brands == nil {
		o.Brands = make([]Brand, 0)
	}
	type _tmpBrandList BrandList
	return safejson.Marshal(_tmpBrandList(o))
}

func (o *BrandList) UnmarshalJSON(data []byte) error {
	type _tmpBrandList BrandList
	var rawBrandList _tmpBrandList
	if err := safejson.Unmarshal(data, &rawBrandList); err != nil {
		return err
	}
	if rawBrandList.Brands == nil {
		rawBrandList.Brands = make([]Brand, 0)
	}
	*o = BrandList(rawBrandList)
	return nil
}

func (o BrandList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BrandList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CreateVehicleRequest struct {
	TypeId  string  `json:"typeId"`
	ModelId *string `json:"modelId,omitempty"`
	Vin     *string `json:"vin,omitempty"`
	// A platform_colors RID (domain='vehicle', D-Color).
	ColorId         *string `json:"colorId,omitempty"`
	ManufactureDate *string `json:"manufactureDate,omitempty"`
	// A JSON object string; defaults to {}.
	Attributes *string `json:"attributes,omitempty"`
}

func (o CreateVehicleRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateVehicleRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A brand is MANUFACTURED_BY a company (link__manufactured_by); temporal (changes with acquisitions).
type Manufacturer struct {
	Id        string `json:"id"`
	BrandId   string `json:"brandId"`
	CompanyId string `json:"companyId"`
	// Best-effort company legal name.
	CompanyLabel  *string           `json:"companyLabel,omitempty"`
	EffectiveFrom *string           `json:"effectiveFrom,omitempty"`
	EffectiveTo   *string           `json:"effectiveTo,omitempty"`
	CreatedAt     datetime.DateTime `json:"createdAt"`
	UpdatedAt     datetime.DateTime `json:"updatedAt"`
}

func (o Manufacturer) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Manufacturer) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type ManufacturerList struct {
	Manufacturers []Manufacturer `json:"manufacturers"`
}

func (o ManufacturerList) MarshalJSON() ([]byte, error) {
	if o.Manufacturers == nil {
		o.Manufacturers = make([]Manufacturer, 0)
	}
	type _tmpManufacturerList ManufacturerList
	return safejson.Marshal(_tmpManufacturerList(o))
}

func (o *ManufacturerList) UnmarshalJSON(data []byte) error {
	type _tmpManufacturerList ManufacturerList
	var rawManufacturerList _tmpManufacturerList
	if err := safejson.Unmarshal(data, &rawManufacturerList); err != nil {
		return err
	}
	if rawManufacturerList.Manufacturers == nil {
		rawManufacturerList.Manufacturers = make([]Manufacturer, 0)
	}
	*o = ManufacturerList(rawManufacturerList)
	return nil
}

func (o ManufacturerList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ManufacturerList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A model under a brand (containment); generation + the manufacture window are structural specs.
type Model struct {
	Id               string            `json:"id"`
	BrandId          string            `json:"brandId"`
	Code             string            `json:"code"`
	Name             map[string]string `json:"name"`
	Generation       *string           `json:"generation,omitempty"`
	ManufactureStart *string           `json:"manufactureStart,omitempty"`
	ManufactureEnd   *string           `json:"manufactureEnd,omitempty"`
	Status           string            `json:"status"`
	SortOrder        *int              `json:"sortOrder,omitempty"`
}

func (o Model) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpModel Model
	return safejson.Marshal(_tmpModel(o))
}

func (o *Model) UnmarshalJSON(data []byte) error {
	type _tmpModel Model
	var rawModel _tmpModel
	if err := safejson.Unmarshal(data, &rawModel); err != nil {
		return err
	}
	if rawModel.Name == nil {
		rawModel.Name = make(map[string]string)
	}
	*o = Model(rawModel)
	return nil
}

func (o Model) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Model) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type ModelList struct {
	Models []Model `json:"models"`
}

func (o ModelList) MarshalJSON() ([]byte, error) {
	if o.Models == nil {
		o.Models = make([]Model, 0)
	}
	type _tmpModelList ModelList
	return safejson.Marshal(_tmpModelList(o))
}

func (o *ModelList) UnmarshalJSON(data []byte) error {
	type _tmpModelList ModelList
	var rawModelList _tmpModelList
	if err := safejson.Unmarshal(data, &rawModelList); err != nil {
		return err
	}
	if rawModelList.Models == nil {
		rawModelList.Models = make([]Model, 0)
	}
	*o = ModelList(rawModelList)
	return nil
}

func (o ModelList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ModelList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A vehicle registration a person owns, enriched with the vehicle's identity (read-only).
type PersonVehicleRegistration struct {
	Id                 string             `json:"id"`
	VehicleId          string             `json:"vehicleId"`
	Vin                *string            `json:"vin,omitempty"`
	TypeLabel          *string            `json:"typeLabel,omitempty"`
	BrandLabel         *string            `json:"brandLabel,omitempty"`
	ModelLabel         *string            `json:"modelLabel,omitempty"`
	RegistrationNumber string             `json:"registrationNumber"`
	CountryId          string             `json:"countryId"`
	SubdivisionLabel   *string            `json:"subdivisionLabel,omitempty"`
	Status             string             `json:"status"`
	EffectiveFrom      datetime.DateTime  `json:"effectiveFrom"`
	EffectiveTo        *datetime.DateTime `json:"effectiveTo,omitempty"`
}

func (o PersonVehicleRegistration) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *PersonVehicleRegistration) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A person's vehicle registrations (current + historical, newest first).
type PersonVehicles struct {
	Registrations []PersonVehicleRegistration `json:"registrations"`
}

func (o PersonVehicles) MarshalJSON() ([]byte, error) {
	if o.Registrations == nil {
		o.Registrations = make([]PersonVehicleRegistration, 0)
	}
	type _tmpPersonVehicles PersonVehicles
	return safejson.Marshal(_tmpPersonVehicles(o))
}

func (o *PersonVehicles) UnmarshalJSON(data []byte) error {
	type _tmpPersonVehicles PersonVehicles
	var rawPersonVehicles _tmpPersonVehicles
	if err := safejson.Unmarshal(data, &rawPersonVehicles); err != nil {
		return err
	}
	if rawPersonVehicles.Registrations == nil {
		rawPersonVehicles.Registrations = make([]PersonVehicleRegistration, 0)
	}
	*o = PersonVehicles(rawPersonVehicles)
	return nil
}

func (o PersonVehicles) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *PersonVehicles) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
Register the vehicle to a new owner (person or company). Any currently-active registration for
the vehicle is closed first (registration is the ownership history), so this also performs a
transfer. subdivisionId (the plate region) must be a geo_places region when supplied.
*/
type RegisterVehicleRequest struct {
	OwnerKind          string             `json:"ownerKind"`
	OwnerId            string             `json:"ownerId"`
	CountryId          string             `json:"countryId"`
	SubdivisionId      *string            `json:"subdivisionId,omitempty"`
	RegistrationNumber string             `json:"registrationNumber"`
	NumberTypeId       *string            `json:"numberTypeId,omitempty"`
	EffectiveFrom      *datetime.DateTime `json:"effectiveFrom,omitempty"`
}

func (o RegisterVehicleRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RegisterVehicleRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
The ownership+plate record (link__registered_to). The owner is a person OR a company
(polymorphic). country/subdivision carry the registering country + optional plate region. A
re-registration is a new row (the prior closed), so registration IS the ownership history.
*/
type Registration struct {
	Id        string `json:"id"`
	VehicleId string `json:"vehicleId"`
	// One of person | company.
	OwnerKind string `json:"ownerKind"`
	OwnerId   string `json:"ownerId"`
	// Best-effort display label (company legal name for company owners; empty for persons).
	OwnerLabel *string `json:"ownerLabel,omitempty"`
	CountryId  string  `json:"countryId"`
	// The plate region — a geo_places RID (placetype=region).
	SubdivisionId      *string `json:"subdivisionId,omitempty"`
	SubdivisionLabel   *string `json:"subdivisionLabel,omitempty"`
	RegistrationNumber string  `json:"registrationNumber"`
	NumberTypeId       *string `json:"numberTypeId,omitempty"`
	// One of active | closed.
	Status        string             `json:"status"`
	EffectiveFrom datetime.DateTime  `json:"effectiveFrom"`
	EffectiveTo   *datetime.DateTime `json:"effectiveTo,omitempty"`
	CreatedAt     datetime.DateTime  `json:"createdAt"`
	UpdatedAt     datetime.DateTime  `json:"updatedAt"`
}

func (o Registration) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Registration) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type RegistrationList struct {
	Registrations []Registration `json:"registrations"`
}

func (o RegistrationList) MarshalJSON() ([]byte, error) {
	if o.Registrations == nil {
		o.Registrations = make([]Registration, 0)
	}
	type _tmpRegistrationList RegistrationList
	return safejson.Marshal(_tmpRegistrationList(o))
}

func (o *RegistrationList) UnmarshalJSON(data []byte) error {
	type _tmpRegistrationList RegistrationList
	var rawRegistrationList _tmpRegistrationList
	if err := safejson.Unmarshal(data, &rawRegistrationList); err != nil {
		return err
	}
	if rawRegistrationList.Registrations == nil {
		rawRegistrationList.Registrations = make([]Registration, 0)
	}
	*o = RegistrationList(rawRegistrationList)
	return nil
}

func (o RegistrationList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RegistrationList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A plate-type catalog entry (regular/temporary/transit/diplomatic/military/old…).
type RegistrationNumberType struct {
	Id        string            `json:"id"`
	Code      string            `json:"code"`
	Name      map[string]string `json:"name"`
	Status    string            `json:"status"`
	SortOrder *int              `json:"sortOrder,omitempty"`
}

func (o RegistrationNumberType) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpRegistrationNumberType RegistrationNumberType
	return safejson.Marshal(_tmpRegistrationNumberType(o))
}

func (o *RegistrationNumberType) UnmarshalJSON(data []byte) error {
	type _tmpRegistrationNumberType RegistrationNumberType
	var rawRegistrationNumberType _tmpRegistrationNumberType
	if err := safejson.Unmarshal(data, &rawRegistrationNumberType); err != nil {
		return err
	}
	if rawRegistrationNumberType.Name == nil {
		rawRegistrationNumberType.Name = make(map[string]string)
	}
	*o = RegistrationNumberType(rawRegistrationNumberType)
	return nil
}

func (o RegistrationNumberType) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RegistrationNumberType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type RegistrationNumberTypeList struct {
	NumberTypes []RegistrationNumberType `json:"numberTypes"`
}

func (o RegistrationNumberTypeList) MarshalJSON() ([]byte, error) {
	if o.NumberTypes == nil {
		o.NumberTypes = make([]RegistrationNumberType, 0)
	}
	type _tmpRegistrationNumberTypeList RegistrationNumberTypeList
	return safejson.Marshal(_tmpRegistrationNumberTypeList(o))
}

func (o *RegistrationNumberTypeList) UnmarshalJSON(data []byte) error {
	type _tmpRegistrationNumberTypeList RegistrationNumberTypeList
	var rawRegistrationNumberTypeList _tmpRegistrationNumberTypeList
	if err := safejson.Unmarshal(data, &rawRegistrationNumberTypeList); err != nil {
		return err
	}
	if rawRegistrationNumberTypeList.NumberTypes == nil {
		rawRegistrationNumberTypeList.NumberTypes = make([]RegistrationNumberType, 0)
	}
	*o = RegistrationNumberTypeList(rawRegistrationNumberTypeList)
	return nil
}

func (o RegistrationNumberTypeList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RegistrationNumberTypeList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Update type/model/vin/colorId/date/attributes/status; omitted fields are unchanged.
type UpdateVehicleRequest struct {
	TypeId  *string `json:"typeId,omitempty"`
	ModelId *string `json:"modelId,omitempty"`
	Vin     *string `json:"vin,omitempty"`
	// A platform_colors RID (domain='vehicle', D-Color).
	ColorId         *string `json:"colorId,omitempty"`
	ManufactureDate *string `json:"manufactureDate,omitempty"`
	Attributes      *string `json:"attributes,omitempty"`
	Status          *string `json:"status,omitempty"`
}

func (o UpdateVehicleRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateVehicleRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpsertBrandRequest struct {
	Code      string  `json:"code"`
	Name      string  `json:"name"`
	CountryId *string `json:"countryId,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

func (o UpsertBrandRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpsertBrandRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpsertModelRequest struct {
	Code             string  `json:"code"`
	Name             string  `json:"name"`
	Generation       *string `json:"generation,omitempty"`
	ManufactureStart *string `json:"manufactureStart,omitempty"`
	ManufactureEnd   *string `json:"manufactureEnd,omitempty"`
	SortOrder        *int    `json:"sortOrder,omitempty"`
}

func (o UpsertModelRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpsertModelRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpsertNumberTypeRequest struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder *int   `json:"sortOrder,omitempty"`
}

func (o UpsertNumberTypeRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpsertNumberTypeRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Create/update (by code) a vehicle-type catalog node. name is the default-locale fallback.
type UpsertVehicleTypeRequest struct {
	Code      string  `json:"code"`
	Name      string  `json:"name"`
	ParentId  *string `json:"parentId,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

func (o UpsertVehicleTypeRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpsertVehicleTypeRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A physical vehicle at registry grade. Soft-deleted, not destroyed. The RID is the external handle.
type Vehicle struct {
	Id     string `json:"id"`
	TypeId string `json:"typeId"`
	// Best-effort default-locale type name.
	TypeLabel  *string `json:"typeLabel,omitempty"`
	ModelId    *string `json:"modelId,omitempty"`
	ModelLabel *string `json:"modelLabel,omitempty"`
	// The brand of the model (derived), when a model is set.
	BrandId    *string `json:"brandId,omitempty"`
	BrandLabel *string `json:"brandLabel,omitempty"`
	Vin        *string `json:"vin,omitempty"`
	// The vehicle's color — a platform_colors RID (domain='vehicle', D-Color). Resolve label/hex via the platform color catalog.
	ColorId         *string `json:"colorId,omitempty"`
	ManufactureDate *string `json:"manufactureDate,omitempty"`
	// Long-tail spec grab-bag as a JSON string (DS-53 will column-ize stabilized fields).
	Attributes *string `json:"attributes,omitempty"`
	// One of active | scrapped | exported.
	Status    string            `json:"status"`
	CreatedAt datetime.DateTime `json:"createdAt"`
	UpdatedAt datetime.DateTime `json:"updatedAt"`
}

func (o Vehicle) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Vehicle) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type VehiclePage struct {
	Vehicles      []Vehicle `json:"vehicles"`
	NextPageToken *string   `json:"nextPageToken,omitempty"`
}

func (o VehiclePage) MarshalJSON() ([]byte, error) {
	if o.Vehicles == nil {
		o.Vehicles = make([]Vehicle, 0)
	}
	type _tmpVehiclePage VehiclePage
	return safejson.Marshal(_tmpVehiclePage(o))
}

func (o *VehiclePage) UnmarshalJSON(data []byte) error {
	type _tmpVehiclePage VehiclePage
	var rawVehiclePage _tmpVehiclePage
	if err := safejson.Unmarshal(data, &rawVehiclePage); err != nil {
		return err
	}
	if rawVehiclePage.Vehicles == nil {
		rawVehiclePage.Vehicles = make([]Vehicle, 0)
	}
	*o = VehiclePage(rawVehiclePage)
	return nil
}

func (o VehiclePage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *VehiclePage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// A vehicle taxonomy node (car/truck/motorcycle…); a shallow tree (parentId + denormalized rootId).
type VehicleType struct {
	Id   string `json:"id"`
	Code string `json:"code"`
	// Default-locale fallback + i18n translations.
	Name      map[string]string `json:"name"`
	ParentId  *string           `json:"parentId,omitempty"`
	RootId    *string           `json:"rootId,omitempty"`
	Status    string            `json:"status"`
	SortOrder *int              `json:"sortOrder,omitempty"`
}

func (o VehicleType) MarshalJSON() ([]byte, error) {
	if o.Name == nil {
		o.Name = make(map[string]string)
	}
	type _tmpVehicleType VehicleType
	return safejson.Marshal(_tmpVehicleType(o))
}

func (o *VehicleType) UnmarshalJSON(data []byte) error {
	type _tmpVehicleType VehicleType
	var rawVehicleType _tmpVehicleType
	if err := safejson.Unmarshal(data, &rawVehicleType); err != nil {
		return err
	}
	if rawVehicleType.Name == nil {
		rawVehicleType.Name = make(map[string]string)
	}
	*o = VehicleType(rawVehicleType)
	return nil
}

func (o VehicleType) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *VehicleType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type VehicleTypeList struct {
	Types []VehicleType `json:"types"`
}

func (o VehicleTypeList) MarshalJSON() ([]byte, error) {
	if o.Types == nil {
		o.Types = make([]VehicleType, 0)
	}
	type _tmpVehicleTypeList VehicleTypeList
	return safejson.Marshal(_tmpVehicleTypeList(o))
}

func (o *VehicleTypeList) UnmarshalJSON(data []byte) error {
	type _tmpVehicleTypeList VehicleTypeList
	var rawVehicleTypeList _tmpVehicleTypeList
	if err := safejson.Unmarshal(data, &rawVehicleTypeList); err != nil {
		return err
	}
	if rawVehicleTypeList.Types == nil {
		rawVehicleTypeList.Types = make([]VehicleType, 0)
	}
	*o = VehicleTypeList(rawVehicleTypeList)
	return nil
}

func (o VehicleTypeList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *VehicleTypeList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
